export interface IPaper2QuestionSeed {
  subjectSlug: string;
  topicSlug: string;
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  questionType: 'PYQ' | 'PYQ_INSPIRED' | 'PRACTICE';
  sourceType: string;
  sourceYear?: number;
}

export const PAPER_2_QUESTIONS: IPaper2QuestionSeed[] = [
  // 1. Traditional Tribal Governance (14 Qs)
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-nagvanshi-governance',
    questionText: 'In the traditional Munda village governance system, who acts as the religious and spiritual head of the village?',
    optionA: 'Munda',
    optionB: 'Pahan',
    optionC: 'Pujjar / Panbhara',
    optionD: 'Mahto',
    correctAnswer: 'B',
    explanation: 'In the Munda administrative system, the Pahan is the sacred village priest who performs all religious rituals and sacrifices. The Munda is the secular head, and the Pujjar assists the Pahan.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-nagvanshi-governance',
    questionText: 'What was the rent-free land given to the Pahan for performing village religious duties known as in Munda society?',
    optionA: 'Bhutkheta',
    optionB: 'Dalikatari',
    optionC: 'Pahanai land',
    optionD: 'Majhias',
    correctAnswer: 'B',
    explanation: 'Dalikatari is the agricultural land allocated rent-free to the Pahan for meeting the expenses of public worship and religious ceremonies.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-nagvanshi-governance',
    questionText: 'Who was the first historical ruler and founder of the Nagvanshi dynasty of Chotanagpur?',
    optionA: 'Phani Mukut Rai',
    optionB: 'Madra Munda',
    optionC: 'Pratap Rai',
    optionD: 'Durjan Sal',
    correctAnswer: 'A',
    explanation: 'Phani Mukut Rai, the adopted son of Madra Munda, founded the Nagvanshi dynasty in the 1st century AD (approx. 64 AD), establishing his capital at Sutiambe.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'padha-panchayat-manjhi',
    questionText: 'In the Oraon community, the inter-village confederation formed by 7, 12, 21, or 22 villages is known as:',
    optionA: 'Parha / Padha',
    optionB: 'Hatu',
    optionC: 'Killi',
    optionD: 'Dhumkuria',
    correctAnswer: 'A',
    explanation: 'The Parha (or Padha) is the confederation of several Oraon villages headed by the Parha Raja, which resolves disputes that cannot be settled at the village level.',
    difficulty: 'Easy',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'padha-panchayat-manjhi',
    questionText: 'In the Manjhi Pargana governance system of the Santhal tribe, who serves as the principal assistant and executive messenger of the Manjhi?',
    optionA: 'Jog Manjhi',
    optionB: 'Godet (Gorait)',
    optionC: 'Naike',
    optionD: 'Parganait',
    correctAnswer: 'B',
    explanation: 'In the Santhal village council, the Godet serves as the assistant, messenger, and orderly who convenes meetings and communicates decisions of the Manjhi.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'padha-panchayat-manjhi',
    questionText: 'What is the highest social ostracism penalty in the Santhal traditional governance system called?',
    optionA: 'Bitlaha',
    optionB: 'Kareya',
    optionC: 'Lo Bir Sendra',
    optionD: 'Danda Pat',
    correctAnswer: 'A',
    explanation: 'Bitlaha is the extreme social punishment of excommunication imposed by the Santhal community for serious socio-sexual taboos (such as clan incest).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-manki-dhoklo',
    questionText: 'Under the Munda-Manki governance system of the Ho tribe, the head of a cluster of 15 to 20 villages (Pir) is designated as:',
    optionA: 'Munda',
    optionB: 'Manki',
    optionC: 'Deori',
    optionD: 'Tahsildar',
    correctAnswer: 'B',
    explanation: 'In the Ho political organization (Kolhan region), the village headman is the Munda, whereas the head of a Pir (federation of villages) is called the Manki.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-manki-dhoklo',
    questionText: 'Which British administrator officially gave legal recognition to the traditional Munda-Manki system in the Kolhan region in 1837?',
    optionA: 'Thomas Wilkinson',
    optionB: 'Augustus Cleveland',
    optionC: 'Captain Camac',
    optionD: 'J.C. Haughton',
    correctAnswer: 'A',
    explanation: 'Captain Thomas Wilkinson framed the Wilkinson Rules in 1837 following the Kol Insurrection, granting civil and judicial authority to traditional Mankis and Mundas.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-manki-dhoklo',
    questionText: 'The traditional community governance system of the Kharia tribe is known as:',
    optionA: 'Manjhi Pargana System',
    optionB: 'Dhoklo Sohor System',
    optionC: 'Parha Panchayat System',
    optionD: 'Munda-Manki System',
    correctAnswer: 'B',
    explanation: 'The Kharia tribe’s socio-political council is called Dhoklo Sohor (Dhoklo meaning assembly/meeting, and Sohor meaning president or supreme leader).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-manki-dhoklo',
    questionText: 'In the Kharia Dhoklo Sohor administration, who maintains the account books and financial records of the community?',
    optionA: 'Likhakar (Secretary)',
    optionB: 'Tinjokad (Treasurer)',
    optionC: 'Deonrha',
    optionD: 'Kalo',
    correctAnswer: 'B',
    explanation: 'In the all-Kharia assembly (Dhoklo Sohor), the Tinjokad acts as the treasurer/fund-keeper, while the Likhakar handles correspondence and records.',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'padha-panchayat-manjhi',
    questionText: 'In the Santhal village council, who is responsible for guiding youth, preserving moral conduct, and managing marriage rituals?',
    optionA: 'Naike',
    optionB: 'Jog Manjhi',
    optionC: 'Kudam Naike',
    optionD: 'Pradhan',
    correctAnswer: 'B',
    explanation: 'Jog Manjhi is the deputy headman entrusted with supervising the conduct of village youth, marriage negotiations, and birth ceremonies.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-nagvanshi-governance',
    questionText: 'Which Nagvanshi king shifted his capital from Sutiambe to Chutia on the banks of the Swarnarekha river?',
    optionA: 'Phani Mukut Rai',
    optionB: 'Pratap Rai',
    optionC: 'Bhim Karn',
    optionD: 'Durjan Sal',
    correctAnswer: 'B',
    explanation: 'King Pratap Rai shifted the Nagvanshi royal capital from Sutiambe to Chutia (now in modern Ranchi city).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'padha-panchayat-manjhi',
    questionText: 'The supreme judicial body and annual hunt council of the Santhals that acts as the final appellate authority is called:',
    optionA: 'Lo Bir Sendra',
    optionB: 'Disom Pargana',
    optionC: 'Kudam Naike Sabha',
    optionD: 'Hatu Panchayat',
    correctAnswer: 'A',
    explanation: 'Lo Bir Sendra (the hunt council in the forest) is the highest democratic appeal court of the Santhals where even the village headman can be tried on equal footing.',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-tribal-governance',
    topicSlug: 'munda-nagvanshi-governance',
    questionText: 'In Oraon society, who assists the Pahan in social matters and acts as the secular administrative head of the village?',
    optionA: 'Mahto',
    optionB: 'Kotwar',
    optionC: 'Gorait',
    optionD: 'Panbhara',
    correctAnswer: 'A',
    explanation: 'In the Oraon village structure, the Mahto is the secular administrative chief, whereas the Pahan is the spiritual leader.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },

  // 2. Jharkhand Movements & Personalities (13 Qs)
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'freedom-fighters-personalities',
    questionText: 'Birsa Munda launched his historic "Ulgulan" (The Great Tumult) rebellion in which year?',
    optionA: '1857',
    optionB: '1885',
    optionC: '1895',
    optionD: '1905',
    correctAnswer: 'C',
    explanation: 'Birsa Munda proclaimed his divine mission and initiated the Ulgulan movement in 1895 against British colonial exploitation, landlords, and Christian missionaries.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'freedom-fighters-personalities',
    questionText: 'On which hill did Birsa Munda and his guerrilla followers fight their famous pitched battle against British forces on January 9, 1900?',
    optionA: 'Parasnath Hill',
    optionB: 'Dombari Buru',
    optionC: 'Trikut Hill',
    optionD: 'Tagore Hill',
    correctAnswer: 'B',
    explanation: 'The battle of Dombari Buru (Sail Rakab) in Khunti district was fought on January 9, 1900, where hundreds of Munda men, women, and children were fired upon by British forces.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'tribal-uprisings-rebellions',
    questionText: 'The Santhal Hool (Rebellion) of 1855–56 was spearheaded under the leadership of four brothers, namely:',
    optionA: 'Sidho, Kanho, Chand, and Bhairav',
    optionB: 'Birsa, Gaya, Sugna, and Komta',
    optionC: 'Tilka, Jitu, Mangal, and Madra',
    optionD: 'Budhu, Jatra, Tana, and Ganga',
    correctAnswer: 'A',
    explanation: 'The Santhal rebellion of 1855 was led by the four Murmu brothers: Sidho, Kanho, Chand, and Bhairav from Bhagnadih village.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'tribal-uprisings-rebellions',
    questionText: 'Who was the first tribal martyr of Jharkhand who shot British officer Augustus Cleveland with an arrow from a banyan tree in 1784?',
    optionA: 'Birsa Munda',
    optionB: 'Baba Tilka Manjhi',
    optionC: 'Telanga Kharia',
    optionD: 'Pandit Raghunath Murmu',
    correctAnswer: 'B',
    explanation: 'Baba Tilka Manjhi ambushed and killed Collector Augustus Cleveland in 1784 and was subsequently hanged at Bhagalpur in 1785, becoming Jharkhand’s first tribal martyr.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'tribal-uprisings-rebellions',
    questionText: 'The Kol Rebellion of 1831–32 in Chotanagpur broke out under the prime leadership of:',
    optionA: 'Bindo Manki and Singrai Manki',
    optionB: 'Budhu Bhagat and Madho Singh',
    optionC: 'Ganga Narayan Singh',
    optionD: 'Both A and B',
    correctAnswer: 'D',
    explanation: 'The Kol Insurrection was ignited when lands of Singrai Manki were alienated, and spread rapidly under leaders like Bindo Manki, Singrai Manki, and Budhu Bhagat of Silagai.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'tribal-uprisings-rebellions',
    questionText: 'The Bhumij Revolt of 1832–33 in Dhalbhum and Manbhum is popularly known by which name in colonial history?',
    optionA: 'Ganga Narayan Ka Hangama',
    optionB: 'Santhal Hool',
    optionC: 'Sardari Larai',
    optionD: 'Kherwar Movement',
    correctAnswer: 'A',
    explanation: 'The British termed the Bhumij rebellion as "Ganga Narayan Ka Hangama" (Ganga Narayan’s turmoil) after its valiant leader Ganga Narayan Singh.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'tribal-uprisings-rebellions',
    questionText: 'Jatra Bhagat initiated the monotheistic, non-violent Tana Bhagat Movement in which year?',
    optionA: '1914',
    optionB: '1920',
    optionC: '1930',
    optionD: '1942',
    correctAnswer: 'A',
    explanation: 'Jatra Bhagat started the Tana Bhagat Movement in April 1914 in Gumla district, preaching pure vegetarianism, devotion to Dharmesh, and non-violent resistance to rent.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'statehood-movement',
    questionText: 'Who founded the "Chotanagpur Unnati Samaj" in 1915, marking the formal beginning of political organization for tribal rights?',
    optionA: 'Jaipal Singh Munda',
    optionB: 'Juel Lakra',
    optionC: 'Theodore Surin',
    optionD: 'Kartik Oraon',
    correctAnswer: 'B',
    explanation: 'Juel Lakra along with Paul Dayal, Bandi Ram Oraon, and Theble Oraon established the Chotanagpur Unnati Samaj in 1915.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'statehood-movement',
    questionText: 'In 1928, which committee was presented with a memorandum by the Chotanagpur Unnati Samaj demanding a separate administrative state for tribals?',
    optionA: 'Simon Commission',
    optionB: 'Cabinet Mission',
    optionC: 'Hunter Commission',
    optionD: 'Fazal Ali Commission',
    correctAnswer: 'A',
    explanation: 'In 1928, a delegation led by Bishop Van Hoven and Juel Lakra submitted a formal memorandum to the Simon Commission in Patna demanding separate status for Chotanagpur.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'statehood-movement',
    questionText: 'The Adivasi Mahasabha was formed in 1938 and headed in 1939 by which iconic leader and Olympic gold medal-winning hockey captain?',
    optionA: 'Kartik Oraon',
    optionB: 'Jaipal Singh Munda',
    optionC: 'Shibu Soren',
    optionD: 'Ram Dayal Munda',
    correctAnswer: 'B',
    explanation: 'Jaipal Singh Munda (Marang Gomke) presided over the historic Adivasi Mahasabha in 1939 and led the crusade for a separate Jharkhand state.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'statehood-movement',
    questionText: 'The Jharkhand Mukti Morcha (JMM) was officially founded on February 4, 1973 at Dhanbad by Vinod Bihari Mahto, Shibu Soren, and:',
    optionA: 'A.K. Roy',
    optionB: 'Nirmal Mahto',
    optionC: 'Suraj Mandal',
    optionD: 'Teklal Mahto',
    correctAnswer: 'A',
    explanation: 'JMM was established on February 4, 1973 at the Golf Ground in Dhanbad under the alliance of Vinod Bihari Mahto (President), Shibu Soren (General Secretary), and trade unionist A.K. Roy.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'statehood-movement',
    questionText: 'The Jharkhand Area Autonomous Council (JAAC) was constituted on which date under the chairmanship of Shibu Soren?',
    optionA: '9th August 1995',
    optionB: '15th November 2000',
    optionC: '2nd August 1998',
    optionD: '1st January 1994',
    correctAnswer: 'A',
    explanation: 'The Jharkhand Area Autonomous Council (JAAC) was formally sworn in on August 9, 1995, with Shibu Soren as Chairman and Suraj Mandal as Vice-Chairman.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-movements-personalities',
    topicSlug: 'freedom-fighters-personalities',
    questionText: 'During the 1857 Revolt in Ranchi and Doranda, which rebel leaders led the mutiny of the Ramgarh Battalion?',
    optionA: 'Thakur Vishwanath Shahdeo and Pandey Ganpat Rai',
    optionB: 'Nilambar and Pitambar',
    optionC: 'Raja Arjun Singh',
    optionD: 'Sheikh Bhikhari and Tikait Umrao Singh',
    correctAnswer: 'A',
    explanation: 'Thakur Vishwanath Shahdeo (King of Barkagarh) and his Commander-in-Chief Pandey Ganpat Rai led the freedom fighters in Ranchi alongside Jamadar Madho Singh.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },

  // 3. Land Laws: CNT Act 1908 & SPT Act 1949 (14 Qs)
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'The Chotanagpur Tenancy Act (CNT Act) was enacted on which date?',
    optionA: '11th November 1908',
    optionB: '15th November 1908',
    optionC: '26th January 1909',
    optionD: '1st April 1908',
    correctAnswer: 'A',
    explanation: 'The Chotanagpur Tenancy Act came into force on November 11, 1908, prepared largely by Reverend Father John Baptist Hoffmann.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'How many Chapters and Sections are contained in the Chotanagpur Tenancy Act, 1908?',
    optionA: '19 Chapters and 271 Sections',
    optionB: '16 Chapters and 250 Sections',
    optionC: '21 Chapters and 312 Sections',
    optionD: '18 Chapters and 264 Sections',
    correctAnswer: 'A',
    explanation: 'The CNT Act, 1908 comprises 19 Chapters and 271 Sections.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'Under Section 46 of the CNT Act, 1908, a member of a Scheduled Tribe may transfer their land rights to another Scheduled Tribe member only with the prior sanction of the:',
    optionA: 'Deputy Commissioner (DC)',
    optionB: 'Sub-Divisional Officer (SDO)',
    optionC: 'Circle Officer (CO)',
    optionD: 'Divisional Commissioner',
    correctAnswer: 'A',
    explanation: 'Section 46 strictly restricts alienation of tribal land; transfer between ST persons within the same police station limits is permissible only with written permission from the Deputy Commissioner.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'Under the CNT Act, 1908, which Section deals with the restoration of unlawfully alienated land to the original raiyat by the Deputy Commissioner?',
    optionA: 'Section 46',
    optionB: 'Section 71A',
    optionC: 'Section 85',
    optionD: 'Section 242',
    correctAnswer: 'B',
    explanation: 'Section 71A empowers the Deputy Commissioner to evict unlawful occupants and restore possession of transferred tribal land to the rightful Scheduled Tribe raiyat.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'Under Section 21 of the CNT Act, a raiyat has the right to utilize their agricultural land for:',
    optionA: 'Constructing dwelling houses and agricultural wells',
    optionB: 'Manufacturing bricks for personal household use',
    optionC: 'Planting trees and enjoying timber fruits',
    optionD: 'All of the above',
    correctAnswer: 'D',
    explanation: 'Section 21 confers wide usufruct rights on the raiyat, including domestic construction, well-digging, brick-making for domestic use, and planting trees.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'What is a "Bhuinhari" land tenure as recognized under Chapter VIII of the CNT Act, 1908?',
    optionA: 'Ancestral land cleared and held by original Oraon settlers',
    optionB: 'Land held exclusively by the British crown',
    optionC: 'Land auctioned for unpaid rent',
    optionD: 'Land owned by money-lenders',
    correctAnswer: 'A',
    explanation: 'Bhuinhari tenure belongs to the original Oraon settlers who reclaimed virgin forest lands for agriculture, recognized under the Chota Nagpur Tenures Act 1869 and CNT 1908.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'spt-act-1949',
    questionText: 'In which year was the Santhal Parganas Tenancy (Supplementary Provisions) Act enacted?',
    optionA: '1947',
    optionB: '1949',
    optionC: '1952',
    optionD: '1956',
    correctAnswer: 'B',
    explanation: 'The Santhal Parganas Tenancy (Supplementary Provisions) Act was enacted in 1949 to safeguard land and raiyat rights in the Santhal Pargana division.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'spt-act-1949',
    questionText: 'How many Chapters and Sections are contained in the Santhal Parganas Tenancy Act, 1949?',
    optionA: '8 Chapters and 72 Sections',
    optionB: '10 Chapters and 100 Sections',
    optionC: '12 Chapters and 150 Sections',
    optionD: '6 Chapters and 60 Sections',
    correctAnswer: 'A',
    explanation: 'The SPT Act, 1949 contains 8 Chapters and 72 Sections (along with two schedules).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'spt-act-1949',
    questionText: 'Which Section of the SPT Act, 1949 strictly prohibits any transfer of a raiyat’s land by sale, gift, mortgage, or lease unless permitted by recorded custom?',
    optionA: 'Section 13',
    optionB: 'Section 20',
    optionC: 'Section 27',
    optionD: 'Section 33',
    correctAnswer: 'B',
    explanation: 'Section 20 of the SPT Act lays down a comprehensive ban on the alienation of raiyati holdings by way of sale, gift, mortgage, lease, or any agreement.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'spt-act-1949',
    questionText: 'Under Section 33 of the SPT Act, 1949, if a settlement of wasteland is not brought under cultivation within how many years, it may be cancelled?',
    optionA: '3 years',
    optionB: '5 years',
    optionC: '7 years',
    optionD: '10 years',
    correctAnswer: 'B',
    explanation: 'Under Section 33 of the SPT Act, if wasteland settled for reclamation is not cultivated within 5 years from the date of settlement, the settlement is liable to cancellation.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'Who prepares the Record-of-Rights (Khatiyan) under Chapter XII of the CNT Act, 1908?',
    optionA: 'Revenue Officer',
    optionB: 'Gram Pradhan',
    optionC: 'Mukhia',
    optionD: 'High Court Judge',
    correctAnswer: 'A',
    explanation: 'Under Chapter XII of the CNT Act, the State Government directs the Revenue Officer to conduct surveys and prepare the Record-of-Rights.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'spt-act-1949',
    questionText: 'Which official is empowered to appoint the village headman (Pradhan) under Section 5 of the SPT Act, 1949?',
    optionA: 'Deputy Commissioner',
    optionB: 'Sub-Divisional Officer',
    optionC: 'Block Development Officer',
    optionD: 'Panchayat Secretary',
    correctAnswer: 'A',
    explanation: 'Under Section 5 of the SPT Act, the Deputy Commissioner appoints the village headman with the consent of at least two-thirds of the village raiyats.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'cnt-act-1908',
    questionText: 'Under the CNT Act, an occupancy raiyat who holds land continuously for how many years acquires the right of occupancy?',
    optionA: '5 years',
    optionB: '10 years',
    optionC: '12 years',
    optionD: '15 years',
    correctAnswer: 'C',
    explanation: 'Under Section 17 and 19 of the CNT Act, a settled raiyat who has continuously held land for 12 years in a village acquires occupancy rights in all agricultural land held by them.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-land-laws',
    topicSlug: 'spt-act-1949',
    questionText: 'Under Section 14 of the SPT Act, 1949, a raiyat can be evicted from their holding only on which authority’s order?',
    optionA: 'Landlord notice',
    optionB: 'Deputy Commissioner order in execution of a decree',
    optionC: 'Gram Panchayat resolution',
    optionD: 'Police inspector directive',
    correctAnswer: 'B',
    explanation: 'Section 14 specifies that no raiyat shall be ejected except in execution of an order passed by the Deputy Commissioner for reasons permitted under the Act.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },

  // 4. Jharkhand Geography & Rivers (12 Qs)
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'physical-geography-plateaus',
    questionText: 'What is the highest mountain peak of Jharkhand State, located in the Giridih district?',
    optionA: 'Parasnath (Sammed Shikhar)',
    optionB: 'Netarhat Peak',
    optionC: 'Saranda Peak',
    optionD: 'Gulgalpat Peak',
    correctAnswer: 'A',
    explanation: 'Parasnath Peak (Sammed Shikhar) is the highest elevation in Jharkhand at 1,365 metres (4,478 feet) above sea level, situated in Giridih district.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'physical-geography-plateaus',
    questionText: 'The stepped flat-topped tablelands in western Jharkhand (Latehar, Lohardaga, Gumla) are locally known as:',
    optionA: 'Pat regions',
    optionB: 'Bhur land',
    optionC: 'Duns',
    optionD: 'Kandi tracts',
    correctAnswer: 'A',
    explanation: 'The Pat region (e.g. Netarhat Pat, Jamira Pat) consists of high plateau mesa/butte formations capped with thick bauxite deposits.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'Which is the longest and largest river flowing through Jharkhand, originating from the Tori region in Latehar district?',
    optionA: 'Swarnarekha River',
    optionB: 'Damodar River',
    optionC: 'Mayurakshi River',
    optionD: 'North Koel River',
    correctAnswer: 'B',
    explanation: 'The Damodar River originates from Tori (Chulhapani) in Latehar and flows eastward for approximately 290 km within Jharkhand before entering West Bengal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'Which unique river in Jharkhand falls directly into the Bay of Bengal without merging into any other tributary or river system?',
    optionA: 'Damodar River',
    optionB: 'Barakar River',
    optionC: 'Swarnarekha River',
    optionD: 'Ajay River',
    correctAnswer: 'C',
    explanation: 'The Swarnarekha River originates at Nagri near Ranchi and flows independently into the Bay of Bengal near Kirtania port in Odisha.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'The spectacular Hundru Falls, dropping from a height of 98 metres (320 feet), is formed by which river in Ranchi district?',
    optionA: 'Swarnarekha River',
    optionB: 'Rarhhu River',
    optionC: 'Kanchi River',
    optionD: 'Sankh River',
    correctAnswer: 'A',
    explanation: 'Hundru Falls is created when the Swarnarekha river drops across the Ranchi plateau escarpment, 45 km northeast of Ranchi.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'Lodh Falls (Burha Ghagh Falls), the highest waterfall in Jharkhand with a fall height of 143 metres, is situated in which district?',
    optionA: 'Latehar',
    optionB: 'Ranchi',
    optionC: 'Simdega',
    optionD: 'Khunti',
    correctAnswer: 'A',
    explanation: 'Lodh Falls (Burha Ghagh) is on the Burha River inside the Mahuadanr valley of Latehar district.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'physical-geography-plateaus',
    questionText: 'The Chotanagpur Plateau primarily belongs to which ancient geological shield landmass?',
    optionA: 'Gondwanaland',
    optionB: 'Laurasia',
    optionC: 'Tethys Geosyncline',
    optionD: 'Angaraland',
    correctAnswer: 'A',
    explanation: 'The Chotanagpur Plateau is an ancient Precambrian cratonic block composed of Archean granites and gneisses, which was part of Gondwanaland.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'The Masanjor Dam (Canada Dam) is constructed across which river in Dumka district of Jharkhand?',
    optionA: 'Brahmani River',
    optionB: 'Mayurakshi River',
    optionC: 'Koel River',
    optionD: 'Damodar River',
    correctAnswer: 'B',
    explanation: 'Masanjor Dam was built in 1955 with Canadian foreign assistance across the Mayurakshi River in Dumka district.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'physical-geography-plateaus',
    questionText: 'What is the dominant soil type found across more than 90% of Jharkhand’s geographical area?',
    optionA: 'Black Soil',
    optionB: 'Red Soil',
    optionC: 'Laterite Soil',
    optionD: 'Alluvial Soil',
    correctAnswer: 'B',
    explanation: 'Red soil, formed by the prolonged weathering of ancient Archean crystalline granite-gneiss rocks, covers almost 90% of Jharkhand.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'Jonha Falls (Gautam Dhara) in Ranchi district is formed along which tributary river?',
    optionA: 'Rarhhu River',
    optionB: 'Kanchi River',
    optionC: 'Swarnarekha River',
    optionD: 'North Koel River',
    correctAnswer: 'A',
    explanation: 'Jonha Falls is located along the Rarhhu River, where a temple dedicated to Lord Buddha also stands.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'physical-geography-plateaus',
    questionText: 'Which district of Jharkhand receives the highest annual rainfall (exceeding 180 cm) in the state?',
    optionA: 'Netarhat (Latehar)',
    optionB: 'Chaibasa (West Singhbhum)',
    optionC: 'Palamu',
    optionD: 'Garhwa',
    correctAnswer: 'A',
    explanation: 'Netarhat region in Latehar receives the highest annual rainfall (180 cm+), whereas the Chaibasa plain receives the lowest.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-geography-rivers',
    topicSlug: 'drainage-rivers',
    questionText: 'The Damodar Valley Corporation (DVC), India’s first multipurpose river valley project, was established in which year?',
    optionA: '1948',
    optionB: '1950',
    optionC: '1952',
    optionD: '1956',
    correctAnswer: 'A',
    explanation: 'DVC was established on July 7, 1948 by an Act of the Constituent Assembly, modeled after the Tennessee Valley Authority (TVA) of the United States.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },

  // 5. Mines, Minerals & Industrial Development (13 Qs)
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'The famous Jaduguda mine in East Singhbhum district is renowned as India’s first operational mine for:',
    optionA: 'Uranium',
    optionB: 'Thorium',
    optionC: 'Chromite',
    optionD: 'Platinum',
    correctAnswer: 'A',
    explanation: 'Jaduguda in East Singhbhum is India’s foremost uranium mine operated by the Uranium Corporation of India Limited (UCIL) since 1967.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'Which district in Jharkhand is known as the "Mica Capital of India" for its world-class ruby mica deposits?',
    optionA: 'Koderma',
    optionB: 'Dhanbad',
    optionC: 'Bokaro',
    optionD: 'Pakur',
    correctAnswer: 'A',
    explanation: 'Koderma and neighbouring Giridih produce superior-quality pegmatite muscovite mica, earning Koderma the epithet of Mica Capital.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'Jharkhand ranks first in India in terms of total reserves of which essential industrial fuel mineral?',
    optionA: 'Prime Coking Coal',
    optionB: 'Natural Gas',
    optionC: 'Petroleum',
    optionD: 'Lignite',
    correctAnswer: 'A',
    explanation: 'Jharkhand holds virtually 100% of India’s prime coking coal reserves, primarily in the Jharia coalfield of Dhanbad district.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'The Chiria iron ore mine located in West Singhbhum district has approximately how many tonnes of iron ore reserves, making it one of Asia’s largest single deposits?',
    optionA: '2 billion tonnes',
    optionB: '500 million tonnes',
    optionC: '100 million tonnes',
    optionD: '5 billion tonnes',
    correctAnswer: 'A',
    explanation: 'Chiria iron ore reserves held by SAIL in West Singhbhum contain nearly 2 billion tonnes of high-grade hematite iron ore.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'industrial-policies-plants',
    questionText: 'The Tata Iron and Steel Company (TISCO, now Tata Steel) was established at Sakchi (Jamshedpur) in which year by Jamsetji Tata and Dorabji Tata?',
    optionA: '1907',
    optionB: '1911',
    optionC: '1915',
    optionD: '1920',
    correctAnswer: 'A',
    explanation: 'TISCO was founded on August 26, 1907 at Sakchi village; pig iron production started in 1911 and steel ingots in 1912.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'industrial-policies-plants',
    questionText: 'Bokaro Steel Plant (BSL), India’s fourth public sector integrated steel plant, was established in 1964 with the collaboration of which foreign nation?',
    optionA: 'Soviet Union (USSR)',
    optionB: 'United Kingdom',
    optionC: 'West Germany',
    optionD: 'United States',
    correctAnswer: 'A',
    explanation: 'Bokaro Steel Plant was incorporated in 1964 with technical and financial collaboration from the USSR (Soviet Union).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'industrial-policies-plants',
    questionText: 'Heavy Engineering Corporation (HEC) situated at Hatia, Ranchi, often referred to as the "Mother of Industries", was set up with assistance from:',
    optionA: 'USSR and Czechoslovakia',
    optionB: 'USA and UK',
    optionC: 'Germany and France',
    optionD: 'Japan and Sweden',
    correctAnswer: 'A',
    explanation: 'HEC Ranchi was established in 1958 with technical collaboration from the USSR and Czechoslovakia to manufacture heavy industrial equipment.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'Bauxite mining in Jharkhand is heavily concentrated on the high lateritic plateaus of which two districts?',
    optionA: 'Lohardaga and Gumla',
    optionB: 'Dhanbad and Bokaro',
    optionC: 'Deoghar and Dumka',
    optionD: 'Godda and Sahibganj',
    correctAnswer: 'A',
    explanation: 'Lohardaga, Gumla, and Latehar constitute the core bauxite mining belt of Jharkhand, supplying the Hindalco aluminum refinery at Muri.',
    difficulty: 'Easy',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'industrial-policies-plants',
    questionText: 'The Indian Copper Corporation established the first copper smelting plant in India in 1928 at which location in Jharkhand?',
    optionA: 'Ghatshila (Moubhandar)',
    optionB: 'Chas',
    optionC: 'Kandra',
    optionD: 'Sindri',
    correctAnswer: 'A',
    explanation: 'Ghatshila (Moubhandar) in East Singhbhum hosted India’s first copper smelter established by the Indian Copper Corporation in 1928.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'industrial-policies-plants',
    questionText: 'India’s first modern chemical fertilizer factory was established by the Government of India in 1951 at which place in Jharkhand?',
    optionA: 'Sindri (Dhanbad)',
    optionB: 'Gomoh',
    optionC: 'Chirkunda',
    optionD: 'Chandrapura',
    correctAnswer: 'A',
    explanation: 'The Sindri fertilizer plant in Dhanbad district was set up in 1951 by the Fertilizer Corporation of India (FCI).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'The Mosabani, Rakha, and Kendadih mines in Jharkhand are prominent producers of which metal ore?',
    optionA: 'Copper ore',
    optionB: 'Lead ore',
    optionC: 'Tungsten',
    optionD: 'Gold ore',
    correctAnswer: 'A',
    explanation: 'Mosabani, Rakha, Kendadih, and Surda in the Singhbhum Shear Zone are the premier copper-producing mines of Jharkhand.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'industrial-policies-plants',
    questionText: 'Which industrial growth agency was created by the Jharkhand government to develop industrial infrastructure around Ranchi and surrounding districts?',
    optionA: 'RIADA (Ranchi Industrial Area Development Authority)',
    optionB: 'BIADA',
    optionC: 'AIADA',
    optionD: 'JIADA (Jharkhand Industrial Area Development Authority)',
    correctAnswer: 'D',
    explanation: 'JIADA was formed by unifying regional authorities (RIADA, AIADA, BIADA, SPIADA) into a single state-wide apex industrial authority.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-minerals-industries',
    topicSlug: 'mineral-resources-mining',
    questionText: 'The famous Jharia coalfield accounts for the largest supply of coking coal in India. It is operated primarily by which subsidiary of Coal India?',
    optionA: 'Bharat Coking Coal Limited (BCCL)',
    optionB: 'Central Coalfields Limited (CCL)',
    optionC: 'Eastern Coalfields Limited (ECL)',
    optionD: 'South Eastern Coalfields Limited (SECL)',
    correctAnswer: 'A',
    explanation: 'BCCL (Bharat Coking Coal Limited) operates the Jharia coalfield, producing prime coking coal for Indian steel plants.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },

  // 6. Government Welfare Schemes & Policies (12 Qs)
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Mukhyamantri Maiya Samman Yojana" launched by Jharkhand in 2024, eligible women receive direct financial assistance of:',
    optionA: '₹1,000 per month (later enhanced to ₹2,500)',
    optionB: '₹500 per month',
    optionC: '₹3,000 per year',
    optionD: '₹5,000 one time',
    correctAnswer: 'A',
    explanation: 'The Jharkhand government launched Mukhyamantri Maiya Samman Yojana in August 2024 providing ₹1,000 per month, which was subsequently raised to ₹2,500 per month for women aged 18 to 50.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Marang Gomke Jaipal Singh Munda Overseas Scholarship Scheme", how many tribal/marginalized students are sponsored annually for overseas postgraduate studies in the UK/Ireland?',
    optionA: 'Up to 25 students',
    optionB: '5 students',
    optionC: '50 students',
    optionD: '100 students',
    correctAnswer: 'A',
    explanation: 'Initially started for 10 ST students, the scheme was expanded to sponsor up to 25 students from SC, ST, Minorities, and OBC categories to pursue Master/M.Phil degrees in top UK and Irish universities.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2024,
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Savitribai Phule Kishori Samriddhi Yojana", how much cumulative financial grant is granted to girl students from Class 8 to age 18–19?',
    optionA: '₹40,000',
    optionB: '₹25,000',
    optionC: '₹15,000',
    optionD: '₹50,000',
    correctAnswer: 'A',
    explanation: 'The scheme provides phased installments from Class 8 to 12 and a final grant upon attaining age 18–19, totaling ₹40,000 to incentivize girls’ education and curb child marriage.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Abua Awas Yojana" launched by Jharkhand in 2023, poor families without pucca houses are provided a 3-room house with financial assistance of:',
    optionA: '₹2.00 Lakh',
    optionB: '₹1.20 Lakh',
    optionC: '₹3.50 Lakh',
    optionD: '₹1.50 Lakh',
    correctAnswer: 'A',
    explanation: 'The Abua Awas Yojana provides ₹2,00,000 in four installments for constructing a 3-room pucca house with a dedicated kitchen.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Guru-ji Student Credit Card Scheme" in Jharkhand, students can avail educational loans for higher studies up to what amount at a concessional 4% simple interest rate?',
    optionA: 'Up to ₹15 Lakh',
    optionB: 'Up to ₹10 Lakh',
    optionC: 'Up to ₹5 Lakh',
    optionD: 'Up to ₹25 Lakh',
    correctAnswer: 'A',
    explanation: 'The Guru-ji Student Credit Card scheme provides collateral-free education loans up to ₹15 Lakh at just 4% simple interest.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'What is the primary objective of the "Poto Ho Khel Vikas Yojana" initiated by the Jharkhand state government?',
    optionA: 'Constructing rural sports grounds in every panchayat to promote indigenous tribal talent',
    optionB: 'Providing sports bicycles to students',
    optionC: 'Organizing interstate cricket matches',
    optionD: 'Building Olympic stadia in metro cities',
    correctAnswer: 'A',
    explanation: 'Named in honor of martyr Poto Ho, the scheme utilizes MGNREGA to build rural playfields and sports parks across village panchayats.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Birsa Harit Gram Yojana", rural households in Jharkhand are supported to cultivate:',
    optionA: 'Fruit-bearing fruit orchards on fallow and unutilized lands',
    optionB: 'Sugarcane plantations',
    optionC: 'Rubber trees',
    optionD: 'Coffee estates',
    correctAnswer: 'A',
    explanation: 'The Birsa Harit Gram Yojana promotes mango and guava horticulture plantations on unused village land to ensure regular livelihood income for rural poor.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Sona Sobran Dhoti-Sari Scheme" in Jharkhand, poor ration-card holding families receive a dhoti/lungi and a saree for how much subsidized token price?',
    optionA: '₹10 per piece (twice a year)',
    optionB: '₹50 per piece',
    optionC: '₹100 per piece',
    optionD: 'Free of cost',
    correctAnswer: 'A',
    explanation: 'Under the Sona Sobran scheme, beneficiaries of the National Food Security Act receive a dhoti/lungi and a saree for just ₹10 each twice a year.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the "Mukhyamantri Krishi Ashirwad Yojana" (subsequently aligned with PM-KISAN), farmers with up to 5 acres received assistance of:',
    optionA: '₹5,000 per acre (up to ₹25,000)',
    optionB: '₹1,000 per acre',
    optionC: '₹10,000 flat',
    optionD: '₹50,000 flat',
    correctAnswer: 'A',
    explanation: 'Mukhyamantri Krishi Ashirwad Yojana provided input assistance of ₹5,000 per acre up to a maximum of ₹25,000 for 5 acres.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'The "Chief Minister Free Coaching Scheme" (Akanksha Scheme) in Jharkhand prepares meritorious government school students for:',
    optionA: 'Engineering (JEE), Medical (NEET), and CLAT entrance exams',
    optionB: 'Driving licenses',
    optionC: 'Typing tests',
    optionD: 'Foreign language certificates',
    correctAnswer: 'A',
    explanation: 'The Akanksha program offers fully state-funded residential coaching for underprivileged students preparing for national competitive exams like JEE and NEET.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'Under the universal pension scheme of Jharkhand (Sarvajan Pension Yojana), which demographic barrier was abolished?',
    optionA: 'BPL ration card requirement (pension made available to all elderly/destitute individuals)',
    optionB: 'Age requirement completely',
    optionC: 'Residency requirement',
    optionD: 'Gender requirement',
    correctAnswer: 'A',
    explanation: 'Jharkhand made pension universal by removing the mandatory BPL list condition, ensuring every person aged 60+ (and widows/disabled) receives monthly pension.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-schemes-development',
    topicSlug: 'welfare-schemes-jharkhand',
    questionText: 'The "Nilamber-Pitamber Jal Samriddhi Yojana" focuses primarily on which critical sector in drought-prone western Jharkhand (Palamu, Garhwa)?',
    optionA: 'Rainwater harvesting and groundwater recharge through trenches and bunds',
    optionB: 'Solar power plant installations',
    optionC: 'Canal construction from Ganga',
    optionD: 'Urban sewage management',
    correctAnswer: 'A',
    explanation: 'The scheme utilizes watershed management (field trenches, soak pits, and check dams) to conserve water in arid districts like Palamu and Garhwa.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },

  // 7. Forest, Wildlife & Environmental Management (12 Qs)
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'According to the India State of Forest Report (ISFR) 2021, what percentage of Jharkhand’s total geographical area is covered under forest cover?',
    optionA: '29.76%',
    optionB: '33.33%',
    optionC: '24.16%',
    optionD: '21.50%',
    correctAnswer: 'A',
    explanation: 'As per ISFR 2021, Jharkhand has a forest cover of 23,721.14 sq km, which constitutes 29.76% of the state’s total geographical area.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2024,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'Which is the only National Park located in Jharkhand, established in 1986 in Latehar district?',
    optionA: 'Betla National Park',
    optionB: 'Dalma National Park',
    optionC: 'Hazaribagh National Park',
    optionD: 'Palkot National Park',
    correctAnswer: 'A',
    explanation: 'Betla National Park (in Latehar/Palamu) is the sole National Park of Jharkhand, notified in 1986. It is celebrated for the world’s first tiger census conducted in 1932.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'In which year and wildlife sanctuary of Jharkhand was the world’s first tiger census based on pugmark method conducted?',
    optionA: '1932 in Palamu (Betla)',
    optionB: '1947 in Dalma',
    optionC: '1972 in Saranda',
    optionD: '1952 in Hazaribagh',
    correctAnswer: 'A',
    explanation: 'The world’s first tiger census was conducted in 1932 in the forests of Palamu by J.W. Nicholson, using the pugmark identification methodology.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'The Dalma Wildlife Sanctuary near Jamshedpur is world-famous as a dedicated sanctuary for which animal species?',
    optionA: 'Asian Elephant',
    optionB: 'Bengal Tiger',
    optionC: 'One-horned Rhinoceros',
    optionD: 'Snow Leopard',
    correctAnswer: 'A',
    explanation: 'Inaugurated by Sanjay Gandhi in 1975, the Dalma Wildlife Sanctuary is renowned for its substantial wild Asian elephant population.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'The dense Sal forest of "Saranda", famously known as the "Land of Seven Hundred Hills", is situated in which district?',
    optionA: 'West Singhbhum',
    optionB: 'Gumla',
    optionC: 'Latehar',
    optionD: 'Simdega',
    correctAnswer: 'A',
    explanation: 'Saranda Forest in West Singhbhum is Asia’s largest contiguous Sal (Shorea robusta) forest, covering over 820 sq km.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'Which district in Jharkhand records the highest percentage of forest cover relative to its total area (approx 56%) according to ISFR 2021?',
    optionA: 'Latehar',
    optionB: 'West Singhbhum',
    optionC: 'Chatra',
    optionD: 'Jamtara',
    correctAnswer: 'A',
    explanation: 'Latehar boasts the highest percentage of forest cover (56.08%), whereas West Singhbhum has the largest absolute forest area in sq km.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2024,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'Which district of Jharkhand has the lowest forest cover in terms of both area and percentage (around 5.85%)?',
    optionA: 'Jamtara',
    optionB: 'Deoghar',
    optionC: 'Dhanbad',
    optionD: 'Bokaro',
    correctAnswer: 'A',
    explanation: 'Jamtara has the lowest percentage of forest cover in Jharkhand at roughly 5.85% (only ~106 sq km).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'Mahuadanr Wolf Sanctuary, the only wildlife sanctuary in India dedicated specifically to the conservation of the Indian Wolf, is in which district?',
    optionA: 'Latehar',
    optionB: 'Palamu',
    optionC: 'Garhwa',
    optionD: 'Gumla',
    correctAnswer: 'A',
    explanation: 'Mahuadanr Wolf Sanctuary in Latehar was established in 1976 for protecting endangered Indian wolves.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'environmental-issues-disaster',
    questionText: 'The State Disaster Management Authority (SDMA) of Jharkhand was constituted in which year under the Disaster Management Act, 2005?',
    optionA: '2010',
    optionB: '2005',
    optionC: '2015',
    optionD: '2008',
    correctAnswer: 'A',
    explanation: 'The Jharkhand State Disaster Management Authority (JSDMA) was formally notified on May 28, 2010 under the chairmanship of the Chief Minister.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'Udhwa Lake Bird Sanctuary, a haven for migratory water birds from Siberia and Central Asia, is situated in which district of Jharkhand?',
    optionA: 'Sahibganj',
    optionB: 'Pakur',
    optionC: 'Godda',
    optionD: 'Dumka',
    correctAnswer: 'A',
    explanation: 'Udhwa Lake Bird Sanctuary is located in Sahibganj along the Ganga river basin, covering Pataura and Berhale lakes.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'forest-wildlife-sanctuaries',
    questionText: 'What is the state tree of Jharkhand, revered by tribals during the Sarhul festival?',
    optionA: 'Sal (Shorea robusta)',
    optionB: 'Palash (Butea monosperma)',
    optionC: 'Mahua (Madhuca longifolia)',
    optionD: 'Peepal (Ficus religiosa)',
    correctAnswer: 'A',
    explanation: 'The Sal tree is the official state tree of Jharkhand, and its blooming flowers (Sal flowers/Sakhua) mark the auspicious Sarhul festival.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-forest-environment',
    topicSlug: 'environmental-issues-disaster',
    questionText: 'Which premier academic institution in Ranchi serves as the state nodal centre for disaster management training and research in Jharkhand?',
    optionA: 'Shri Krishna Institute of Public Administration (SKIPA)',
    optionB: 'Birsa Agricultural University',
    optionC: 'IIM Ranchi',
    optionD: 'BIT Mesra',
    correctAnswer: 'A',
    explanation: 'SKIPA (Shri Krishna Institute of Public Administration) in Ranchi operates the Centre for Disaster Management providing administrative and crisis response training.',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
  },

  // 8. Culture, Sports & Miscellaneous Jharkhand GK (12 Qs)
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'folk-literature-dance-festivals',
    questionText: 'Sarhul, the most celebrated tribal spring festival of Jharkhand, worships which natural element and deity?',
    optionA: 'Nature and the Sal tree (representing Mother Earth / Gaon Khunt)',
    optionB: 'Sun God exclusively',
    optionC: 'Ganga river',
    optionD: 'Cattle and livestock',
    correctAnswer: 'A',
    explanation: 'Sarhul is the great festival of nature worship celebrated in Chaitra month when Sal trees bloom. The Pahan offers prayers to Singbonga and village deities under the Sarna grove.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'folk-literature-dance-festivals',
    questionText: 'Chhau Dance of Seraikela (Jharkhand) was inscribed in UNESCO’s Representative List of the Intangible Cultural Heritage of Humanity in which year?',
    optionA: '2010',
    optionB: '2005',
    optionC: '2015',
    optionD: '2020',
    correctAnswer: 'A',
    explanation: 'Seraikela Chhau dance, famed for its stylized masked performances and martial origins, was recognized by UNESCO in 2010.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'folk-literature-dance-festivals',
    questionText: 'Who invented the "Ol Chiki" script for the Santhali language in 1925?',
    optionA: 'Pandit Raghunath Murmu',
    optionB: 'Jaipal Singh Munda',
    optionC: 'Ram Dayal Munda',
    optionD: 'Lako Bodra',
    correctAnswer: 'A',
    explanation: 'Pandit Raghunath Murmu invented the Ol Chiki script in 1925 to give the Santhali language its own distinct writing system.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'folk-literature-dance-festivals',
    questionText: 'The "Warang Chiti" script was created by Lako Bodra for writing which indigenous tribal language of Jharkhand?',
    optionA: 'Ho language',
    optionB: 'Kurukh language',
    optionC: 'Mundari language',
    optionD: 'Kharia language',
    correctAnswer: 'A',
    explanation: 'Lako Bodra devised the Warang Chiti script in the 1940s specifically for the Ho language of the Kolhan region.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'folk-literature-dance-festivals',
    questionText: 'Sohrai and Khovar mural paintings, awarded the Geographical Indication (GI) tag in 2020, are traditionally practiced primarily in which district?',
    optionA: 'Hazaribagh',
    optionB: 'Deoghar',
    optionC: 'Simdega',
    optionD: 'Godda',
    correctAnswer: 'A',
    explanation: 'Sohrai and Khovar wall mural art practiced by indigenous women using natural earth pigments in Hazaribagh district was granted the GI tag in May 2020.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'famous-personalities-awards',
    questionText: 'Eminent scholar, folklorist, and former Vice-Chancellor of Ranchi University who was awarded the Padma Shri in 2010 for his contributions to tribal art and music was:',
    optionA: 'Dr. Ram Dayal Munda',
    optionB: 'Father Camille Bulcke',
    optionC: 'Bhubneshwar Anuj',
    optionD: 'B.P. Keshri',
    correctAnswer: 'A',
    explanation: 'Dr. Ram Dayal Munda was an internationally recognized tribal intellectual, author, folk musician, and Rajya Sabha MP honoured with the Padma Shri in 2010.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'sports-stadiums',
    questionText: 'The JSCA International Stadium Complex, a premier venue hosting international cricket matches, is located in which city of Jharkhand?',
    optionA: 'Ranchi',
    optionB: 'Jamshedpur',
    optionC: 'Dhanbad',
    optionD: 'Bokaro',
    correctAnswer: 'A',
    explanation: 'The JSCA (Jharkhand State Cricket Association) International Stadium is located in Dhurwa, Ranchi, inaugurated in January 2013.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'sports-stadiums',
    questionText: 'Which legendary Indian hockey player from Simdega district captained the Indian women’s hockey team and won gold at the 2002 Commonwealth Games in Manchester?',
    optionA: 'Asunta Lakra',
    optionB: 'Savitri Purti',
    optionC: 'Salima Tete',
    optionD: 'Nikki Pradhan',
    correctAnswer: 'A',
    explanation: 'Simdega is celebrated as the "Cradle of Hockey" in Jharkhand, producing international hockey stalwarts such as Asunta Lakra, Savitri Purti, and Salima Tete.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'sports-stadiums',
    questionText: 'Deepika Kumari, an Arjuna Awardee and Padma Shri recipient from Jharkhand, has earned international acclaim in which sporting discipline?',
    optionA: 'Archery',
    optionB: 'Shooting',
    optionC: 'Wrestling',
    optionD: 'Weightlifting',
    correctAnswer: 'A',
    explanation: 'Deepika Kumari from Ranchi is a world number-one recurve archer who won double gold at the 2010 Commonwealth Games and numerous World Cup titles.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'famous-personalities-awards',
    questionText: 'Father Camille Bulcke, a renowned Belgian Jesuit priest who settled in Ranchi and became one of India’s foremost Hindi-English scholars and Ramkatha authorities, was awarded:',
    optionA: 'Padma Bhushan in 1974',
    optionB: 'Bharat Ratna',
    optionC: 'Jnanpith Award',
    optionD: 'Sahitya Akademi Fellowship',
    correctAnswer: 'A',
    explanation: 'Father Camille Bulcke authored the seminal thesis "Ramkatha: Utpatti Aur Vikas" and an English-Hindi dictionary, receiving the Padma Bhushan in 1974.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'folk-literature-dance-festivals',
    questionText: 'The festival of "Karma" in Jharkhand is primarily celebrated to honour:',
    optionA: 'Brother-sister affection, fertility, and prosperity through the Karam tree branch',
    optionB: 'Hunting prowess',
    optionC: 'Rain invocation exclusively',
    optionD: 'Harvest conclusion in spring',
    correctAnswer: 'A',
    explanation: 'Karma is an agrarian festival celebrated on Bhadra Shukla Ekadashi where youth plant branches of the Karam (Nauclea parvifolia) tree and sisters pray for brothers’ prosperity.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2016,
  },
  {
    subjectSlug: 'jpsc-p2-culture-sports',
    topicSlug: 'sports-stadiums',
    questionText: 'The 34th National Games of India were hosted by Jharkhand in which year across Ranchi, Jamshedpur, and Dhanbad?',
    optionA: '2011',
    optionB: '2007',
    optionC: '2015',
    optionD: '2018',
    correctAnswer: 'A',
    explanation: 'The 34th National Games were hosted in February 2011 with the main athletic events at Mega Sports Complex, Hotwar, Ranchi; its mascot was "Chhauva" (a deer fawn).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    sourceYear: 2021,
  },
];
