export interface QuestionData {
  questionText: string;
  optionA: string;
  optionB: string;
  optionC: string;
  optionD: string;
  correctAnswer: 'A' | 'B' | 'C' | 'D';
  explanation: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
}

// Authentic SSC CGL Questions across subjects

export const PROFIT_LOSS_QUESTIONS: QuestionData[] = [
  // Easy
  {
    questionText: 'A trader buys an article for ₹500 and sells it for ₹600. What is his profit percentage?',
    optionA: '20%',
    optionB: '25%',
    optionC: '15%',
    optionD: '10%',
    correctAnswer: 'A',
    explanation: 'Profit = ₹600 - ₹500 = ₹100. Profit % = (100 / 500) * 100 = 20%.',
    difficulty: 'Easy',
  },
  {
    questionText: 'An article bought for ₹800 is sold at a loss of 10%. What is the selling price?',
    optionA: '₹720',
    optionB: '₹700',
    optionC: '₹740',
    optionD: '₹750',
    correctAnswer: 'A',
    explanation: 'Loss = 10% of 800 = ₹80. Selling Price = 800 - 80 = ₹720.',
    difficulty: 'Easy',
  },
  {
    questionText: 'If the Cost Price is ₹250 and Selling Price is ₹200, find the loss percentage.',
    optionA: '20%',
    optionB: '25%',
    optionC: '15%',
    optionD: '30%',
    correctAnswer: 'A',
    explanation: 'Loss = ₹50. Loss % = (50 / 250) * 100 = 20%.',
    difficulty: 'Easy',
  },
  {
    questionText: 'The marked price of a watch is ₹1,000. A shopkeeper offers a 10% discount. What is the selling price?',
    optionA: '₹900',
    optionB: '₹950',
    optionC: '₹850',
    optionD: '₹920',
    correctAnswer: 'A',
    explanation: 'Discount = 10% of 1000 = ₹100. Selling Price = 1000 - 100 = ₹900.',
    difficulty: 'Easy',
  },
  {
    questionText: 'If 15 articles are bought for ₹120, what is the cost of 5 articles?',
    optionA: '₹40',
    optionB: '₹50',
    optionC: '₹35',
    optionD: '₹45',
    correctAnswer: 'A',
    explanation: 'Cost of 1 article = 120 / 15 = ₹8. Cost of 5 articles = 5 * 8 = ₹40.',
    difficulty: 'Easy',
  },
  {
    questionText: 'A cycle is purchased for ₹1,200 and sold for ₹1,500. Calculate the gain.',
    optionA: '₹300',
    optionB: '₹250',
    optionC: '₹350',
    optionD: '₹200',
    correctAnswer: 'A',
    explanation: 'Gain = SP - CP = 1500 - 1200 = ₹300.',
    difficulty: 'Easy',
  },
  {
    questionText: 'On selling an item for ₹660, a shopkeeper gains 10%. What was the cost price?',
    optionA: '₹600',
    optionB: '₹580',
    optionC: '₹620',
    optionD: '₹590',
    correctAnswer: 'A',
    explanation: 'CP = SP / (1 + Profit%) = 660 / 1.10 = ₹600.',
    difficulty: 'Easy',
  },
  {
    questionText: 'If the selling price is double the cost price, the profit percentage is:',
    optionA: '100%',
    optionB: '50%',
    optionC: '200%',
    optionD: '150%',
    correctAnswer: 'A',
    explanation: 'Let CP = 100, then SP = 200. Profit = 100. Profit % = (100/100)*100 = 100%.',
    difficulty: 'Easy',
  },
  {
    questionText: 'A merchant sells 20 pens for ₹200 at no profit no loss. What is the CP of 1 pen?',
    optionA: '₹10',
    optionB: '₹12',
    optionC: '₹8',
    optionD: '₹15',
    correctAnswer: 'A',
    explanation: 'Total CP = Total SP = 200. CP per pen = 200 / 20 = ₹10.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Find the single discount equivalent to successive discounts of 10% and 10%.',
    optionA: '19%',
    optionB: '20%',
    optionC: '18%',
    optionD: '21%',
    correctAnswer: 'A',
    explanation: 'Equivalent discount = d1 + d2 - (d1 * d2)/100 = 10 + 10 - 1 = 19%.',
    difficulty: 'Easy',
  },

  // Medium
  {
    questionText: 'A dishonest dealer professes to sell his goods at cost price but uses a weight of 900 gm for 1 kg. His gain percentage is:',
    optionA: '11.11%',
    optionB: '10%',
    optionC: '12.5%',
    optionD: '9.09%',
    correctAnswer: 'A',
    explanation: 'Gain % = [Error / (True Value - Error)] * 100 = (100 / 900) * 100 = 11.11%.',
    difficulty: 'Medium',
  },
  {
    questionText: 'By selling 33 meters of cloth, a shopkeeper gains the selling price of 11 meters. Find the gain percentage.',
    optionA: '50%',
    optionB: '33.33%',
    optionC: '25%',
    optionD: '40%',
    correctAnswer: 'A',
    explanation: 'Gain = SP of 11 m. SP of 33 m - CP of 33 m = SP of 11 m => CP of 33 m = SP of 22 m. Profit% = (11 / 22) * 100 = 50%.',
    difficulty: 'Medium',
  },
  {
    questionText: 'A man bought two articles for ₹3,000 each. He sold one at a profit of 10% and the other at a loss of 10%. Overall profit or loss percentage is:',
    optionA: '0% (No profit no loss)',
    optionB: '1% loss',
    optionC: '1% profit',
    optionD: '2% loss',
    correctAnswer: 'A',
    explanation: 'When CP of both articles is identical and % profit = % loss, net result is always 0%.',
    difficulty: 'Medium',
  },
  {
    questionText: 'If the cost price of 12 pens is equal to the selling price of 8 pens, the gain percentage is:',
    optionA: '50%',
    optionB: '33.33%',
    optionC: '66.66%',
    optionD: '25%',
    correctAnswer: 'A',
    explanation: '12 CP = 8 SP => SP / CP = 12 / 8 = 3 / 2. Profit% = (1 / 2) * 100 = 50%.',
    difficulty: 'Medium',
  },
  {
    questionText: 'A shopkeeper marks his goods 20% above the cost price and allows a discount of 10%. His gain percentage is:',
    optionA: '8%',
    optionB: '10%',
    optionC: '12%',
    optionD: '6%',
    correctAnswer: 'A',
    explanation: 'Let CP = 100. MP = 120. SP after 10% discount = 120 - 12 = 108. Profit% = 8%.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Successive discounts of 20% and 10% on an item of ₹500 result in a selling price of:',
    optionA: '₹360',
    optionB: '₹350',
    optionC: '₹380',
    optionD: '₹370',
    correctAnswer: 'A',
    explanation: 'SP = 500 * 0.80 * 0.90 = ₹360.',
    difficulty: 'Medium',
  },
  {
    questionText: 'A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?',
    optionA: '5',
    optionB: '4',
    optionC: '3',
    optionD: '4.5',
    correctAnswer: 'A',
    explanation: 'CP of 1 toffee = ₹1/6. SP for 20% gain = (1/6) * 1.20 = ₹1/5. Hence, 5 toffees for a rupee.',
    difficulty: 'Medium',
  },
  {
    questionText: 'A sells an article to B at 20% profit, and B sells it to C at 10% loss. If C paid ₹216, what did A pay?',
    optionA: '₹200',
    optionB: '₹220',
    optionC: '₹190',
    optionD: '₹180',
    correctAnswer: 'A',
    explanation: 'A * 1.20 * 0.90 = 216 => A * 1.08 = 216 => A = ₹200.',
    difficulty: 'Medium',
  },
  {
    questionText: 'By selling a table for ₹350 instead of ₹400, loss percent increases by 5%. The cost price of table is:',
    optionA: '₹1,000',
    optionB: '₹1,050',
    optionC: '₹950',
    optionD: '₹1,200',
    correctAnswer: 'A',
    explanation: 'Difference in SP = ₹50 represents 5% of CP. Therefore, CP = (50 / 5) * 100 = ₹1,000.',
    difficulty: 'Medium',
  },
  {
    questionText: 'A trader marks his goods so as to earn a profit of 25% after allowing a discount of 20%. The marked price of an article whose CP is ₹800 is:',
    optionA: '₹1,250',
    optionB: '₹1,200',
    optionC: '₹1,150',
    optionD: '₹1,300',
    correctAnswer: 'A',
    explanation: 'SP = 800 * 1.25 = ₹1000. MP * (1 - 0.20) = 1000 => MP = 1000 / 0.80 = ₹1,250.',
    difficulty: 'Medium',
  },

  // Hard
  {
    questionText: 'A person sells two machines at ₹396 each. On one he gains 10% and on the other he loses 10%. His overall loss in the whole transaction is:',
    optionA: '₹8',
    optionB: '₹6',
    optionC: '₹10',
    optionD: '₹12',
    correctAnswer: 'A',
    explanation: 'Total SP = 2 * 396 = ₹792. CP1 = 396 / 1.1 = 360. CP2 = 396 / 0.9 = 440. Total CP = 800. Loss = 800 - 792 = ₹8.',
    difficulty: 'Hard',
  },
  {
    questionText: 'A dishonest milkman claims to sell milk at cost price, but mixes water and gains 16.67%. The ratio of water to milk in the mixture is:',
    optionA: '1 : 6',
    optionB: '1 : 5',
    optionC: '1 : 7',
    optionD: '2 : 5',
    correctAnswer: 'A',
    explanation: '16.67% = 1/6. Profit corresponds directly to the added water on pure milk, hence water:milk = 1:6.',
    difficulty: 'Hard',
  },
  {
    questionText: 'A shopkeeper sells an article at 15% discount and makes a profit of 19%. If he gives a 10% discount, what will be his profit percentage?',
    optionA: '26%',
    optionB: '25%',
    optionC: '28%',
    optionD: '30%',
    correctAnswer: 'A',
    explanation: 'MP * 0.85 = CP * 1.19 => MP/CP = 1.19 / 0.85 = 1.4. At 10% discount, SP = 1.4 * 0.90 * CP = 1.26 CP. Profit = 26%.',
    difficulty: 'Hard',
  },
  {
    questionText: 'A reduction of 20% in the price of sugar enables a purchaser to obtain 4 kg more for ₹160. What is the original price per kg?',
    optionA: '₹10',
    optionB: '₹8',
    optionC: '₹12',
    optionD: '₹9',
    correctAnswer: 'A',
    explanation: '20% of 160 = ₹32. 4 kg costs ₹32 at reduced price => reduced price = ₹8/kg. Original price = 8 / 0.80 = ₹10/kg.',
    difficulty: 'Hard',
  },
  {
    questionText: 'A manufacturer sells an article to a wholesale dealer at a profit of 10%. The wholesale dealer sells it to a shopkeeper at 20% profit. The shopkeeper sells it to a customer for ₹56,100 at a loss of 15%. What was the cost of production?',
    optionA: '₹50,000',
    optionB: '₹48,000',
    optionC: '₹52,000',
    optionD: '₹55,000',
    correctAnswer: 'A',
    explanation: 'CP * 1.10 * 1.20 * 0.85 = 56100 => CP * 1.122 = 56100 => CP = ₹50,000.',
    difficulty: 'Hard',
  },
];

export const REASONING_ANALOGY_QUESTIONS: QuestionData[] = [
  // Easy
  {
    questionText: 'Select the related word from the given alternatives:\nOphthalmologist : Eye :: Dermatologist : ?',
    optionA: 'Skin',
    optionB: 'Bones',
    optionC: 'Heart',
    optionD: 'Brain',
    correctAnswer: 'A',
    explanation: 'An ophthalmologist specializes in eyes; a dermatologist specializes in skin.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related number from the given alternatives:\n12 : 144 :: 14 : ?',
    optionA: '196',
    optionB: '169',
    optionC: '210',
    optionD: '225',
    correctAnswer: 'A',
    explanation: 'The relationship is n : n^2. 14^2 = 196.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related word:\nNeedle : Clock :: Wheel : ?',
    optionA: 'Vehicle',
    optionB: 'Drive',
    optionC: 'Circular',
    optionD: 'Road',
    correctAnswer: 'A',
    explanation: 'Needle is a crucial moving part of a clock; wheel is a crucial moving part of a vehicle.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the odd one out from the given options:',
    optionA: 'Gold',
    optionB: 'Silver',
    optionC: 'Copper',
    optionD: 'Brass',
    correctAnswer: 'D',
    explanation: 'Brass is an alloy, while Gold, Silver, and Copper are pure elements/metals.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related letter cluster:\nCAT : DDW :: BIG : ?',
    optionA: 'CLJ',
    optionB: 'CKJ',
    optionC: 'CLL',
    optionD: 'BKJ',
    correctAnswer: 'A',
    explanation: 'C(+1)=D, A(+3)=D, T(+3)=W. B(+1)=C, I(+3)=L, G(+3)=J => CLJ.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related number:\n5 : 125 :: 6 : ?',
    optionA: '216',
    optionB: '225',
    optionC: '256',
    optionD: '196',
    correctAnswer: 'A',
    explanation: 'The pattern is n : n^3. 6^3 = 216.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the odd word from the alternatives:',
    optionA: 'Paris',
    optionB: 'Berlin',
    optionC: 'Rome',
    optionD: 'New York',
    correctAnswer: 'D',
    explanation: 'Paris, Berlin, and Rome are capital cities; New York is not a capital city.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related word:\nBook : Author :: Statue : ?',
    optionA: 'Sculptor',
    optionB: 'Painter',
    optionC: 'Mason',
    optionD: 'Architect',
    correctAnswer: 'A',
    explanation: 'An author creates a book; a sculptor creates a statue.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related pair:\nPen : Write :: Knife : ?',
    optionA: 'Cut',
    optionB: 'Sharp',
    optionC: 'Steel',
    optionD: 'Vegetable',
    correctAnswer: 'A',
    explanation: 'Pen is an instrument used to write; knife is used to cut.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the related number:\n7 : 49 :: 9 : ?',
    optionA: '81',
    optionB: '72',
    optionC: '90',
    optionD: '89',
    correctAnswer: 'A',
    explanation: '7^2 = 49; 9^2 = 81.',
    difficulty: 'Easy',
  },

  // Medium
  {
    questionText: 'Select the related number from the alternatives:\n8 : 28 :: 27 : ?',
    optionA: '65',
    optionB: '64',
    optionC: '54',
    optionD: '72',
    correctAnswer: 'A',
    explanation: '8 = 2^3, 28 = 3^3 + 1. 27 = 3^3, next is 4^3 + 1 = 64 + 1 = 65.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Select the related letter cluster:\nMASTER : OCUVGT :: DOCTOR : ?',
    optionA: 'FQEVQT',
    optionB: 'FQDVQT',
    optionC: 'FPEVQT',
    optionD: 'FQEWPT',
    correctAnswer: 'A',
    explanation: 'Every letter is shifted forward by +2: D->F, O->Q, C->E, T->V, O->Q, R->T => FQEVQT.',
    difficulty: 'Medium',
  },
  {
    questionText: 'In a code language, if FRIEND is coded as HUMJTK, then CANDLE is coded as:',
    optionA: 'EDRIRL',
    optionB: 'EDRIRK',
    optionC: 'DEQIRL',
    optionD: 'ECRIRL',
    correctAnswer: 'A',
    explanation: 'Pattern is +2, +3, +4, +5, +6, +7. C+2=E, A+3=D, N+4=R, D+5=I, L+6=R, E+7=L => EDRIRL.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Select the odd letter cluster:\n(A) BDFH (B) JLNP (C) RTVX (D) PRSU',
    optionA: 'PRSU',
    optionB: 'BDFH',
    optionC: 'JLNP',
    optionD: 'RTVX',
    correctAnswer: 'A',
    explanation: 'In BDFH, JLNP, and RTVX, every step has a difference of +2. In PRSU, S to U has +2, but R to S is +1.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Select the related number:\n25 : 37 :: 49 : ?',
    optionA: '65',
    optionB: '64',
    optionC: '60',
    optionD: '72',
    correctAnswer: 'A',
    explanation: '25 = 5^2, 37 = 6^2 + 1. 49 = 7^2, next is 8^2 + 1 = 64 + 1 = 65.',
    difficulty: 'Medium',
  },

  // Hard
  {
    questionText: 'Select the related number:\n17 : 290 :: 11 : ?',
    optionA: '122',
    optionB: '120',
    optionC: '121',
    optionD: '124',
    correctAnswer: 'A',
    explanation: '17^2 + 1 = 289 + 1 = 290. Similarly, 11^2 + 1 = 121 + 1 = 122.',
    difficulty: 'Hard',
  },
  {
    questionText: 'Select the odd pair of numbers:\n(A) 12 - 144 (B) 13 - 156 (C) 15 - 180 (D) 16 - 176',
    optionA: '12 - 144',
    optionB: '13 - 156',
    optionC: '15 - 180',
    optionD: '16 - 176',
    correctAnswer: 'A',
    explanation: '13 * 12 = 156, 15 * 12 = 180, 16 * 11 = 176 (n * (n-1)). In 12 - 144, it is 12 * 12.',
    difficulty: 'Hard',
  },
  {
    questionText: 'If 45 * 25 = 2 and 78 * 45 = 6, then 63 * 28 = ?',
    optionA: '1',
    optionB: '2',
    optionC: '3',
    optionD: '4',
    correctAnswer: 'A',
    explanation: '(4+5) - (2+5) = 9 - 7 = 2. (7+8) - (4+5) = 15 - 9 = 6. (6+3) - (2+8) = 9 - 10 = -1 (magnitude 1).',
    difficulty: 'Hard',
  },
  {
    questionText: 'Statements: Some mangoes are apples. All apples are bananas.\nConclusions:\nI. Some mangoes are bananas.\nII. Some bananas are mangoes.',
    optionA: 'Both conclusions I and II follow',
    optionB: 'Only conclusion I follows',
    optionC: 'Only conclusion II follows',
    optionD: 'Neither follows',
    correctAnswer: 'A',
    explanation: 'Since Some mangoes are apples and All apples are bananas, the intersection of mangoes and apples is within bananas. Hence both I and II follow.',
    difficulty: 'Hard',
  },
  {
    questionText: 'Select the missing term:\nAZ, BY, CX, ?',
    optionA: 'DW',
    optionB: 'EV',
    optionC: 'DU',
    optionD: 'DX',
    correctAnswer: 'A',
    explanation: 'First letter advances +1 (A, B, C, D); second letter moves backward -1 from Z (Z, Y, X, W) => DW.',
    difficulty: 'Hard',
  },
];

export const ENGLISH_QUESTIONS: QuestionData[] = [
  // Easy
  {
    questionText: 'Find the correctly spelt word:',
    optionA: 'Accommodate',
    optionB: 'Acommodate',
    optionC: 'Accomodate',
    optionD: 'Acomodate',
    correctAnswer: 'A',
    explanation: 'Accommodate has double "c" and double "m".',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the most appropriate synonym of "CANDID":',
    optionA: 'Frank',
    optionB: 'Deceitful',
    optionC: 'Shy',
    optionD: 'Arrogant',
    correctAnswer: 'A',
    explanation: '"Candid" means truthful and straightforward; frank.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the most appropriate antonym of "EXPAND":',
    optionA: 'Contract',
    optionB: 'Congest',
    optionC: 'Conclude',
    optionD: 'Convert',
    correctAnswer: 'A',
    explanation: '"Expand" means to grow larger; its direct opposite is "contract".',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the meaning of the given idiom: "A blessing in disguise"',
    optionA: 'An apparent misfortune that eventually results in something good',
    optionB: 'A secret gift',
    optionC: 'A religious prayer',
    optionD: 'A hidden danger',
    correctAnswer: 'A',
    explanation: '"A blessing in disguise" is a good thing that seemed bad at first.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Choose the one-word substitute for: "One who looks at the bright side of things"',
    optionA: 'Optimist',
    optionB: 'Pessimist',
    optionC: 'Pacifist',
    optionD: 'Atheist',
    correctAnswer: 'A',
    explanation: 'An optimist is a person who tends to be hopeful and confident about the future.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Fill in the blank: Neither he nor his friends ______ present at the venue.',
    optionA: 'were',
    optionB: 'was',
    optionC: 'is',
    optionD: 'are',
    correctAnswer: 'A',
    explanation: 'When subjects are connected by "neither... nor", the verb agrees with the closer subject ("his friends" = plural => were).',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the synonym of "ABUNDANT":',
    optionA: 'Plentiful',
    optionB: 'Scarce',
    optionC: 'Rare',
    optionD: 'Minute',
    correctAnswer: 'A',
    explanation: '"Abundant" means existing or available in large quantities; plentiful.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the antonym of "HOSTILE":',
    optionA: 'Friendly',
    optionB: 'Violent',
    optionC: 'Aggressive',
    optionD: 'Enemy',
    correctAnswer: 'A',
    explanation: '"Hostile" means showing or feeling active opposition; opposite is "friendly".',
    difficulty: 'Easy',
  },
  {
    questionText: 'Select the meaning of idiom: "Spill the beans"',
    optionA: 'Reveal a secret prematurely',
    optionB: 'Drop food on the floor',
    optionC: 'Waste money',
    optionD: 'Cook a meal',
    correctAnswer: 'A',
    explanation: '"Spill the beans" means to divulge secret information.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Identify the segment with an error: "She has been working / here since / two years."',
    optionA: 'since',
    optionB: 'She has been working',
    optionC: 'here',
    optionD: 'two years',
    correctAnswer: 'A',
    explanation: '"For" is used with a period of time (for two years), while "since" is for a point in time.',
    difficulty: 'Easy',
  },

  // Medium
  {
    questionText: 'Select the option that rectifies the error in the underlined part:\n"Scarcely had he gone than a police officer arrived."',
    optionA: 'Scarcely had he gone when',
    optionB: 'Scarcely did he went than',
    optionC: 'No sooner had he gone when',
    optionD: 'Hardly had he gone than',
    correctAnswer: 'A',
    explanation: '"Scarcely" and "Hardly" are followed by "when", not "than" (which follows "No sooner").',
    difficulty: 'Medium',
  },
  {
    questionText: 'Select the most appropriate synonym of "TACITURN":',
    optionA: 'Reserved',
    optionB: 'Talkative',
    optionC: 'Lively',
    optionD: 'Noisy',
    correctAnswer: 'A',
    explanation: '"Taciturn" refers to a person reserved or uncommunicative in speech; saying little.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Select the most appropriate antonym of "EPHEMERAL":',
    optionA: 'Eternal',
    optionB: 'Transient',
    optionC: 'Brief',
    optionD: 'Short-lived',
    correctAnswer: 'A',
    explanation: '"Ephemeral" means lasting for a very short time. The antonym is "eternal" or "permanent".',
    difficulty: 'Medium',
  },
  {
    questionText: 'One word substitution: "A person who hates or distrusts humankind"',
    optionA: 'Misanthrope',
    optionB: 'Philanthropist',
    optionC: 'Misogynist',
    optionD: 'Cannibal',
    correctAnswer: 'A',
    explanation: 'A misanthrope is a person who dislikes humankind and avoids human society.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Select the meaning of idiom: "To burn the midnight oil"',
    optionA: 'To work or study late into the night',
    optionB: 'To waste resources carelessly',
    optionC: 'To cause an accidental fire',
    optionD: 'To celebrate late at night',
    correctAnswer: 'A',
    explanation: '"Burn the midnight oil" means to read, study, or work late into the night.',
    difficulty: 'Medium',
  },

  // Hard
  {
    questionText: 'Identify the error: "The quality of these mangoes / are not as good / as the ones we bought yesterday."',
    optionA: 'are not as good',
    optionB: 'The quality of these mangoes',
    optionC: 'as the ones we bought',
    optionD: 'yesterday',
    correctAnswer: 'A',
    explanation: 'The subject of the sentence is "The quality" (singular), so the verb should be "is not as good".',
    difficulty: 'Hard',
  },
  {
    questionText: 'Select the synonym of "UBIQUITOUS":',
    optionA: 'Omnipresent',
    optionB: 'Rare',
    optionC: 'Unique',
    optionD: 'Invisible',
    correctAnswer: 'A',
    explanation: '"Ubiquitous" means present, appearing, or found everywhere; omnipresent.',
    difficulty: 'Hard',
  },
  {
    questionText: 'Select the antonym of "METICULOUS":',
    optionA: 'Careless',
    optionB: 'Scrupulous',
    optionC: 'Painstaking',
    optionD: 'Diligent',
    correctAnswer: 'A',
    explanation: '"Meticulous" means showing great attention to detail; very careful. The opposite is "careless".',
    difficulty: 'Hard',
  },
  {
    questionText: 'Select the correct sentence structure:\n(A) If he would have worked hard, he would have passed.\n(B) If he had worked hard, he would have passed.\n(C) If he had worked hard, he would pass.\n(D) If he worked hard, he would have passed.',
    optionA: 'If he had worked hard, he would have passed.',
    optionB: 'If he would have worked hard, he would have passed.',
    optionC: 'If he had worked hard, he would pass.',
    optionD: 'If he worked hard, he would have passed.',
    correctAnswer: 'A',
    explanation: 'Third conditional structure requires: If + past perfect, would + have + past participle.',
    difficulty: 'Hard',
  },
  {
    questionText: 'One word substitution: "The act of speaking irreverently about sacred things"',
    optionA: 'Blasphemy',
    optionB: 'Atheism',
    optionC: 'Heresy',
    optionD: 'Sacrilege',
    correctAnswer: 'A',
    explanation: 'Blasphemy is the action or offense of speaking sacrilegiously about God or sacred things.',
    difficulty: 'Hard',
  },
];

export const GENERAL_AWARENESS_QUESTIONS: QuestionData[] = [
  // Easy
  {
    questionText: 'Which Article of the Indian Constitution guarantees the "Right to Equality"?',
    optionA: 'Articles 14 to 18',
    optionB: 'Articles 19 to 22',
    optionC: 'Articles 23 to 24',
    optionD: 'Articles 25 to 28',
    correctAnswer: 'A',
    explanation: 'Articles 14 to 18 of the Indian Constitution deal with the Fundamental Right to Equality.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Who was the founder of the Maurya Dynasty in ancient India?',
    optionA: 'Chandragupta Maurya',
    optionB: 'Ashoka the Great',
    optionC: 'Bindusara',
    optionD: 'Harshavardhana',
    correctAnswer: 'A',
    explanation: 'Chandragupta Maurya founded the Maurya Empire in 322 BCE with the help of Chanakya.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Which planet in our solar system is known as the "Red Planet"?',
    optionA: 'Mars',
    optionB: 'Venus',
    optionC: 'Jupiter',
    optionD: 'Saturn',
    correctAnswer: 'A',
    explanation: 'Mars is called the Red Planet because iron minerals in its soil oxidize (rust), making the soil look red.',
    difficulty: 'Easy',
  },
  {
    questionText: 'What is the chemical formula of common salt?',
    optionA: 'NaCl',
    optionB: 'KCl',
    optionC: 'Na2CO3',
    optionD: 'NaHCO3',
    correctAnswer: 'A',
    explanation: 'Common table salt is Sodium Chloride (NaCl).',
    difficulty: 'Easy',
  },
  {
    questionText: 'In which year did the Dandi March (Salt Satyagraha) led by Mahatma Gandhi take place?',
    optionA: '1930',
    optionB: '1928',
    optionC: '1932',
    optionD: '1942',
    correctAnswer: 'A',
    explanation: 'The Dandi March took place from March 12, 1930 to April 6, 1930.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Which gas is most abundant in the Earth\'s atmosphere?',
    optionA: 'Nitrogen',
    optionB: 'Oxygen',
    optionC: 'Carbon Dioxide',
    optionD: 'Argon',
    correctAnswer: 'A',
    explanation: 'Nitrogen makes up approximately 78% of the Earth\'s atmosphere.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Who acts as the ex-officio Chairman of the Rajya Sabha?',
    optionA: 'Vice-President of India',
    optionB: 'President of India',
    optionC: 'Prime Minister of India',
    optionD: 'Speaker of Lok Sabha',
    correctAnswer: 'A',
    explanation: 'Under Article 64 of the Indian Constitution, the Vice-President of India is the ex-officio Chairman of the Rajya Sabha.',
    difficulty: 'Easy',
  },
  {
    questionText: 'What is the SI unit of electric current?',
    optionA: 'Ampere',
    optionB: 'Volt',
    optionC: 'Ohm',
    optionD: 'Watt',
    correctAnswer: 'A',
    explanation: 'The SI unit of electric current is the Ampere (A).',
    difficulty: 'Easy',
  },
  {
    questionText: 'Kaziranga National Park is famously known for which animal?',
    optionA: 'One-horned Rhinoceros',
    optionB: 'Royal Bengal Tiger',
    optionC: 'Asiatic Lion',
    optionD: 'Snow Leopard',
    correctAnswer: 'A',
    explanation: 'Kaziranga National Park in Assam hosts two-thirds of the world\'s great one-horned rhinoceroses.',
    difficulty: 'Easy',
  },
  {
    questionText: 'Which vitamin deficiency leads to Rickets in children?',
    optionA: 'Vitamin D',
    optionB: 'Vitamin A',
    optionC: 'Vitamin C',
    optionD: 'Vitamin B12',
    correctAnswer: 'A',
    explanation: 'Rickets is caused by a deficiency of Vitamin D, which is essential for calcium absorption in bones.',
    difficulty: 'Easy',
  },

  // Medium
  {
    questionText: 'Which Constitutional Amendment Act is known as the "Mini Constitution" of India?',
    optionA: '42nd Amendment Act (1976)',
    optionB: '44th Amendment Act (1978)',
    optionC: '73rd Amendment Act (1992)',
    optionD: '86th Amendment Act (2002)',
    correctAnswer: 'A',
    explanation: 'The 42nd Amendment Act of 1976 brought widespread changes to the Indian Constitution, hence termed the "Mini Constitution".',
    difficulty: 'Medium',
  },
  {
    questionText: 'Who was the Viceroy of India during the Partition of Bengal in 1905?',
    optionA: 'Lord Curzon',
    optionB: 'Lord Ripon',
    optionC: 'Lord Dalhousie',
    optionD: 'Lord Hardinge',
    correctAnswer: 'A',
    explanation: 'Lord Curzon was the Viceroy who ordered the Partition of Bengal in July 1905.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Which organ in the human body is responsible for producing insulin?',
    optionA: 'Pancreas',
    optionB: 'Liver',
    optionC: 'Kidney',
    optionD: 'Thyroid',
    correctAnswer: 'A',
    explanation: 'Insulin is synthesized and secreted by the beta cells of the Islets of Langerhans in the pancreas.',
    difficulty: 'Medium',
  },
  {
    questionText: 'Which river is known as the "Dakshin Ganga" (Ganges of the South)?',
    optionA: 'Godavari',
    optionB: 'Krishna',
    optionC: 'Cauvery',
    optionD: 'Mahanadi',
    correctAnswer: 'A',
    explanation: 'The Godavari River is often referred to as Dakshin Ganga due to its length and religious significance in southern India.',
    difficulty: 'Medium',
  },
  {
    questionText: 'The concept of "Directive Principles of State Policy" in the Indian Constitution was borrowed from:',
    optionA: 'Irish Constitution',
    optionB: 'US Constitution',
    optionC: 'British Constitution',
    optionD: 'Australian Constitution',
    correctAnswer: 'A',
    explanation: 'DPSPs (Part IV) were borrowed from the Constitution of Ireland (1937).',
    difficulty: 'Medium',
  },

  // Hard
  {
    questionText: 'Under which Article can the President of India declare a Financial Emergency?',
    optionA: 'Article 360',
    optionB: 'Article 352',
    optionC: 'Article 356',
    optionD: 'Article 370',
    correctAnswer: 'A',
    explanation: 'Article 360 empowers the President to proclaim a Financial Emergency if financial stability or credit of India is threatened.',
    difficulty: 'Hard',
  },
  {
    questionText: 'The Battle of Buxar was fought in which year?',
    optionA: '1764',
    optionB: '1757',
    optionC: '1761',
    optionD: '1772',
    correctAnswer: 'A',
    explanation: 'The Battle of Buxar was fought on October 22, 1764 between the British East India Company and combined Indian rulers.',
    difficulty: 'Hard',
  },
  {
    questionText: 'What is the phenomenon called when light bends as it passes from one medium to another of different optical density?',
    optionA: 'Refraction',
    optionB: 'Reflection',
    optionC: 'Dispersion',
    optionD: 'Diffraction',
    correctAnswer: 'A',
    explanation: 'Refraction is the change in direction of a wave passing from one medium to another caused by its change in speed.',
    difficulty: 'Hard',
  },
  {
    questionText: 'Which Five-Year Plan in India was based on the Mahalanobis model focusing on heavy industries?',
    optionA: 'Second Five-Year Plan (1956-1961)',
    optionB: 'First Five-Year Plan (1951-1956)',
    optionC: 'Third Five-Year Plan (1961-1966)',
    optionD: 'Fourth Five-Year Plan (1969-1974)',
    correctAnswer: 'A',
    explanation: 'The Second Five-Year Plan, formulated by P.C. Mahalanobis, prioritized rapid industrialization and basic heavy industries.',
    difficulty: 'Hard',
  },
  {
    questionText: 'Which Schedule of the Indian Constitution contains the list of recognized national languages?',
    optionA: 'Eighth Schedule',
    optionB: 'Seventh Schedule',
    optionC: 'Ninth Schedule',
    optionD: 'Tenth Schedule',
    correctAnswer: 'A',
    explanation: 'The Eighth Schedule currently lists 22 officially recognized languages of India.',
    difficulty: 'Hard',
  },
];
