import { JPSCQuestionRaw } from './types';

export const geographyQuestions: JPSCQuestionRaw[] = [
  // --- GENERAL & PHYSICAL GEOGRAPHY (35 Questions) ---
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'What is the latitudinal extent of mainland India from south to north?',
    options: ["8°4' N to 37°6' N", "6°4' N to 36°6' N", "8°4' N to 35°6' N", "7°4' N to 38°6' N"],
    correctAnswerIndex: 0,
    explanation: "Mainland India extends between latitudes 8°4' N (Kanyakumari) and 37°6' N (Indira Col in Ladakh). If including Andaman & Nicobar, Indira Point is at 6°45' N.",
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Standard Meridian of India (82°30\' E) passes through which of the following cities in Uttar Pradesh?',
    options: ['Mirzapur (near Prayagraj)', 'Varanasi', 'Kanpur', 'Lucknow'],
    correctAnswerIndex: 0,
    explanation: "The 82°30' E longitude chosen as the Indian Standard Meridian passes through Mirzapur near Prayagraj (UP) and cuts across five states: Uttar Pradesh, Madhya Pradesh, Chhattisgarh, Odisha, and Andhra Pradesh.",
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which channel separates the Andaman Islands from the Nicobar Islands in the Bay of Bengal?',
    options: ['Ten Degree Channel', 'Nine Degree Channel', 'Eight Degree Channel', 'Duncan Passage'],
    correctAnswerIndex: 0,
    explanation: 'The Ten Degree Channel (10° N latitude) separates the Andaman group (specifically Little Andaman) from the Nicobar group (Car Nicobar).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which is the highest peak in the Western Ghats and all of South India?',
    options: ['Anamudi', 'Doddabetta', 'Mullayanagiri', 'Kalsubai'],
    correctAnswerIndex: 0,
    explanation: 'Anamudi, standing at an elevation of 2,695 meters (8,842 ft) in the Anaimalai Hills of Kerala (Eravikulam National Park), is the highest peak in Peninsular India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which mountain range acts as a water divide between the Ganga river system in northern India and the peninsular river systems?',
    options: ['Vindhyan Range', 'Aravalli Range', 'Satpura Range', 'Western Ghats'],
    correctAnswerIndex: 0,
    explanation: 'The Vindhyan Range forms the primary geographic divide separating the drainage basin of the Ganga from the basins of the Narmada and other southern peninsular rivers.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Palghat Gap (Palakkad Gap) connects which two major regional centers in South India?',
    options: ['Coimbatore (Tamil Nadu) and Palakkad (Kerala)', 'Mumbai and Pune', 'Nashik and Mumbai', 'Bengaluru and Mangaluru'],
    correctAnswerIndex: 0,
    explanation: 'The Palghat Gap is a prominent low-elevation mountain pass (about 30 km wide) in the Western Ghats between the Nilgiris to the north and the Anaimalai Hills to the south, connecting Palakkad and Coimbatore.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Tropic of Cancer (23°30\' N) passes through how many Indian states?',
    options: ['7', '8', '9', '6'],
    correctAnswerIndex: 1,
    explanation: 'The Tropic of Cancer passes through 8 Indian states from west to east: Gujarat, Rajasthan, Madhya Pradesh, Chhattisgarh, Jharkhand, West Bengal, Tripura, and Mizoram.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Tropic of Cancer cuts across which district and prominent town in Jharkhand?',
    options: ['Kanke in Ranchi district', 'Jamshedpur in East Singhbhum', 'Deoghar town', 'Dhanbad city'],
    correctAnswerIndex: 0,
    explanation: 'The Tropic of Cancer passes directly through Kanke and Ormanjhi in Ranchi district, as well as parts of Lohardaga, Ramgarh, and Bokaro in Jharkhand.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which river forms the famous marble rocks gorge and Dhuandhar Falls near Jabalpur?',
    options: ['Narmada', 'Tapti', 'Mahanadi', 'Chambal'],
    correctAnswerIndex: 0,
    explanation: 'The Narmada River carves a scenic gorge through white marble rocks at Bhedaghat near Jabalpur in Madhya Pradesh, cascading down into the 30-meter Dhuandhar Falls.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which of the following peninsular rivers flows westwards through a rift valley between the Vindhya and Satpura ranges?',
    options: ['Narmada', 'Godavari', 'Krishna', 'Cauvery'],
    correctAnswerIndex: 0,
    explanation: 'Narmada originates at Amarkantak and flows 1,312 km westwards through a tectonic rift valley bounded by the Vindhyas to the north and the Satpuras to the south before emptying into the Arabian Sea.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which tributary of the Ganga originates in the Chota Nagpur Plateau of Jharkhand and was historically known as the "Sorrow of Bengal"?',
    options: ['Damodar', 'Subarnarekha', 'Barakar', 'Mayurakshi'],
    correctAnswerIndex: 0,
    explanation: 'The Damodar River originates near Tori in Chandwa (Latehar district, Chota Nagpur Plateau) and flows into the Hooghly. Its destructive seasonal inundations in West Bengal earned it the moniker "Sorrow of Bengal".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Majuli island, recognized as the world’s largest inhabited freshwater river island by Guinness World Records, is situated in which river?',
    options: ['Brahmaputra', 'Ganga', 'Barak', 'Godavari'],
    correctAnswerIndex: 0,
    explanation: 'Majuli is a fluvial river island formed by the Brahmaputra River and the Kherkutia Xuti channel in Assam, serving as the cultural epicenter of Neo-Vaishnavite Satras.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'At which confluence do the Bhagirathi and Alaknanda rivers meet to officially form the river Ganga?',
    options: ['Devprayag', 'Rudraprayag', 'Karnaprayag', 'Vishnuprayag'],
    correctAnswerIndex: 0,
    explanation: 'The two sacred headstreams, Bhagirathi (originating from Gaumukh, Gangotri) and Alaknanda (from Satopanth glacier), unite at Devprayag in Tehri Garhwal to flow onwards as the Ganga.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The longest river in Peninsular India, often called "Dakshin Ganga" or "Vriddha Ganga", is:',
    options: ['Godavari', 'Krishna', 'Cauvery', 'Mahanadi'],
    correctAnswerIndex: 0,
    explanation: 'Originating at Trimbakeshwar near Nashik, the Godavari flows for 1,465 km across Maharashtra, Telangana, and Andhra Pradesh, with the largest catchment basin in peninsular India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which peninsular river originates from the Brahmagiri Hills in Kodagu (Coorg) district of Karnataka?',
    options: ['Cauvery', 'Krishna', 'Tungabhadra', 'Pennar'],
    correctAnswerIndex: 0,
    explanation: 'The Cauvery originates at Talakaveri in the Brahmagiri range (Western Ghats) and flows 800 km eastwards through Karnataka and Tamil Nadu before debouching into the Bay of Bengal.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The pre-monsoon thunderstorms accompanied by heavy torrential rain and hail in West Bengal and adjoining Jharkhand in April-May are called:',
    options: ['Kalbaisakhi (Nor\'westers)', 'Mango Showers', 'Cherry Blossom', 'Loo'],
    correctAnswerIndex: 0,
    explanation: 'Kalbaisakhi (calamity of the month of Baisakh) or Nor\'westers are violent convective thunderstorms in eastern India that bring sudden temperature drops along with damaging squalls.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Winter rainfall experienced in northwestern parts of India (Punjab, Haryana, western UP) is caused by:',
    options: ['Western Disturbances originating in the Mediterranean Sea', 'Retreating Northeast Monsoon', 'Tropical Cyclones from Bay of Bengal', 'Southwest Monsoon currents'],
    correctAnswerIndex: 0,
    explanation: 'Western Disturbances are extra-tropical temperate storm depressions originating over the Mediterranean Sea and Caspian Sea, steered into northwest India by the subtropical westerly jet stream, crucial for Rabi crops like wheat.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which coast of India receives the bulk of its rainfall during October and November from the Retreating (Northeast) Monsoon?',
    options: ['Coromandel Coast (Tamil Nadu)', 'Konkan Coast', 'Malabar Coast', 'Northern Circars'],
    correctAnswerIndex: 0,
    explanation: 'As the monsoon trough retreats southward, northeast trade winds pick up moisture over the Bay of Bengal and deposit torrential precipitation on the Coromandel Coast of Tamil Nadu.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The black cotton soil (Regur soil) of the Deccan Traps was formed predominantly by the weathering of which rocks?',
    options: ['Basaltic lava flows', 'Granite and Gneiss', 'Sandstone', 'Limestone'],
    correctAnswerIndex: 0,
    explanation: 'Regur soil developed over the Deccan volcanic plateau due to the denudation of solidified fissure-basaltic lava flows, characterized by montmorillonite clay, high moisture retention, and self-ploughing capacity.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Laterite soils, extensively found in the Western Ghats and parts of Chota Nagpur, are formed due to:',
    options: ['Intense leaching by heavy rainfall', 'Mechanical weathering by wind', 'Deposition by river floods', 'Arid desiccation'],
    correctAnswerIndex: 0,
    explanation: 'Laterite soils develop in tropical regions experiencing alternating wet and dry seasons where high rainfall causes intense silica leaching, leaving residual oxides of iron and aluminum.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which is the largest brackish water coastal lagoon in India and designated as India’s first Ramsar site?',
    options: ['Chilika Lake (Odisha)', 'Pulicat Lake', 'Vembanad Lake', 'Kolleru Lake'],
    correctAnswerIndex: 0,
    explanation: 'Chilika Lake in Odisha, situated at the mouth of the Daya River, is the largest brackish water lagoon in Asia and was designated as India’s first Ramsar wetland of international importance in 1981.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Loktak Lake, famous for its floating phumdis and the Keibul Lamjao National Park, is located in which state?',
    options: ['Manipur', 'Meghalaya', 'Mizoram', 'Nagaland'],
    correctAnswerIndex: 0,
    explanation: 'Loktak Lake in Manipur is the largest freshwater lake in Northeast India, harboring the world’s only floating national park (Keibul Lamjao), the refuge of the endangered Sangai deer.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which mountain pass connects Srinagar with Leh across the Great Himalayas?',
    options: ['Zoji La', 'Rohtang Pass', 'Shipki La', 'Nathu La'],
    correctAnswerIndex: 0,
    explanation: 'Zoji La (elevation 3,528 m) on National Highway 1 connects the Kashmir Valley with the Ladakh plateau across the Great Himalayan range.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Nathu La Pass, through which the historic Sino-Indian border trade passes, is located in:',
    options: ['Sikkim', 'Arunachal Pradesh', 'Himachal Pradesh', 'Uttarakhand'],
    correctAnswerIndex: 0,
    explanation: 'Nathu La (14,140 ft) links Sikkim with the Tibet Autonomous Region of China and was reopened in 2006 for bilateral border trade.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Siachen Glacier, the longest glacier in the Karakoram and the world’s highest battlefield, is located in the valley of:',
    options: ['Nubra Valley', 'Shyok Valley', 'Suru Valley', 'Zanskar Valley'],
    correctAnswerIndex: 0,
    explanation: 'The Siachen Glacier (76 km long) is situated in the eastern Karakoram range; meltwater from its snout feeds the Nubra River, a tributary of the Shyok.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which geological fault structure separates the Meghalaya (Shillong) Plateau from the main Chota Nagpur Plateau?',
    options: ['Malda Fault (Garo-Rajmahal Gap)', 'Great Boundary Fault', 'Narmada-Son Fault', 'Himalayan Frontal Thrust'],
    correctAnswerIndex: 0,
    explanation: 'The Meghalaya Plateau is an outlier of the Peninsular shield separated from the Rajmahal Hills of Jharkhand by the tectonic down-faulting of the Malda Gap, later filled by Ganga-Brahmaputra alluvium.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Barren Island, the only confirmed active volcano in the Indian subcontinent, is situated in:',
    options: ['Andaman Sea', 'Lakshadweep Sea', 'Gulf of Mannar', 'Arabian Sea'],
    correctAnswerIndex: 0,
    explanation: 'Barren Island is an active stratovolcano lying in the volcanic arc of the Andaman Sea, about 138 km northeast of Port Blair.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The Lakshadweep archipelago in the Arabian Sea is composed entirely of:',
    options: ['Coral reef atolls', 'Submarine volcanic basalt', 'Granitic continental remnants', 'Deltaic sediment deposits'],
    correctAnswerIndex: 0,
    explanation: 'The 36 islands of Lakshadweep are biological coral atolls built upon the submerged Chagos-Laccadive submarine volcanic ridge in the Arabian Sea.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which of the following ranges is the oldest fold mountain system in India and among the oldest in the world?',
    options: ['Aravalli Range', 'Himalayas', 'Satpura Range', 'Eastern Ghats'],
    correctAnswerIndex: 0,
    explanation: 'The Aravallis are relict residual fold mountains formed during the Proterozoic orogeny (c. 1.8 billion years ago), running 692 km from Delhi to Palanpur in Gujarat.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'What is Guru Shikhar?',
    options: ['The highest peak of the Aravalli Range in Rajasthan', 'The highest peak of the Nilgiris', 'A volcanic crater in Deccan', 'A peak in Satpura'],
    correctAnswerIndex: 0,
    explanation: 'Guru Shikhar (elevation 1,722 m) in the Arbuda Mountains near Mount Abu, Sirohi district (Rajasthan), is the highest point of the Aravalli Range.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The region characterized by underground disappears of Himalayan streams into coarse gravel pebbles at the foot of the Shiwaliks is known as:',
    options: ['Bhabar', 'Tarai', 'Bhangar', 'Khadar'],
    correctAnswerIndex: 0,
    explanation: 'Bhabar is a narrow porous belt (8–10 km wide) along the foothills of the Shiwalik where fast-flowing rivers drop heavy boulders, causing streams to vanish beneath the porous surface.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The marshy, damp, heavily forested zone immediately south of the Bhabar belt where lost streams re-emerge is called:',
    options: ['Tarai', 'Khadar', 'Bhangar', 'Usar'],
    correctAnswerIndex: 0,
    explanation: 'The Tarai is an ill-drained marshy lowland belt south of Bhabar where underground streams re-emerge, historically covered with dense sal forests and rich wildlife.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'The older alluvium forming floodplains and higher terraces containing calcareous concretions (Kankar) is termed:',
    options: ['Bhangar', 'Khadar', 'Bhabar', 'Kallar'],
    correctAnswerIndex: 0,
    explanation: 'Bhangar represents mature, un-inundated older alluvium situated above flood levels, whereas Khadar represents newer, fertile annual flood deposits.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which river in India is recognized as the only major inland-draining river in the arid Thar Desert region?',
    options: ['Luni', 'Sabarmati', 'Mahi', 'Banas'],
    correctAnswerIndex: 0,
    explanation: 'The Luni River originates in the Pushkar valley of the Aravallis, flows 495 km southwest across Rajasthan, and dissipates into the salt marshes of the Rann of Kutch without reaching the sea.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'general-physical-geography',
    questionText: 'Which is the longest beach in India and the second longest urban natural beach in the world?',
    options: ['Marina Beach (Chennai)', 'Colva Beach (Goa)', 'Puri Beach (Odisha)', 'Kovalam Beach (Kerala)'],
    correctAnswerIndex: 0,
    explanation: 'Marina Beach along the Bay of Bengal in Chennai stretches approximately 13 km from Fort St. George to Foreshore Estate.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },

  // --- ECONOMIC, SOCIAL & DEMOGRAPHIC GEOGRAPHY (25 Questions) ---
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which region of India is famously hailed as the "Ruhr of India" owing to its dense concentration of iron, coal, and metallurgical industries?',
    options: ['Chota Nagpur Plateau region', 'Deccan Plateau', 'Malwa Plateau', 'Bastar Basin'],
    correctAnswerIndex: 0,
    explanation: 'The Chota Nagpur Plateau (spanning Jharkhand, West Bengal, Odisha, and Chhattisgarh) is called the Ruhr of India because of its mineral wealth in coking coal, iron ore, mica, bauxite, and copper.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which coalfield in Jharkhand holds the country’s largest reserves of prime metallurgical coking coal?',
    options: ['Jharia Coalfield', 'Raniganj Coalfield', 'Bokaro Coalfield', 'North Karanpura'],
    correctAnswerIndex: 0,
    explanation: 'Jharia Coalfield in Dhanbad district, Jharkhand, is India’s premier storehouse of prime coking coal required for blast furnace steel-making.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Khetri in Jhunjhunu district of Rajasthan is renowned across India for the extraction of which metal?',
    options: ['Copper', 'Lead and Zinc', 'Iron ore', 'Bauxite'],
    correctAnswerIndex: 0,
    explanation: 'The Khetri Copper Belt operated by Hindustan Copper Limited (HCL) is India’s foremost historical and commercial copper mining tract.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Jaduguda in East Singhbhum district of Jharkhand is internationally famous for mining which strategic nuclear mineral?',
    options: ['Uranium', 'Thorium', 'Titanium', 'Beryllium'],
    correctAnswerIndex: 0,
    explanation: 'Jaduguda was the first uranium mine in India, commissioned in 1967 and managed by the Uranium Corporation of India Limited (UCIL).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'The Kudremukh iron ore deposits in the Western Ghats are located in which state?',
    options: ['Karnataka', 'Goa', 'Maharashtra', 'Kerala'],
    correctAnswerIndex: 0,
    explanation: 'Kudremukh (horse-face peak) in Chikkamagaluru district of Karnataka possesses massive magnetite iron ore deposits historically exported through New Mangalore Port.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which Indian state is the leading producer of mica and bauxite?',
    options: ['Odisha for Bauxite and Andhra Pradesh for Mica', 'Jharkhand for both', 'Rajasthan for Bauxite', 'Chhattisgarh for both'],
    correctAnswerIndex: 0,
    explanation: 'Odisha accounts for over 50% of India’s bauxite output (Panchpatmali deposits), while Andhra Pradesh (Nellore belt) is currently the leading commercial producer of crude mica.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Digboi in Tinsukia district of Assam holds which historical distinction in India’s industrial landscape?',
    options: ['Oldest operating oil refinery in India (and Asia)', 'First coal mine in India', 'First tea plantation in India', 'First railway workshop'],
    correctAnswerIndex: 0,
    explanation: 'Crude oil was struck in Digboi in 1889, and the Digboi Refinery was commissioned in 1901, making it the oldest continually operating oil refinery in Asia.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which offshore oilfield located 160 km west of Mumbai contributes the single largest share of India’s domestic crude petroleum production?',
    options: ['Mumbai High (Bombay High)', 'Bassein field', 'Ravva field', 'Mangala field'],
    correctAnswerIndex: 0,
    explanation: 'Discovered in 1974 by ONGC and commissioned in 1976 with the Sagar Samrat drill ship, Mumbai High in the Arabian Sea is India’s premier offshore oil reservoir.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'The Bhilai Steel Plant in Chhattisgarh was established in 1955 with technical and financial collaboration from which country?',
    options: ['USSR (Soviet Union)', 'West Germany', 'United Kingdom', 'United States'],
    correctAnswerIndex: 0,
    explanation: 'The Bhilai Steel Plant was built during the Second Five-Year Plan with Soviet assistance, drawing iron ore from Dalli-Rajhara and coal from Korba.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'The Bokaro Steel Plant in Jharkhand was set up during which Five Year Plan with Soviet assistance?',
    options: ['Third Five-Year Plan', 'First Five-Year Plan', 'Second Five-Year Plan', 'Fourth Five-Year Plan'],
    correctAnswerIndex: 0,
    explanation: 'Incorporated in 1964 during the Third Five-Year Plan, Bokaro Steel Plant was conceived as India’s first indigenous steel plant designed with Soviet collaboration.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'National Waterway 1 (NW-1) spans a navigable distance of 1,620 km along which river corridor?',
    options: ['Ganga-Bhagirathi-Hooghly river system from Prayagraj to Haldia', 'Brahmaputra from Sadiya to Dhubri', 'Godavari from Kakinada to Puducherry', 'West Coast Canal in Kerala'],
    correctAnswerIndex: 0,
    explanation: 'NW-1 runs from Prayagraj (UP) through Varanasi, Patna, Sahibganj (Jharkhand), to Haldia (West Bengal) along the Ganga-Bhagirathi-Hooghly waterway.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which multi-modal river terminal on National Waterway 1 was constructed in Jharkhand to promote domestic and cargo transit?',
    options: ['Sahibganj Multi-Modal Terminal', 'Pakur Terminal', 'Rajmahal Terminal', 'Deoghar River Port'],
    correctAnswerIndex: 0,
    explanation: 'The Sahibganj Multi-Modal Terminal on the Ganga in Jharkhand, inaugurated in September 2019 under the Jal Marg Vikas Project, facilitates trade connectivity to the Northeast and Nepal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which natural port located in Andhra Pradesh is deeply landlocked and protected by the Dolphin’s Nose rock promontory?',
    options: ['Visakhapatnam Port', 'Chennai Port', 'Paradip Port', 'Tuticorin Port'],
    correctAnswerIndex: 0,
    explanation: 'Visakhapatnam Port is the deepest landlocked natural harbor on the eastern coast of India, protected from cyclonic storms by the headland Dolphin\'s Nose.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which is the only riverine major port in India?',
    options: ['Kolkata Port (Syama Prasad Mookerjee Port)', 'Mumbai Port', 'Kandla Port', 'Mormugao Port'],
    correctAnswerIndex: 0,
    explanation: 'The Port of Kolkata situated along the tidal Hooghly River, 203 km from the sea, is India’s sole major riverine port, operating twin dock facilities at Kolkata and Haldia.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'According to Census 2011, which Indian state has the highest population density?',
    options: ['Bihar (1,106 persons/sq km)', 'West Bengal', 'Uttar Pradesh', 'Kerala'],
    correctAnswerIndex: 0,
    explanation: 'As per Census 2011, Bihar surpassed West Bengal (1,028) with a population density of 1,106 persons per square kilometer, making it the most densely populated state in India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'According to Census 2011, which Indian state recorded the lowest population density in the country?',
    options: ['Arunachal Pradesh (17 persons/sq km)', 'Mizoram', 'Sikkim', 'Nagaland'],
    correctAnswerIndex: 0,
    explanation: 'Arunachal Pradesh recorded a population density of only 17 persons per square kilometer in Census 2011 due to its rugged mountainous terrain and dense forest cover.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which state recorded the highest sex ratio (females per 1,000 males) in India according to Census 2011?',
    options: ['Kerala (1,084)', 'Tamil Nadu', 'Andhra Pradesh', 'Chhattisgarh'],
    correctAnswerIndex: 0,
    explanation: 'Kerala recorded the highest sex ratio of 1,084 females per 1,000 males in Census 2011, followed by Puducherry (1,037) and Tamil Nadu (996).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which Indian state recorded a negative decadal population growth rate (-0.58%) between 2001 and 2011?',
    options: ['Nagaland', 'Sikkim', 'Kerala', 'Goa'],
    correctAnswerIndex: 0,
    explanation: 'Nagaland was the only state in India to record a negative decadal population growth rate of -0.58% during the 2001–2011 census period.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'According to Census 2011, what is the overall literacy rate of India?',
    options: ['74.04%', '72.90%', '76.10%', '68.50%'],
    correctAnswerIndex: 0,
    explanation: 'As per the 2011 Census, the literacy rate of India stands at 74.04% (82.14% for males and 65.46% for females).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which state in India has the largest scheduled tribe (ST) population in terms of absolute numbers as per Census 2011?',
    options: ['Madhya Pradesh', 'Maharashtra', 'Odisha', 'Jharkhand'],
    correctAnswerIndex: 0,
    explanation: 'Madhya Pradesh has the largest ST population in India (15.31 million, representing 14.7% of India’s total tribal population), followed by Maharashtra and Odisha.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'The "Golden Quadrilateral" super-highway network connecting Delhi, Mumbai, Chennai, and Kolkata has a total route length of approximately:',
    options: ['5,846 km', '6,500 km', '4,900 km', '7,200 km'],
    correctAnswerIndex: 0,
    explanation: 'The Golden Quadrilateral highway network conceived under the National Highways Development Project (NHDP) by Prime Minister Atal Bihari Vajpayee measures exactly 5,846 km.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which Indian railway station has the longest railway platform in the world as of 2023?',
    options: ['Shree Siddharoodha Swamiji Hubballi Station (Karnataka)', 'Gorakhpur Railway Station', 'Kollam Junction', 'Kharagpur Railway Station'],
    correctAnswerIndex: 0,
    explanation: 'Platform No. 8 of Shree Siddharoodha Swamiji Hubballi Railway Station in Karnataka measures 1,507 meters, officially recognized as the world’s longest railway platform (surpassing Gorakhpur’s 1,366 m).',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which state of India is the largest producer of raw silk, accounting for over 70% of the country’s mulberry silk?',
    options: ['Karnataka', 'Andhra Pradesh', 'Assam', 'West Bengal'],
    correctAnswerIndex: 0,
    explanation: 'Karnataka, centered around Ramanagara, Mysuru, and Mandya, produces the vast majority of India’s commercial mulberry silk.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which state in India is the largest producer of Coffee, particularly Arabica and Robusta varieties in the Baba Budan Giri hills?',
    options: ['Karnataka', 'Kerala', 'Tamil Nadu', 'Andhra Pradesh'],
    correctAnswerIndex: 0,
    explanation: 'Karnataka accounts for over 70% of India’s total coffee production, centered in the districts of Kodagu, Chikkamagaluru, and Hassan.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-geography',
    topicSlug: 'economic-social-geography',
    questionText: 'Which Indian state is the leading producer of natural rubber, accounting for more than 75% of the country’s total harvest?',
    options: ['Kerala', 'Tripura', 'Karnataka', 'Tamil Nadu'],
    correctAnswerIndex: 0,
    explanation: 'Kerala’s humid tropical climate, slopes of the Western Ghats, and well-drained acidic laterite soils make it the undisputed leader in natural rubber cultivation in India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
];
