import { JPSCQuestionRaw } from './types';

export const historyQuestions: JPSCQuestionRaw[] = [
  // --- ANCIENT INDIA (30 Questions) ---
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which Indus Valley Civilization site has provided evidence of a tidal dockyard connected to the Gulf of Khambhat via the Bhogava river?',
    options: ['Kalibangan', 'Lothal', 'Dholavira', 'Banawali'],
    correctAnswerIndex: 1,
    explanation: 'Lothal, located in the Bhal region of modern Gujarat along the Bhogava river, possessed a massive brick basin identified as a tidal dockyard, proving extensive maritime trade with West Asia and Mesopotamia.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'At which Harappan site was a unique stone-cut reservoir and sophisticated water harvesting system discovered?',
    options: ['Dholavira', 'Rakhigarhi', 'Harappa', 'Mohenjo-daro'],
    correctAnswerIndex: 0,
    explanation: 'Dholavira, located in the Khadir Bet island in the Rann of Kutch (Gujarat), is renowned for its monumental stone architecture, tripartite city planning, and a series of 16 interconnecting stone-cut water reservoirs.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The famous "Dancing Girl" bronze figurine was excavated from which Indus Valley site?',
    options: ['Harappa', 'Mohenjo-daro', 'Chanhudaro', 'Kalibangan'],
    correctAnswerIndex: 1,
    explanation: 'The iconic lost-wax cast bronze statuette of the Dancing Girl (dated c. 2500 BCE) was discovered by Ernest Mackay in 1926 in the HR area of Mohenjo-daro.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which Vedic text contains the famous dialogue between Nachiketa and Yama regarding death and the nature of the soul (Atman)?',
    options: ['Chandogya Upanishad', 'Katha Upanishad', 'Mundaka Upanishad', 'Brihadaranyaka Upanishad'],
    correctAnswerIndex: 1,
    explanation: 'The Katha Upanishad (belonging to the Krishna Yajurveda) narrates the spiritual discourse between the young boy Nachiketa and Yama, the god of death, on the secrets of immortality and self-realization.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The national motto of India, "Satyameva Jayate", inscribed below the emblem of India, is taken from which Upanishad?',
    options: ['Mundaka Upanishad', 'Mandukya Upanishad', 'Taittiriya Upanishad', 'Aitareya Upanishad'],
    correctAnswerIndex: 0,
    explanation: 'The phrase "Satyameva Jayate" (Truth alone triumphs) is a mantra from the ancient Hindu scripture Mundaka Upanishad (Mundaka 3.1.6).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'In Early Vedic society, the assembly of elders and distinguished persons was known as:',
    options: ['Samiti', 'Sabha', 'Vidatha', 'Gana'],
    correctAnswerIndex: 1,
    explanation: 'In the Rigvedic period, Sabha was an exclusive council of elders and elite nobles, whereas Samiti was a broader folk assembly of the entire community that could elect the Rajan.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which ancient Mahajanapada had its twin capitals at Ujjayini (northern part) and Mahishmati (southern part)?',
    options: ['Vatsa', 'Avanti', 'Kosala', 'Magadha'],
    correctAnswerIndex: 1,
    explanation: 'Avanti was divided into two parts by the river Vetravati: the northern capital was Ujjayini (modern Ujjain) and the southern capital was Mahishmati, located along the Narmada.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The First Buddhist Council was convened immediately after the Mahaparinirvana of the Buddha under the patronage of which king?',
    options: ['Ashoka', 'Kanishka', 'Ajatashatru', 'Kalashoka'],
    correctAnswerIndex: 2,
    explanation: 'The First Buddhist Council was held in 483 BCE at the Saptaparni cave in Rajagriha under the patronage of King Ajatashatru of the Haryanka dynasty, presided over by Mahakassapa.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Where did Gautama Buddha deliver his first sermon, known as the "Dharmachakrapravartana"?',
    options: ['Bodh Gaya', 'Sarnath', 'Kushinagar', 'Sravasti'],
    correctAnswerIndex: 1,
    explanation: 'After attaining enlightenment under the Bodhi tree at Bodh Gaya, Buddha traveled to the deer park in Rishipattana (modern Sarnath near Varanasi) where he set the wheel of law in motion.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Parshvanatha, the 23rd Tirthankara of Jainism, is closely associated with which mountain in modern Jharkhand where he attained Nirvana?',
    options: ['Mandara Hill', 'Parasnath Hill (Sammed Shikharji)', 'Rajgir Hills', 'Dalma Hill'],
    correctAnswerIndex: 1,
    explanation: 'Sammed Shikharji located on Parasnath Hill in Giridih district, Jharkhand, is the most sacred Jain pilgrimage site where 20 of the 24 Tirthankaras, including Parshvanatha, attained Nirvana.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which Jain council led to the final split of Jainism into the Digambara and Svetambara sects?',
    options: ['First Council at Pataliputra', 'Second Council at Vallabhi', 'Third Council at Vaishali', 'Council at Kanchipuram'],
    correctAnswerIndex: 0,
    explanation: 'The First Jain Council was held around 300 BCE at Pataliputra under the leadership of Sthulabhadra following the great Magadha famine, formalizing the divergence between Bhadrabahu’s followers (Digambara) and Sthulabhadra’s followers (Svetambara).',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Megasthenes, the Greek ambassador sent by Seleucus Nicator, lived in the court of which Indian ruler?',
    options: ['Chandragupta Maurya', 'Bindusara', 'Ashoka', 'Samudragupta'],
    correctAnswerIndex: 0,
    explanation: 'Megasthenes visited the court of Chandragupta Maurya at Pataliputra around 302 BCE and recorded his vivid observations on Mauryan society and imperial administration in his treatise "Indica".',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'In Ashoka’s Rock Edicts, which edict provides direct information on the Kalinga War and his profound remorse?',
    options: ['Major Rock Edict XIII', 'Major Rock Edict XII', 'Major Rock Edict V', 'Pillar Edict VII'],
    correctAnswerIndex: 0,
    explanation: 'Major Rock Edict XIII explicitly describes Ashoka’s conquest of Kalinga in the 8th year of his coronation, the suffering of hundreds of thousands of people, and his subsequent renunciation of Bherighosha in favor of Dhammaghosha.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which script was primarily used for Emperor Ashoka’s edicts throughout northwestern India (modern Pakistan)?',
    options: ['Brahmi', 'Kharosthi', 'Aramaic', 'Greek'],
    correctAnswerIndex: 1,
    explanation: 'While Brahmi script was used across most of the subcontinent, Kharosthi (written right-to-left, derived from Aramaic) was used for Ashoka’s inscriptions in northwestern regions like Shahbazgarhi and Mansehra.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Who was the court poet of King Samudragupta that composed the famous Allahabad Pillar Inscription (Prayag Prashasti)?',
    options: ['Kalidasa', 'Harishena', 'Banabhatta', 'Ravikirti'],
    correctAnswerIndex: 1,
    explanation: 'Harishena, the Sandhivigrahika (minister for peace and war) and Mahadandanayaka in Samudragupta’s court, composed the celebrated Sanskrit eulogy in Champu kavya style inscribed on the Ashokan pillar at Prayagraj.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'During whose reign did the Chinese Buddhist monk Faxian (Fa-Hien) visit India?',
    options: ['Chandragupta I', 'Chandragupta II (Vikramaditya)', 'Kumaragupta I', 'Harshavardhana'],
    correctAnswerIndex: 1,
    explanation: 'Faxian visited northern India during the reign of Chandragupta II (c. 399–414 CE) to collect authentic Buddhist monastic texts (Vinaya Pitaka).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Who among the following Gupta rulers founded the ancient Mahavihara of Nalanda?',
    options: ['Samudragupta', 'Kumaragupta I', 'Skandagupta', 'Budhagupta'],
    correctAnswerIndex: 1,
    explanation: 'Kumaragupta I (Shakraditya) founded Nalanda University in the 5th century CE in modern Bihar, which grew into the premier Buddhist intellectual center of Asia.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The Iron Pillar near Qutub Minar in Delhi, which has resisted corrosion for over 1,600 years, bears an inscription referring to a king named:',
    options: ['Chandra', 'Ashoka', 'Harsha', 'Kanishka'],
    correctAnswerIndex: 0,
    explanation: 'The inscription on the Mehrauli Iron Pillar commemorates the military victories of King "Chandra", universally identified by historians with Chandragupta II Vikramaditya of the Gupta dynasty.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Banabhatta was the court poet of which North Indian emperor and wrote his biography "Harshacharita"?',
    options: ['Chandragupta Maurya', 'Harshavardhana', 'Dharmapala', 'Yashovarman'],
    correctAnswerIndex: 1,
    explanation: 'Banabhatta lived in the royal court of Emperor Harshavardhana of Kannauj (Pushyabhuti dynasty) and authored Harshacharita as well as the Sanskrit romantic novel Kadambari.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which Chalukya ruler defeated Emperor Harshavardhana on the banks of the Narmada River in 618–619 CE?',
    options: ['Pulakeshin I', 'Pulakeshin II', 'Kirtivarman I', 'Vikramaditya I'],
    correctAnswerIndex: 1,
    explanation: 'Pulakeshin II of the Badami Chalukyas checked Harsha’s southward expansion at the Narmada River, as recorded by his court poet Ravikirti in the famous Aihole Inscription.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The renowned Chinese pilgrim Xuanzang (Hiuen Tsang) attended which grand religious assembly convened by King Harsha?',
    options: ['Kannauj Assembly', 'Prayag Assembly', 'Pataliputra Assembly', 'Valabhi Assembly'],
    correctAnswerIndex: 0,
    explanation: 'Harsha organized a grand 20-day theological assembly at Kannauj in 643 CE to honor Xuanzang and popularize Mahayana Buddhist doctrines, attended by 20 tributary kings and thousands of monks.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which Sangam age Tamil epic, composed by Ilango Adigal, narrates the tragedy of Kannagi and Kovalan?',
    options: ['Manimekalai', 'Silappadikaram', 'Sivaka Chintamani', 'Tolkappiyam'],
    correctAnswerIndex: 1,
    explanation: 'Silappadikaram (The Tale of an Anklet), composed by Prince Ilango Adigal, is one of the Five Great Epics of Tamil literature, chronicling Kannagi’s divine wrath on the city of Madurai after the wrongful execution of her husband Kovalan.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The Satavahana dynasty used which language primarily for their official royal inscriptions and coin legends?',
    options: ['Sanskrit', 'Prakrit', 'Tamil', 'Telugu'],
    correctAnswerIndex: 1,
    explanation: 'The Satavahana kings patronized Prakrit (in Brahmi script) as their administrative and epigraphic language, as exemplified in the Nanaghat and Nasik cave inscriptions.',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The famous astronomical work "Suryasiddhanta" and the mathematical concept of zero were pioneered during the Gupta period primarily associated with:',
    options: ['Varahamihira', 'Aryabhata', 'Brahmagupta', 'Bhaskara I'],
    correctAnswerIndex: 1,
    explanation: 'Aryabhata (born 476 CE at Kusumapura/Pataliputra) authored Aryabhatiya, calculating the value of pi to four decimal places, explaining solar/lunar eclipses scientifically, and proposing the Earth’s axial rotation.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Which Kushana emperor convened the Fourth Buddhist Council in Kundalavana, Kashmir?',
    options: ['Kujula Kadphises', 'Vima Kadphises', 'Kanishka I', 'Huvishka'],
    correctAnswerIndex: 2,
    explanation: 'Kanishka I convened the Fourth Buddhist Council around 72 CE in Kashmir, presided over by Vasumitra and Ashvaghosha, which resulted in the definitive division into Mahayana and Hinayana.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The Junagadh Rock Inscription of 150 CE, written in completely chaste classical Sanskrit, was issued by which Western Kshatrapa ruler?',
    options: ['Nahapana', 'Rudradaman I', 'Chashtana', 'Rudrasimha I'],
    correctAnswerIndex: 1,
    explanation: 'Saka ruler Rudradaman I issued the Junagadh inscription, detailing his reconstruction of the Sudarshana Lake embankment originally built during Chandragupta Maurya’s rule and renovated under Ashoka.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The philosophy of "Syadvada" (doctrine of conditioned predication) is a fundamental epistemological concept of which school?',
    options: ['Buddhism', 'Jainism', 'Charvaka', 'Nyaya'],
    correctAnswerIndex: 1,
    explanation: 'Syadvada, along with Anekantavada (multi-sided nature of truth), forms the core metaphysical and logical doctrine of Jainism, stating that all judgments are relative and hold true only from specific perspectives.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'In Mauryan administration, the high-ranking official in charge of treasury and revenue assessment was termed:',
    options: ['Samaharta', 'Sannidhata', 'Sitadhyaksha', 'Karmantika'],
    correctAnswerIndex: 0,
    explanation: 'According to Kautilya’s Arthashastra, the Samaharta was the Collector General of revenue responsible for assessment and collection, whereas the Sannidhata was the Chief Treasurer and keeper of the royal storehouse.',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'Who was the Greek ambassador sent to the court of King Bhagabhadra who erected the famous Garuda Pillar at Vidisha (Besnagar)?',
    options: ['Megasthenes', 'Deimachus', 'Heliodorus', 'Dionysius'],
    correctAnswerIndex: 2,
    explanation: 'Heliodorus, an Indo-Greek ambassador from Taxila representing King Antialcidas, dedicated a stone pillar to Lord Vasudeva at Besnagar around 113 BCE, declaring himself a "Bhagavata".',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'ancient-india',
    questionText: 'The Boghazkoi inscription of Asia Minor (dated c. 1380 BCE) mentions which four Vedic deities as witnesses to a peace treaty?',
    options: [
      'Indra, Varuna, Mitra, Nasatya',
      'Agni, Soma, Surya, Vayu',
      'Brahma, Vishnu, Shiva, Indra',
      'Indra, Agni, Yama, Varuna',
    ],
    correctAnswerIndex: 0,
    explanation: 'The Boghazkoi clay tablets recording a treaty between the Hittite King Suppiluliuma and the Mitanni King Shattiwaza invoke the four Vedic deities Indra, Mitra, Varuna, and Nasatyas (Ashvins).',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },

  // --- MEDIEVAL INDIA (30 Questions) ---
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Who founded the Slave (Mamluk) dynasty and was popularly known as "Lakh Baksh" for his immense generosity?',
    options: ['Iltutmish', 'Qutb-ud-din Aibak', 'Ghiyas-ud-din Balban', 'Nasir-ud-din Mahmud'],
    correctAnswerIndex: 1,
    explanation: 'Qutb-ud-din Aibak, who assumed power in Lahore and Delhi in 1206 following Muhammad Ghori’s death, earned the epithet "Lakh Baksh" (giver of lakhs) due to his lavish charity.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Delhi Sultan instituted the rigorous court ceremonial practices of "Sijdah" (prostration) and "Paibos" (kissing the monarch’s feet)?',
    options: ['Alauddin Khalji', 'Ghiyas-ud-din Balban', 'Muhammad bin Tughlaq', 'Iltutmish'],
    correctAnswerIndex: 1,
    explanation: 'Balban introduced Persian court etiquette including Sijdah, Paibos, and the Iranian spring festival Nauroz to cultivate an aura of divine majesty and absolute royal authority.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Delhi Sultan introduced market control regulations and established the office of "Shahna-i-Mandi" to strictly regulate grain prices?',
    options: ['Balban', 'Alauddin Khalji', 'Firoz Shah Tughlaq', 'Sikandar Lodi'],
    correctAnswerIndex: 1,
    explanation: 'Alauddin Khalji enacted strict market regulations, price ceilings on all essential commodities, and appointed intelligence officers (Munhiyans) and market supervisors (Shahna-i-Mandi) to maintain a massive standing army.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Moroccan traveler Ibn Battuta visited India during the reign of which Delhi Sultan and was appointed as Qazi of Delhi?',
    options: ['Alauddin Khalji', 'Muhammad bin Tughlaq', 'Ghiyasuddin Tughlaq', 'Bahlul Lodi'],
    correctAnswerIndex: 1,
    explanation: 'Ibn Battuta reached Delhi in 1334 during the reign of Muhammad bin Tughlaq, served as Grand Qazi of Delhi for over six years, and recorded his travels in the book "Rihla".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which ruler established the city of Agra in 1504 and shifted the imperial capital from Delhi to Agra?',
    options: ['Bahlul Lodi', 'Sikandar Lodi', 'Ibrahim Lodi', 'Sher Shah Suri'],
    correctAnswerIndex: 1,
    explanation: 'Sikandar Lodi founded Agra in 1504 on the banks of Yamuna to tighten royal command over central trade routes and Rajasthan chieftains.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The First Battle of Panipat (1526) was fought between Babur and which ruler of Delhi?',
    options: ['Sikandar Lodi', 'Ibrahim Lodi', 'Rana Sanga', 'Sher Shah Suri'],
    correctAnswerIndex: 1,
    explanation: 'On April 21, 1526, Babur defeated Ibrahim Lodi at Panipat using superior gunpowder artillery and the Ottoman Tulghuma battle tactic, inaugurating Mughal rule in India.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Sher Shah Suri introduced a standard silver coin that remained the basis of India’s currency system for centuries. What was it called?',
    options: ['Dam', 'Rupiya', 'Tanka', 'Mohur'],
    correctAnswerIndex: 1,
    explanation: 'Sher Shah Suri introduced the standardized silver coin called "Rupiya" (weighing 178 grains) along with copper "Dam" (380 grains), replacing the earlier debased mixed coinage.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which battle in 1539 forced Humayun to flee across the Ganga into Agra after being decisively outmaneuvered by Sher Khan?',
    options: ['Battle of Chausa', 'Battle of Kannauj (Bilgram)', 'Battle of Ghaghra', 'Battle of Machhiwara'],
    correctAnswerIndex: 0,
    explanation: 'Sher Khan routed Humayun at Chausa on June 26, 1539, on the banks of the Ganga near Buxar, after which Sher Khan formally assumed the sovereign title "Sher Shah".',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The Second Battle of Panipat (1556) was fought between Akbar’s regent Bairam Khan and which Hindu general?',
    options: ['Hemu (Hemchandra Vikramaditya)', 'Rana Pratap', 'Rana Sanga', 'Maldeo Rathore'],
    correctAnswerIndex: 0,
    explanation: 'On November 5, 1556, the 13-year-old Akbar under Bairam Khan defeated Hemu, who had occupied Delhi and assumed the regal title Raja Vikramaditya.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Emperor Akbar constructed the "Ibadat Khana" (House of Worship) in 1575 at Fatehpur Sikri for which primary purpose?',
    options: [
      'Conducting private royal prayers',
      'Theological discussions among scholars of diverse religions',
      'Treasury repository for war spoils',
      'Judicial trials for treason',
    ],
    correctAnswerIndex: 1,
    explanation: 'Akbar established the Ibadat Khana to host interfaith philosophical debates among Sunni and Shia scholars, Christians (Jesuits), Hindus, Jains, Zoroastrians, and Charvakas, culminating in his philosophy of Sulh-i-Kul.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Who was Akbar’s finance minister that designed the revolutionary "Dahsala" land revenue settlement system in 1580?',
    options: ['Raja Man Singh', 'Raja Todar Mal', 'Abdul Rahim Khan-i-Khana', 'Abul Fazl'],
    correctAnswerIndex: 1,
    explanation: 'Raja Todar Mal institutionalized the Ain-i-Dahsala, which calculated tax based on the average agricultural yield and produce prices over the previous ten-year period (1570–1580).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Mughal emperor was conferred the honorary title of "Zinda Pir" (Living Saint) by orthodox contemporaries due to his frugal personal life?',
    options: ['Jahangir', 'Shah Jahan', 'Aurangzeb', 'Babur'],
    correctAnswerIndex: 2,
    explanation: 'Aurangzeb Alamgir was called "Zinda Pir" because he lived austerely, refused to use imperial treasury funds for personal expenses, and earned his livelihood by sewing caps and copying the Quran.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Sir Thomas Roe arrived in India in 1615 as the official ambassador of King James I of England in the court of which Mughal Emperor?',
    options: ['Akbar', 'Jahangir', 'Shah Jahan', 'Aurangzeb'],
    correctAnswerIndex: 1,
    explanation: 'Sir Thomas Roe spent three years (1615–1618) at the court of Jahangir at Ajmer and secured trade concessions and permission to build English factories at Surat.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The Vijayanagara Empire was founded in 1336 along the banks of the Tungabhadra River by which two brothers?',
    options: ['Harihara I and Bukka Raya I', 'Krishnadevaraya and Achyuta Raya', 'Rama Raya and Tirumala', 'Saluva Narasimha and Vira Narasimha'],
    correctAnswerIndex: 0,
    explanation: 'Harihara and Bukka, originally commanders in the service of Kampili and Kakatiyas, established the Sangama dynasty in 1336 with the blessings of sage Vidyaranya.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Krishnadevaraya, the greatest emperor of Vijayanagara, composed the renowned administrative and political treatise "Amuktamalyada" in which language?',
    options: ['Kannada', 'Telugu', 'Sanskrit', 'Tamil'],
    correctAnswerIndex: 1,
    explanation: 'Krishnadevaraya authored Amuktamalyada in Telugu, elaborating the marriage of Andal and Lord Ranganatha alongside deep statecraft guidelines for monarchies.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The disastrous Battle of Talikota (Rakshasi-Tangadi) in 1565 led to the sack and ruin of which imperial capital?',
    options: ['Hampi (Vijayanagara)', 'Golconda', 'Bidar', 'Warangal'],
    correctAnswerIndex: 0,
    explanation: 'A combined confederacy of the Deccan Sultanates (Bijapur, Golconda, Ahmadnagar, Bidar) crushed the Vijayanagara army led by Rama Raya at Talikota in January 1565, devastating the city of Hampi.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Bhakti saint and poet popularized the devotional singing of "Kirtana" and initiated the Gaudiya Vaishnavism tradition in Eastern India?',
    options: ['Chaitanya Mahaprabhu', 'Ramananda', 'Kabir', 'Vallabhacharya'],
    correctAnswerIndex: 0,
    explanation: 'Chaitanya Mahaprabhu (1486–1534) from Nabadwip, Bengal, spearheaded Gaudiya Vaishnavism through communal congregational chanting (Sankirtana) and unconditioned love for Radha-Krishna.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Who was the preceptor (Guru) of Chhatrapati Shivaji Maharaj who composed the spiritual and practical guide "Dasbodh"?',
    options: ['Sant Tukaram', 'Samarth Ramdas', 'Sant Eknath', 'Sant Jnaneshwar'],
    correctAnswerIndex: 1,
    explanation: 'Samarth Ramdas was a prominent 17th-century Marathi saint and spiritual advisor to Shivaji Maharaj who authored Dasbodh and Manache Shlok to awaken Hindu cultural fortitude.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'In the Maratha administrative council known as the "Ashtapradhan", what was the designation of the Prime Minister?',
    options: ['Peshwa (Mukhya Pradhan)', 'Amatya', 'Senapati', 'Sumant'],
    correctAnswerIndex: 0,
    explanation: 'In Shivaji’s Ashtapradhan, the Peshwa held premier civil and military authority as Prime Minister, overseeing general administration under the Chhatrapati.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'What was "Chauth" levied by the Marathas across neighboring territories in the 17th and 18th centuries?',
    options: [
      'One-fourth of assessed land revenue paid to protect from Maratha raids',
      'One-tenth hereditary cess levied on local Deshmukhs',
      'Customs tax on river crossings',
      'Religious tax on pilgrim caravans',
    ],
    correctAnswerIndex: 0,
    explanation: 'Chauth was an assessment of 25% (one-fourth) of gross produce or revenue exacted from non-Maratha territories in return for military protection and immunity from Maratha raids.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Who composed the immortal Sufi poetic masterpiece "Padmavat" in Awadhi during the reign of Sher Shah Suri?',
    options: ['Amir Khusrau', 'Malik Muhammad Jayasi', 'Abul Fazl', 'Mulla Daud'],
    correctAnswerIndex: 1,
    explanation: 'Malik Muhammad Jayasi composed Padmavat in 1540 CE in Awadhi, allegorizing the historical siege of Chittor by Alauddin Khalji and Queen Padmini’s jauhar.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The Chishti Sufi saint Khwaja Moinuddin Chishti established his Khanqah at which historic city in India?',
    options: ['Ajmer', 'Delhi', 'Nagaur', 'Fatehpur Sikri'],
    correctAnswerIndex: 0,
    explanation: 'Khwaja Moinuddin Chishti arrived in India in the late 12th century and founded the premier Chishti Sufi order at Ajmer, Rajasthan, where his Dargah Sharif attracts millions of pilgrims.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Persian chronicler accompanied Sultan Mahmud of Ghazni to India and authored the comprehensive scientific compendium "Kitab-ul-Hind"?',
    options: ['Al-Biruni', 'Firdausi', 'Utbi', 'Minhaj-i-Siraj'],
    correctAnswerIndex: 0,
    explanation: 'Al-Biruni spent years studying Sanskrit texts, Indian mathematics, astronomy, and religion, compiling his encyclopedic masterpiece Kitab-ul-Hind (Tarikh al-Hind) around 1030 CE.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The Chola naval expedition against the Srivijaya Kingdom (modern Sumatra and Malay Peninsula) in 1025 CE was executed under which Chola monarch?',
    options: ['Rajaraja I', 'Rajendra I', 'Rajadhiraja', 'Kulothunga I'],
    correctAnswerIndex: 1,
    explanation: 'Rajendra Chola I (reigned 1014–1044 CE) deployed a powerful armada across the Bay of Bengal, successfully subduing King Sangrama Vijayottungavarman of the Srivijaya Empire and securing maritime trade lanes.',
    difficulty: 'Hard',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The famous bronze statue of "Nataraja" (Shiva as the cosmic cosmic dancer) is an artistic triumph of which southern dynasty?',
    options: ['Pallavas', 'Cholas', 'Rashtrakutas', 'Hoysalas'],
    correctAnswerIndex: 1,
    explanation: 'The lost-wax cast bronze Nataraja sculptures reached their pinnacle of aesthetic and technical perfection under the imperial Cholas from the 10th to 12th centuries.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Sultan of Delhi transferred the capital from Delhi to Deogiri (renamed Daulatabad) in 1327 and later ordered the reverse march?',
    options: ['Alauddin Khalji', 'Ghiyasuddin Tughlaq', 'Muhammad bin Tughlaq', 'Firoz Shah Tughlaq'],
    correctAnswerIndex: 2,
    explanation: 'Muhammad bin Tughlaq ordered the entire imperial court and population to relocate 1,500 km south to Daulatabad to command the Deccan, but logistical collapse and vulnerability in the north forced him to revoke it.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The "Diwan-i-Khairot" (Department of Charity) and "Dar-ul-Shifa" (Free Charitable Hospital) in Delhi were established by:',
    options: ['Alauddin Khalji', 'Balban', 'Firoz Shah Tughlaq', 'Sikandar Lodi'],
    correctAnswerIndex: 2,
    explanation: 'Firoz Shah Tughlaq undertook widespread welfare initiatives including Diwan-i-Khairat (for financial aid to poor Muslims/orphans), Dar-ul-Shifa (charitable hospital), and Diwan-i-Bandagan (department for slaves).',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'In Mughal architecture, the decorative technique of inlaying cut and polished colored stones into white marble is known as:',
    options: ['Pietra Dura', 'Arabesque', 'Minaret', 'Muqarnas'],
    correctAnswerIndex: 0,
    explanation: 'Pietra Dura (Parchin Kari) was prominently used in the Tomb of Itimad-ud-Daulah and reached its peak in the Taj Mahal under Shah Jahan.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'Which Guru of the Sikhs was executed at Delhi in 1675 under the orders of Mughal Emperor Aurangzeb for defending Kashmiri Pandits?',
    options: ['Guru Arjan Dev', 'Guru Har Gobind', 'Guru Tegh Bahadur', 'Guru Gobind Singh'],
    correctAnswerIndex: 2,
    explanation: 'Ninth Sikh Guru, Guru Tegh Bahadur, was publicly martyred at Chandni Chowk, Delhi, on November 11, 1675, for defending religious freedom. Gurdwara Sis Ganj Sahib marks the site of his supreme sacrifice.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'medieval-india',
    questionText: 'The Third Battle of Panipat was fought on January 14, 1761, between Ahmad Shah Abdali and:',
    options: ['The Mughals', 'The Marathas led by Sadashivrao Bhau', 'The Rajputs', 'The Sikhs'],
    correctAnswerIndex: 1,
    explanation: 'Afghan invader Ahmad Shah Durrani (Abdali), allied with Najib-ud-Daula of Rohilkhand and the Nawab of Awadh, dealt a crippling defeat to the Maratha confederacy under Sadashivrao Bhau and Vishwasrao.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },

  // --- MODERN INDIA (30 Questions) ---
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'In which year was the Battle of Plassey fought, laying the foundation of British political dominance in Bengal?',
    options: ['1757', '1764', '1761', '1773'],
    correctAnswerIndex: 0,
    explanation: 'On June 23, 1757, Robert Clive defeated Nawab Siraj-ud-Daulah of Bengal at Palashi due to the treason of Mir Jafar, establishing British hegemony over Bengal’s revenue.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The decisive Battle of Buxar (1764) was won by the British East India Company under the command of:',
    options: ['Robert Clive', 'Hector Munro', 'Warren Hastings', 'Eyre Coote'],
    correctAnswerIndex: 1,
    explanation: 'Major Hector Munro led the British troops to a crushing victory at Buxar on October 22, 1764, against the combined forces of Mir Qasim (Bengal), Shuja-ud-Daulah (Awadh), and Mughal Emperor Shah Alam II.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'By which treaty did the Mughal Emperor Shah Alam II grant the Diwani rights of Bengal, Bihar, and Orissa to the British East India Company?',
    options: ['Treaty of Alinagar (1757)', 'Treaty of Allahabad (1765)', 'Treaty of Purandar (1776)', 'Treaty of Salbai (1782)'],
    correctAnswerIndex: 1,
    explanation: 'Following the Battle of Buxar, Robert Clive concluded the Treaty of Allahabad in August 1765 with Shah Alam II, securing lawful rights to collect land revenues across Bengal, Bihar, and Orissa in exchange for an annual tribute of 26 lakh rupees.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who introduced the "Permanent Settlement" (Sthayi Bandobast) in Bengal, Bihar, and Orissa in 1793?',
    options: ['Warren Hastings', 'Lord Cornwallis', 'Lord Wellesley', 'Sir John Shore'],
    correctAnswerIndex: 1,
    explanation: 'Governor-General Lord Cornwallis, planned with Sir John Shore, implemented the Permanent Settlement in 1793, making zamindars hereditary owners of land with fixed annual revenue dues payable to the government.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Which Indian princely state was the first to accept the "Subsidiary Alliance" system devised by Lord Wellesley in 1798?',
    options: ['Awadh', 'Hyderabad (The Nizam)', 'Mysore', 'Tanjore'],
    correctAnswerIndex: 1,
    explanation: 'The Nizam of Hyderabad was the first Indian ruler to enter into Lord Wellesley’s Subsidiary Alliance in September 1798, disbanding his French-trained battalions and stationing British subsidiary troops.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Under the Doctrine of Lapse introduced by Lord Dalhousie, which princely state was annexed first in 1848?',
    options: ['Satara', 'Jhansi', 'Nagpur', 'Sambalpur'],
    correctAnswerIndex: 0,
    explanation: 'Satara was the first Indian state annexed under Dalhousie’s Doctrine of Lapse in 1848 when Raja Appa Sahib died without a natural male heir.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Mangal Pandey mutinied and fired at British officers on March 29, 1857, at which military cantonment?',
    options: ['Meerut', 'Barrackpore', 'Berhampore', 'Danapur'],
    correctAnswerIndex: 1,
    explanation: 'Sepoy Mangal Pandey of the 34th Bengal Native Infantry mutinied on the parade ground of Barrackpore cantonment against the Enfield rifle greased cartridges.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who was the celebrated leader of the 1857 Revolt in Bihar and Jagdishpur who fought valiantly despite an advanced age of nearly 80 years?',
    options: ['Kunwar Singh', 'Amar Singh', 'Pir Ali Khan', 'Hare Krishna Singh'],
    correctAnswerIndex: 0,
    explanation: 'Veer Kunwar Singh, the zamindar of Jagdishpur (Bhojpur district, Bihar), masterminded gorilla campaigns across Bihar and eastern Uttar Pradesh, repeatedly routing British commanders before his martyrdom in April 1858.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who founded the "Brahmo Samaj" in Calcutta in 1828 to propagate monotheism and eradicate social evils like Sati?',
    options: ['Ishwar Chandra Vidyasagar', 'Raja Ram Mohan Roy', 'Debendranath Tagore', 'Keshab Chandra Sen'],
    correctAnswerIndex: 1,
    explanation: 'Raja Ram Mohan Roy, known as the "Father of Modern Indian Renaissance", established the Brahmo Samaj in 1828 and successfully campaigned for the abolition of Sati (enacted under Regulation XVII in 1829 by Lord William Bentinck).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who authored the landmark book "Poverty and Un-British Rule in India" (1901) that formulated the "Drain of Wealth" theory?',
    options: ['Romesh Chunder Dutt', 'Dadabhai Naoroji', 'Gopal Krishna Gokhale', 'Mahadev Govind Ranade'],
    correctAnswerIndex: 1,
    explanation: 'Dadabhai Naoroji, the "Grand Old Man of India", demonstrated through statistical evidence how British colonial extraction drained India’s national capital through home charges, unrequited exports, and foreign pensions.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The First Session of the Indian National Congress in December 1885 was held at Bombay under the presidency of:',
    options: ['Surendranath Banerjee', 'W. C. Bonnerjee', 'Dadabhai Naoroji', 'Allan Octavian Hume'],
    correctAnswerIndex: 1,
    explanation: 'Womesh Chandra Bonnerjee presided over the founding session of the INC held at Gokuldas Tejpal Sanskrit College in Bombay, attended by 72 delegates from across India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who announced the Partition of Bengal in July 1905, which sparked the nationwide Swadeshi and Boycott Movement?',
    options: ['Lord Minto', 'Lord Curzon', 'Lord Hardinge', 'Lord Elgin II'],
    correctAnswerIndex: 1,
    explanation: 'Viceroy Lord Curzon promulgated the partition of Bengal on administrative grounds on October 16, 1905, intending to create a communal wedge between eastern Muslim-majority and western Hindu-majority districts.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'In which session of the Indian National Congress in 1907 did the historic split between the Moderates and Extremists take place?',
    options: ['Calcutta Session', 'Surat Session', 'Madras Session', 'Lahore Session'],
    correctAnswerIndex: 1,
    explanation: 'The Surat Split occurred at the 1907 session presided over by Rash Behari Ghosh on the banks of the Tapti River over leadership and extending the Swadeshi boycott outside Bengal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The Champaran Satyagraha of 1917, Mahatma Gandhi’s first civil disobedience movement in India, was organized against the oppressive:',
    options: ['Tinkathia System in indigo cultivation', 'Salt monopoly tax', 'Chaukidari tax', 'Landed zamindari cesses'],
    correctAnswerIndex: 0,
    explanation: 'Raj Kumar Shukla persuaded Gandhi to visit Champaran (Bihar), where tenant farmers were compelled under the Tinkathia system to cultivate indigo on 3/20th of their best landholdings for British planters.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The tragic Jallianwala Bagh massacre occurred on April 13, 1919, in Amritsar under the military command of:',
    options: ['General Reginald Dyer', 'Michael O’Dwyer', 'Lord Chelmsford', 'John Saunders'],
    correctAnswerIndex: 0,
    explanation: 'Brigadier-General Reginald Dyer ordered unprovoked firing upon an unarmed gathering observing Baisakhi and protesting the arrest of Dr. Saifuddin Kitchlew and Dr. Satyapal.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Mahatma Gandhi abruptly suspended the Non-Cooperation Movement in February 1922 because of the violent incident at:',
    options: ['Kakori', 'Chauri Chaura', 'Bardoli', 'Kheda'],
    correctAnswerIndex: 1,
    explanation: 'On February 4, 1922, protestors in Chauri Chaura (Gorakhpur, UP) clashed with police and set the police post ablaze, killing 22 policemen, prompting Gandhi to call off the movement.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who founded the "Swaraj Party" in January 1923 within the Congress to participate in legislative councils and wreck colonial policies from within?',
    options: [
      'Motilal Nehru and Chittaranjan Das',
      'Jawaharlal Nehru and Subhash Chandra Bose',
      'Vallabhbhai Patel and Rajendra Prasad',
      'Lala Lajpat Rai and Bipin Chandra Pal',
    ],
    correctAnswerIndex: 0,
    explanation: 'C. R. Das (President) and Motilal Nehru (Secretary) formed the Congress-Khilafat Swaraj Party following the Gaya Congress of 1922 to contest provincial elections.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The Indian National Congress passed the historic "Purna Swaraj" (Complete Independence) resolution in 1929 at which session?',
    options: ['Karachi Session', 'Lahore Session', 'Madras Session', 'Belgaum Session'],
    correctAnswerIndex: 1,
    explanation: 'The Lahore Session of December 1929, presided over by Jawaharlal Nehru on the banks of the Ravi, adopted Purna Swaraj as the sole national objective and declared January 26, 1930, as Independence Day.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Mahatma Gandhi commenced his 240-mile Dandi March from Sabarmati Ashram to break the salt law on which date in 1930?',
    options: ['March 12, 1930', 'April 6, 1930', 'January 26, 1930', 'May 5, 1930'],
    correctAnswerIndex: 0,
    explanation: 'Gandhi set off from Sabarmati on March 12, 1930, with 78 chosen satyagrahis and reached the coastal village of Dandi on April 5, ceremonially manufacturing salt on the morning of April 6 to launch the Civil Disobedience Movement.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Mahatma Gandhi attended only which of the following Round Table Conferences held in London?',
    options: ['First Round Table Conference (1930)', 'Second Round Table Conference (1931)', 'Third Round Table Conference (1932)', 'None of them'],
    correctAnswerIndex: 1,
    explanation: 'Pursuant to the Gandhi-Irwin Pact of March 1931, Mahatma Gandhi sailed to London as the sole representative of the Indian National Congress to participate in the Second Round Table Conference.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The "Poona Pact" of September 1932 was signed between Dr. B. R. Ambedkar and representatives of Mahatma Gandhi to replace:',
    options: [
      'The Communal Award’s separate electorates with reserved seats for Depressed Classes',
      'The Simon Commission’s dual franchise formula',
      'The Rowlatt Acts',
      'The Cripps Offer',
    ],
    correctAnswerIndex: 0,
    explanation: 'Following Gandhi’s fast-unto-death in Yerwada Jail against Ramsay MacDonald’s Communal Award, the Poona Pact retained joint electorates while almost doubling reserved legislative seats for the Depressed Classes from 71 to 148 in provincial assemblies.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who was the only Indian woman to preside over a session of the Indian National Congress before independence?',
    options: ['Annie Besant', 'Sarojini Naidu', 'Nellie Sengupta', 'Sucheta Kripalani'],
    correctAnswerIndex: 1,
    explanation: 'Sarojini Naidu presided over the 1925 Kanpur Session of the INC, becoming the first Indian woman president (Annie Besant in 1917 was the first woman, but British).',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Netaji Subhash Chandra Bose was elected President of the INC at the Tripuri Session in 1939 by defeating which candidate backed by Mahatma Gandhi?',
    options: ['Pattabhi Sitaramayya', 'Abul Kalam Azad', 'Jawaharlal Nehru', 'C. Rajagopalachari'],
    correctAnswerIndex: 0,
    explanation: 'Subhash Chandra Bose defeated Dr. Pattabhi Sitaramayya by 1,580 to 1,377 votes at the 52nd session in Tripuri (Jabalpur), after which Gandhi magnanimously stated that "Sitaramayya’s defeat is more mine than his".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Subhash Chandra Bose established the "Provisional Government of Free India" (Arzi Hukumat-e-Azad Hind) in October 1943 at:',
    options: ['Tokyo', 'Singapore', 'Rangoon', 'Bangkok'],
    correctAnswerIndex: 1,
    explanation: 'Netaji proclaimed the Arzi Hukumat-e-Azad Hind on October 21, 1943, at the Cathay Cinema hall in Singapore with the famous rallying cry "Give me blood, and I shall give you freedom!"',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The "Do or Die" (Karo ya Maro) slogan was given by Mahatma Gandhi during which freedom struggle movement?',
    options: ['Non-Cooperation Movement (1920)', 'Civil Disobedience Movement (1930)', 'Quit India Movement (1942)', 'Anti-Rowlatt Satyagraha (1919)'],
    correctAnswerIndex: 2,
    explanation: 'Gandhi delivered his historic "Do or Die" address on August 8, 1942, at the Gowalia Tank Maidan (August Kranti Maidan) in Bombay while launching the Quit India Movement.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who operated an underground secret radio transmitter called "Congress Radio" to broadcast national messages during the Quit India Movement?',
    options: ['Aruna Asaf Ali', 'Usha Mehta', 'Kalpana Datta', 'Matangini Hazra'],
    correctAnswerIndex: 1,
    explanation: 'Usha Mehta and her associates set up the clandestine Congress Radio at 42.34 meters from Bombay, broadcasting patriotic news and Gandhi’s messages until her arrest in November 1942.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The Cabinet Mission arrived in India in March 1946. Who among the following was NOT a member of the Cabinet Mission?',
    options: ['Lord Pethick-Lawrence', 'Sir Stafford Cripps', 'A. V. Alexander', 'Lord Wavell'],
    correctAnswerIndex: 3,
    explanation: 'The three-member Cabinet Mission sent by British PM Clement Attlee consisted of Lord Pethick-Lawrence (Secretary of State), Sir Stafford Cripps (President of the Board of Trade), and A. V. Alexander (First Lord of the Admiralty). Lord Wavell was the Viceroy.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The Royal Indian Navy (RIN) Mutiny, which shook British military confidence on the eve of independence, began on February 18, 1946, aboard which ship?',
    options: ['HMIS Talwar', 'HMIS Bengal', 'HMIS Vikrant', 'HMIS Shivaji'],
    correctAnswerIndex: 0,
    explanation: 'Naval ratings on the signals training ship HMIS Talwar in Bombay harbor struck work over racial discrimination, substandard food, and the arrest of B. C. Dutt for writing patriotic graffiti.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'The Mountbatten Plan announcing the partition of British India and the transfer of power on August 15, 1947, was unveiled on:',
    options: ['June 3, 1947', 'July 18, 1947', 'March 24, 1947', 'August 8, 1947'],
    correctAnswerIndex: 0,
    explanation: 'Lord Mountbatten announced his plan on June 3, 1947 (the 3rd June Plan), outlining procedures for the partition of Punjab, Bengal, and Sindh and early transfer of dominion status to India and Pakistan.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-history',
    topicSlug: 'modern-india',
    questionText: 'Who was appointed the Chairman of the Boundary Commissions responsible for drawing the borders between India and Pakistan in Punjab and Bengal?',
    options: ['Sir Cyril Radcliffe', 'Sir Stafford Cripps', 'Sir Maurice Gwyer', 'Lord Curzon'],
    correctAnswerIndex: 0,
    explanation: 'British lawyer Sir Cyril Radcliffe chaired both Boundary Commissions, demarcating the Radcliffe Line under severe time constraints before the announcement on August 17, 1947.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
];
