import { JPSCQuestionRaw } from './types';

export const jharkhandQuestions: JPSCQuestionRaw[] = [
  // --- JHARKHAND HISTORY, HERITAGE & CULTURE (25 Questions) ---
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The ancient region of modern Jharkhand is mentioned in the Aitareya Brahmana (c. 8th-7th century BCE) under which name?',
    options: ['Pundra (or Punda)', 'Kikata', 'Murand', 'Mundal'],
    correctAnswerIndex: 0,
    explanation: 'In the Vedic text Aitareya Brahmana, the forested region encompassing modern Jharkhand and its indigenous tribal inhabitants was referred to as "Pundra" or "Punda".',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'In the Allahabad Pillar Inscription of Samudragupta (Prayag Prashasti), what name was assigned to the forest kingdom region of Jharkhand?',
    options: ['Murund Desha', 'Kukkar Desha', 'Al-Atavika', 'Pundravardhana'],
    correctAnswerIndex: 0,
    explanation: 'Harishena’s Prayag Prashasti describes Samudragupta subjugating the rulers of forest kingdoms ("Atavika Rajyas"), explicitly designating the Chota Nagpur forested territory as "Murund Desha".',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'During the Mughal period (under Akbar and Jahangir), the Jharkhand territory was officially designated in imperial chronicles like Ain-i-Akbari as:',
    options: ['Kokrah (or Khokhra)', 'Jungle Mahal', 'Jharkhanda', 'Damin-i-Koh'],
    correctAnswerIndex: 0,
    explanation: 'Abul Fazl in Ain-i-Akbari and Jahangir in Tuzuk-i-Jahangiri referred to the Chota Nagpur plateau as Kokrah (or Khokhra), known for its placer diamonds found along the riverbeds of the Sankh.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Who was the founder of the ancient Nagvanshi dynasty of Chota Nagpur in 64 CE (1st century CE)?',
    options: ['Phani Mukut Rai', 'Madra Munda', 'Bhim Karn', 'Durjan Sal'],
    correctAnswerIndex: 0,
    explanation: 'According to regional chronicles, Phani Mukut Rai, brought up by Madra Munda, was chosen as the first Maharaja of the Nagvanshi dynasty at Sutiambe in 64 CE.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Which Nagvanshi king was imprisoned by Mughal Emperor Jahangir for 12 years in Gwalior Fort for failing to pay revenue, and later released due to his uncanny expertise in testing diamonds?',
    options: ['Durjan Sal', 'Bhim Karn', 'Raghunath Shah', 'Ani Nath Shahdeo'],
    correctAnswerIndex: 0,
    explanation: 'Durjan Sal was captured in 1615 by Ibrahim Khan and incarcerated in Gwalior Fort. In 1627, he correctly identified a flawless diamond when royal jewelers were baffled, earning his freedom and the title of "Shah".',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Which Chero ruler of Palamu built the famous "New Fort" (Naya Qila) of Palamu during the reign of Aurangzeb?',
    options: ['Medini Ray', 'Pratap Ray', 'Anant Ray', 'Bhagwant Ray'],
    correctAnswerIndex: 0,
    explanation: 'Medini Ray (1658–1674), known as the "Bapji" of Palamu, built the New Palamu Fort featuring the monumental Nagpuri Gate made of finely carved stone.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Who was the first tribal freedom fighter of Jharkhand who led the rebellion against British rule in Rajmahal and killed the British magistrate Augustus Cleveland with a poisoned arrow in 1784?',
    options: ['Baba Tilka Manjhi', 'Birsa Munda', 'Sidho Murmu', 'Budhu Bhagat'],
    correctAnswerIndex: 0,
    explanation: 'Baba Tilka Manjhi (Jabrah Paharia) organized tribal guerrillas against East India Company exploitation, shot Cleveland on January 13, 1784, and was martyred by being hung from a banyan tree at Bhagalpur in 1785.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The historic "Kol Uprising" (Kol Mutiny) of 1831–1832 in Chota Nagpur was spearheaded by which hero of Silagai?',
    options: ['Budhu Bhagat (along with Singrai and Bindrai Manki)', 'Birsa Munda', 'Ganga Narayan Singh', 'Telanga Kharia'],
    correctAnswerIndex: 0,
    explanation: 'The Kol Rebellion of 1831–32 broke out when Oraon and Munda Mankis and Mundas resisted dispossession by outsider Thikadars, led valiantly by Budhu Bhagat of Silagai who sacrificed his life fighting Captain Impey.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The historic "Santhal Hul" (Santhal Rebellion) was proclaimed on June 30, 1855, at which sacred assembly ground in Santhal Parganas?',
    options: ['Bhagnadih (near Barhait)', 'Panchkathia', 'Sahebganj', 'Dumka'],
    correctAnswerIndex: 0,
    explanation: 'Over 10,000 Santhals gathered at Bhagnadih on June 30, 1855, where brothers Sidho, Kanho, Chand, and Bhairav Murmu proclaimed open armed insurrection against British rule and moneylenders (Mahajans).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Bhagwan Birsa Munda proclaimed his divine leadership and launched the great "Munda Ulgulan" (The Great Tumult) in which year?',
    options: ['1895', '1885', '1905', '1875'],
    correctAnswerIndex: 0,
    explanation: 'In 1895, 20-year-old Birsa Munda of Ulihatu proclaimed himself as the messenger of Singbonga (Dharati Aaba), rallying the Munda tribe to drive away British colonizers and Dikus and establish Birsa Raj.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'On which tragic date did Bhagwan Birsa Munda achieve martyrdom while imprisoned in Ranchi Jail?',
    options: ['June 9, 1900', 'November 15, 1900', 'August 15, 1899', 'January 26, 1901'],
    correctAnswerIndex: 0,
    explanation: 'Birsa Munda died mysteriously of cholera in Ranchi District Jail on June 9, 1900, at the young age of 25.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The "Tana Bhagat Movement" began in April 1914 in Gumla under the spiritual and political leadership of:',
    options: ['Jatra Bhagat (Jatra Oraon)', 'Sibu Bhagat', 'Budhu Bhagat', 'Balram Bhagat'],
    correctAnswerIndex: 0,
    explanation: 'Jatra Oraon initiated the Tana Bhagat movement in 1914 among the Oraon tribe, advocating vegetarianism, abstinence, non-violence, and later enthusiastically joining Mahatma Gandhi’s Non-Cooperation movement.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Who founded the "Adivasi Mahasabha" in 1938 and later transformed it into the "Jharkhand Party" in 1950, campaigning for a separate Jharkhand state?',
    options: ['Jaipal Singh Munda', 'Theodore Surin', 'Kartik Oraon', 'Julius Tigga'],
    correctAnswerIndex: 0,
    explanation: 'Oxford-educated Olympian Jaipal Singh Munda led the Adivasi Mahasabha and founded the Jharkhand Party in January 1950 at Jamshedpur, spearheading the political demand for an autonomous tribal state.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Under whose leadership did the Indian field hockey team win its historic first Olympic Gold Medal at the 1928 Amsterdam Olympic Games?',
    options: ['Jaipal Singh Munda (Captain)', 'Dhyan Chand', 'Richard Allen', 'Eric Pinniger'],
    correctAnswerIndex: 0,
    explanation: 'Jaipal Singh Munda captained the victorious Indian Olympic hockey team at the 1928 Amsterdam Games, winning India’s first ever Olympic gold without conceding a single goal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The "Sarhul" festival, the most important spring festival celebrated across Jharkhand by tribes like Oraon, Munda, and Ho, is centered around the worship of which tree?',
    options: ['Sal tree (Shorea robusta)', 'Mahua tree', 'Karam tree', 'Peepal tree'],
    correctAnswerIndex: 0,
    explanation: 'Sarhul (literally the worship of the Sal tree flower) is observed in the Chaitra month when Sal trees burst into blossom, celebrating the marriage of the Earth with the Sun at the Sarna sthal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The traditional "Karma" festival of Jharkhand celebrated on Bhadra Shukla Ekadashi is celebrated primarily for:',
    options: ['Sisters praying for the long life, prosperity, and valor of their brothers', 'Welcoming the summer harvest', 'Mourning the ancestors', 'Appeasing the river spirits'],
    correctAnswerIndex: 0,
    explanation: 'During Karam (Karma) festival, tribal youth plant branches of the sacred Karam tree in the Akhra, and sisters fast (Jawa fasting) to pray for the well-being and prosperity of their brothers.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Which traditional mural and scroll painting art style of Hazaribagh was granted the prestigious Geographical Indication (GI) tag in 2020?',
    options: ['Sohrai and Khovar Painting', 'Paitkar Painting', 'Jadopatia Painting', 'Madhubani Painting'],
    correctAnswerIndex: 0,
    explanation: 'Sohrai (harvest art) and Khovar (bridal chamber art) of Hazaribagh, practiced by tribal women using natural ochre and clay pigments, were conferred GI tag status in May 2020.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: '"Paitkar" painting, regarded as one of the oldest folk scroll painting traditions in India practiced by the Chitrakar community, belongs to which district of Jharkhand?',
    options: ['East Singhbhum (Amadubi village)', 'Dumka', 'Ranchi', 'Palamu'],
    correctAnswerIndex: 0,
    explanation: 'Amadubi village (known as the Village of Paitkar Painters) in Dhalbhumgarh block of East Singhbhum is renowned for Paitkar scroll paintings depicting Santhal epics and life after death.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The world-famous "Seraikella Chhau" dance of Jharkhand, which received UNESCO Intangible Cultural Heritage recognition in 2010, is distinctively known for:',
    options: ['Elaborate handcrafted papier-mache facial masks depicting mythological gods and emotions', 'Absence of musical accompaniment', 'Pure vocal chanting without footwork', 'Exclusively female performers'],
    correctAnswerIndex: 0,
    explanation: 'Seraikella Chhau is a classical martial dance where performers wear delicately painted symbolic masks crafted by traditional artisans in Seraikella to portray divine and heroic motifs.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'What is "Dhumkuria" in traditional Oraon tribal society?',
    options: ['A traditional youth dormitory (bachelors’ hall) for educating and socializing youth in tribal customs', 'The village council court', 'A granary for festival grains', 'A sacred grove for deities'],
    correctAnswerIndex: 0,
    explanation: 'Dhumkuria is the traditional social institution and dormitory of the Oraons (Jonkh-Erpa for boys, Pelo-Erpa for girls) that served as an indigenous cultural and vocational academy.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'In Munda tribal custom, what is "Sasandiri"?',
    options: ['Large stone slabs placed over burial vaults of clan members where bones are interred', 'A tribal marriage ceremony', 'A sacred musical horn', 'A wooden agricultural plough'],
    correctAnswerIndex: 0,
    explanation: 'Sasandiri are megalithic memorial burial stone slabs placed in the clan cemetery (Sasan) during the annual bone-interment ceremony (Jang-topa), establishing hereditary clan landholding rights.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Who invented the "Ol Chiki" script for writing the Santhali language in 1925?',
    options: ['Pandit Raghunath Murmu', 'Lako Bodra', 'Ramdayal Munda', 'Dobar Ho'],
    correctAnswerIndex: 0,
    explanation: 'Pandit Raghunath Murmu created the indigenous 30-letter phonetic Ol Chiki script in 1925 to preserve and advance Santhali language and literature.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'In which year was the Santhali language included in the Eighth Schedule of the Constitution of India via the 92nd Constitutional Amendment Act?',
    options: ['2003', '2000', '2008', '1992'],
    correctAnswerIndex: 0,
    explanation: 'The 92nd Constitutional Amendment Act of 2003 added Santhali, Bodo, Dogri, and Maithili to the Eighth Schedule of the Constitution.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'Who authored the authoritative ethnographic study "The Mundas and Their Country" published in 1912?',
    options: ['Sarat Chandra Roy (S.C. Roy)', 'Verrier Elwin', 'L. P. Vidyarthi', 'Father John Baptist Hoffmann'],
    correctAnswerIndex: 0,
    explanation: 'Sarat Chandra Roy, recognized as the "Father of Indian Anthropology", documented the culture, origin myths, and legal customary rights of the Mundas in his 1912 classic.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-history-culture',
    questionText: 'The encyclopedic monumental work "Encyclopaedia Mundarica" running into 16 volumes was compiled by which Jesuit scholar?',
    options: ['Father John Baptist Hoffmann (assisted by Menas Orea)', 'Father Constant Lievens', 'Father Camille Bulcke', 'Father De Smet'],
    correctAnswerIndex: 0,
    explanation: 'Father J.B. Hoffmann devoted decades to documenting the Munda language, customs, social structures, and flora, authoring the monumental Encyclopaedia Mundarica and helping draft the CNT Act 1908.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },

  // --- JHARKHAND GEOGRAPHY & NATURAL RESOURCES (20 Questions) ---
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'What is the total geographical area of the State of Jharkhand?',
    options: ['79,714 sq km', '85,420 sq km', '72,110 sq km', '91,200 sq km'],
    correctAnswerIndex: 0,
    explanation: 'The total geographical area of Jharkhand is 79,714 square kilometers, representing approximately 2.42% of the total land area of India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Which is the highest mountain peak in Jharkhand, with an elevation of 1,365 meters (4,478 ft)?',
    options: ['Parasnath Peak (Sammed Shikhar)', 'Netarhat Hill', 'Tagore Hill', 'Trikut Hill'],
    correctAnswerIndex: 0,
    explanation: 'Parasnath Hill in Giridih district is the highest point of the state at 1,365 meters, sacred as the nirvana site of 20 Jain Tirthankaras.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The flat-topped bauxite-bearing plateaus of Netarhat and Latehar in western Jharkhand are locally called:',
    options: ['Pat regions (Patks)', 'Dons', 'Tands', 'Bhabhars'],
    correctAnswerIndex: 0,
    explanation: 'The western elevated flat-topped tablelands of Jharkhand (Netarhat, Jamira, Bagru) elevated over 900–1,100 meters above sea level are geographically designated as the Pat Region.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Which river in Jharkhand originates from the Nagri village near Ranchi and flows independently into the Bay of Bengal without joining any other major river?',
    options: ['Subarnarekha', 'Damodar', 'Barakar', 'North Koel'],
    correctAnswerIndex: 0,
    explanation: 'Subarnarekha (streak of gold) originates at Nagri in Ranchi district and flows 470 km southeast across Jharkhand, West Bengal, and Odisha to empty directly into the Bay of Bengal near Kirtania.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The Hundru Falls (98 meters high), one of the most picturesque waterfalls in Jharkhand, is formed by which river?',
    options: ['Subarnarekha', 'Damodar', 'Sankh', 'Raru'],
    correctAnswerIndex: 0,
    explanation: 'The Subarnarekha River plunges 98 meters (320 ft) over a sheer granite knickpoint at Hundru, located approximately 45 km from Ranchi city.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Which is the highest waterfall in Jharkhand, having a drop of 143 meters (469 ft)?',
    options: ['Burha Ghagh (Lodh Falls) on the Burha river in Latehar', 'Hundru Falls', 'Jonha Falls', 'Dassam Falls'],
    correctAnswerIndex: 0,
    explanation: 'Lodh Falls (also called Burha Ghagh) in Latehar district on the Burha River (a tributary of North Koel) is the tallest waterfall in Jharkhand with a total drop of 143 meters.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The Damodar Valley Corporation (DVC), India’s first multipurpose river valley project modeled on the Tennessee Valley Authority (TVA), was established in which year?',
    options: ['July 7, 1948', 'January 26, 1950', 'August 15, 1947', 'October 2, 1952'],
    correctAnswerIndex: 0,
    explanation: 'DVC was created by an Act of the Constituent Assembly on July 7, 1948, constructing dams at Tilaiya, Konar, Maithon, and Panchet for flood control and hydroelectric power.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The Maithon Dam and Tilaiya Dam of the DVC were constructed across which river?',
    options: ['Barakar River', 'Damodar River', 'Konar River', 'Bokaro River'],
    correctAnswerIndex: 0,
    explanation: 'Tilaiya Dam (1953) and Maithon Dam (1957) were built across the Barakar River, the main tributary of the Damodar.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Which is the only National Park in the State of Jharkhand?',
    options: ['Betla National Park (Latehar district)', 'Dalma National Park', 'Hazaribagh National Park', 'Topchanchi National Park'],
    correctAnswerIndex: 0,
    explanation: 'Betla National Park in Latehar district, established in 1986, is the only officially notified National Park in Jharkhand and one of the pioneer sanctuaries of Project Tiger (1973).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Where in the world was the first systematic tiger census using pugmark tracking technology conducted in 1932?',
    options: ['Palamu Tiger Reserve (Jharkhand)', 'Corbett National Park', 'Ranthambore National Park', 'Bandipur National Park'],
    correctAnswerIndex: 0,
    explanation: 'The world’s first tiger census was conducted in the forests of Palamu in 1932 by J.W. Nicholson, Divisional Forest Officer, using the pugmark measurement method.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The Dalma Wildlife Sanctuary, located near Jamshedpur, is famous primarily as a protected habitat for:',
    options: ['Indian Asian Elephants', 'One-horned Rhinoceros', 'Ganges River Dolphins', 'Snow Leopards'],
    correctAnswerIndex: 0,
    explanation: 'Dalma Wildlife Sanctuary, inaugurated in 1975 on the Dalma mountain range, is renowned for its sizeable population of Asian wild elephants and migratory elephant corridors.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'According to the India State of Forest Report (ISFR) 2021, forest cover in Jharkhand accounts for what percentage of the state’s total geographical area?',
    options: ['29.76%', '26.50%', '33.33%', '24.16%'],
    correctAnswerIndex: 0,
    explanation: 'As per ISFR 2021, Jharkhand has a forest cover of 23,721 sq km, which constitutes 29.76% of the state’s total geographical territory.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Which district in Jharkhand has the highest percentage of forest cover according to ISFR 2021?',
    options: ['Latehar (56.08%)', 'Chatra', 'West Singhbhum', 'Kodarma'],
    correctAnswerIndex: 0,
    explanation: 'Latehar district has the highest proportion of forest cover in Jharkhand at 56.08%, while West Singhbhum has the largest absolute forest area in square kilometers.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Which district in Jharkhand has the lowest forest cover percentage as per ISFR 2021?',
    options: ['Jamtara (5.85%)', 'Deoghar', 'Dhanbad', 'Bokaro'],
    correctAnswerIndex: 0,
    explanation: 'Jamtara records the lowest forest cover in Jharkhand at only 5.85% (approx. 106 sq km), followed by Deoghar (8.31%).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The Saranda Forest in West Singhbhum, celebrated as the largest contiguous Sal (Shorea robusta) forest in Asia, is famously known as the:',
    options: ['Land of Seven Hundred Hills', 'Land of Red Minerals', 'Valley of Green Sal', 'The Hidden Wilderness'],
    correctAnswerIndex: 0,
    explanation: 'Saranda Forest covers an area of 820 sq km in West Singhbhum along the Odisha border and is poetically titled "The Land of Seven Hundred Hills".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'What type of soil is most widely distributed across the state of Jharkhand, covering more than 90% of its total geographical area?',
    options: ['Red Soil (Lal Mitti)', 'Black Cotton Soil', 'Laterite Soil', 'Alluvial Soil'],
    correctAnswerIndex: 0,
    explanation: 'Due to the weathering of ancient Archean granites and gneisses of the Chota Nagpur plateau, Red Soil covers over 90% of Jharkhand’s land area.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Black soil (Regur soil) in Jharkhand is specifically found in which geographical zone?',
    options: ['Rajmahal Traps (Sahibganj and Pakur)', 'Netarhat Pat', 'Singhbhum plain', 'Ranchi plateau'],
    correctAnswerIndex: 0,
    explanation: 'Black soil in Jharkhand is restricted to the Rajmahal Hills and Traps, formed by the weathering of basaltic volcanic lava flows.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Udhwa Lake Bird Sanctuary, the only designated bird sanctuary in Jharkhand where migratory birds from Siberia flock in winter, is situated in:',
    options: ['Sahibganj district', 'Pakur district', 'Deoghar district', 'Hazaribagh district'],
    correctAnswerIndex: 0,
    explanation: 'Udhwa Lake Bird Sanctuary covers two natural backwater lakes (Pataura and Berhale) on the Ganga floodplain in Sahibganj district.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'Netarhat, known as the "Queen of Chota Nagpur", famous for its sunrise and sunset viewpoints, is located in which district?',
    options: ['Latehar district', 'Gumla district', 'Lohardaga district', 'Simdega district'],
    correctAnswerIndex: 0,
    explanation: 'Netarhat hill station is situated at an altitude of 1,071 meters in Latehar district, renowned for its cool climate and the iconic Netarhat Residential School.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-geography-resources',
    questionText: 'The only district in Jharkhand that touches the River Ganga along its border is:',
    options: ['Sahibganj', 'Pakur', 'Godda', 'Deoghar'],
    correctAnswerIndex: 0,
    explanation: 'The River Ganga flows along the northern and eastern boundary of Sahibganj district for about 80 km before entering West Bengal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },

  // --- JHARKHAND GOVERNANCE, SCHEMES & ECONOMY (15 Questions) ---
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'On which auspicious date was the State of Jharkhand officially carved out of Bihar as the 28th State of the Indian Union?',
    options: ['November 15, 2000', 'November 1, 2000', 'November 9, 2000', 'August 15, 2000'],
    correctAnswerIndex: 0,
    explanation: 'Jharkhand was created on November 15, 2000 (the 125th birth anniversary of Bhagwan Birsa Munda) under the Bihar Reorganisation Act, 2000.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'Who was sworn in as the first Governor of the newly formed State of Jharkhand on November 15, 2000?',
    options: ['Prabhat Kumar', 'V. C. Pande', 'Ved Marwah', 'Syed Sibtey Razi'],
    correctAnswerIndex: 0,
    explanation: 'Prabhat Kumar (former Cabinet Secretary of India) served as the first Governor of Jharkhand from November 15, 2000, to February 3, 2002.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'Who took oath as the first Chief Minister of the State of Jharkhand in November 2000?',
    options: ['Babulal Marandi', 'Shibu Soren', 'Arjun Munda', 'Madhu Koda'],
    correctAnswerIndex: 0,
    explanation: 'Babulal Marandi was sworn in as the first Chief Minister of Jharkhand on November 15, 2000, heading an NDA coalition government.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'What is the total number of elective seats in the unicameral Jharkhand State Legislative Assembly (Jharkhand Vidhan Sabha)?',
    options: ['81 seats', '82 seats', '80 seats', '75 seats'],
    correctAnswerIndex: 0,
    explanation: 'The Jharkhand Vidhan Sabha consists of 81 directly elected members (the single nominated Anglo-Indian seat was discontinued under the 104th Constitutional Amendment Act).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'How many parliamentary constituencies (Lok Sabha seats) are allocated to the State of Jharkhand in the Parliament of India?',
    options: ['14 seats', '16 seats', '12 seats', '10 seats'],
    correctAnswerIndex: 0,
    explanation: 'Jharkhand is represented by 14 members in the Lok Sabha (5 reserved for STs, 1 for SC, and 8 unreserved) and 6 members in the Rajya Sabha.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'What is the State Animal of Jharkhand?',
    options: ['Asian Elephant (Elephas maximus)', 'Tiger', 'Wild Buffalo', 'Nilgai'],
    correctAnswerIndex: 0,
    explanation: 'The official State Animal of Jharkhand is the Asian Elephant (Elephas maximus), reflecting the state’s dense forests and prominent elephant habitats.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'What is the official State Flower of Jharkhand?',
    options: ['Palas (Butea monosperma)', 'Lotus', 'Marigold', 'Jasmine'],
    correctAnswerIndex: 0,
    explanation: 'The bright crimson flower of Palas (Butea monosperma, known as the "Flame of the Forest") is the official State Flower of Jharkhand.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'What is the official State Tree of Jharkhand?',
    options: ['Sal (Shorea robusta)', 'Teak', 'Banyan', 'Neem'],
    correctAnswerIndex: 0,
    explanation: 'The Sal tree (Shorea robusta), deeply intertwined with tribal culture and religion (Sarna sthal), is the official State Tree of Jharkhand.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'The High Court of Jharkhand at Ranchi, inaugurated on November 15, 2000, is which numbered High Court of India?',
    options: ['21st High Court', '18th High Court', '25th High Court', '20th High Court'],
    correctAnswerIndex: 0,
    explanation: 'The High Court of Jharkhand was established in Ranchi on November 15, 2000, as the 21st High Court of the country, with Justice V. K. Gupta as its first Chief Justice.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'The Tata Iron and Steel Company (TISCO, now Tata Steel) was established in 1907 by Jamsetji Tata at Sakchi (Jamshedpur) along the confluence of which two rivers?',
    options: ['Subarnarekha and Kharkai rivers', 'Damodar and Barakar', 'Ganga and Son', 'Brahmani and Koel'],
    correctAnswerIndex: 0,
    explanation: 'TISCO, India’s first integrated private iron and steel plant, was founded in 1907 at Sakchi (renamed Jamshedpur by Lord Chelmsford in 1919) at the confluence of Subarnarekha and Kharkai.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'Heavy Engineering Corporation (HEC) established in 1958 at Hatia, Ranchi, with Czechoslovakian and Soviet technical assistance, is known as:',
    options: ['Mother of Machines (Mother of all industries in India)', 'Heart of Steel', 'The Atomic Foundry', 'The Silicon of the East'],
    correctAnswerIndex: 0,
    explanation: 'HEC Ranchi manufactures massive steel-making machinery, draglines, and forging components, celebrated historically as the "Mother of Machines".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'The "Birsa Harit Gram Yojana" launched by the Government of Jharkhand in 2020 aims to:',
    options: [
      'Promote fruit orchard plantation (mango, guava) on unused government and fallow tribal land to create sustainable family income',
      'Distribute free tractors to panchayats',
      'Afforest industrial slag dumps',
      'Construct concrete roads in villages',
    ],
    correctAnswerIndex: 0,
    explanation: 'Under Birsa Harit Gram Yojana, over 2 lakh acres of fallow land are brought under commercial fruit plantation under MGNREGA to secure Rs 50,000 annual income for rural families.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'The "Marang Gomke Jaipal Singh Munda Overseas Scholarship Scheme" launched by Jharkhand in 2020 provides:',
    options: [
      '100% state-funded scholarships for tribal and marginalized students from Jharkhand to pursue master\'s and MPhil degrees in premier UK and overseas universities',
      'Free coaching for civil services in Delhi',
      'Subsidized loans for foreign travel',
      'Stipends for sports athletes in Europe',
    ],
    correctAnswerIndex: 0,
    explanation: 'This flagship scheme fully finances tuition and living expenses for students from tribal, Dalit, and backward backgrounds to study at Oxford, Cambridge, LSE, and other top global universities.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'The "Poto Ho Khel Vikas Yojana" in Jharkhand was launched to promote:',
    options: [
      'Development of rural sports grounds in every Gram Panchayat to nurture local athletic talent',
      'Subsidized archery equipment for schools',
      'Annual marathons across district headquarters',
      'Construction of cricket stadiums in towns',
    ],
    correctAnswerIndex: 0,
    explanation: 'Named after tribal martyr Poto Ho, the scheme constructs village-level sports playgrounds across thousands of panchayats to engage rural youth in sports and recreation.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-jharkhand',
    topicSlug: 'jharkhand-polity-economy',
    questionText: 'Under the Jharkhand Industrial and Investment Promotion Policy (JIIPP) 2021, which priority thrust sectors are incentivized with capital investment subsidies?',
    options: ['Automobile & Auto components, Electric Vehicles, Textiles, Electronic System Design (ESDM), and Agro-Food processing', 'Coal brick making', 'Conventional thermal power plants alone', 'Timber cutting'],
    correctAnswerIndex: 0,
    explanation: 'JIIPP 2021 provides comprehensive incentives including up to 25% capital subsidy for high-technology sunrise manufacturing, EV ecosystems, textiles, and food processing.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
];
