import { JPSCQuestionRaw } from './types';

export const miscellaneousQuestions: JPSCQuestionRaw[] = [
  // --- HUMAN RIGHTS & SOCIAL JUSTICE (25 Questions) ---
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'On which date was the Universal Declaration of Human Rights (UDHR) adopted by the United Nations General Assembly in Paris?',
    options: ['December 10, 1948', 'October 24, 1945', 'January 26, 1950', 'June 26, 1948'],
    correctAnswerIndex: 0,
    explanation: 'The UDHR was proclaimed by UNGA Resolution 217 A in Paris on December 10, 1948, which is commemorated globally every year as Human Rights Day.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Who chaired the United Nations Commission on Human Rights that drafted the Universal Declaration of Human Rights (UDHR)?',
    options: ['Eleanor Roosevelt', 'Rene Cassin', 'John Peters Humphrey', 'Hansa Mehta'],
    correctAnswerIndex: 0,
    explanation: 'Former US First Lady Eleanor Roosevelt chaired the drafting committee of the UDHR; Indian delegate Hansa Mehta famously ensured the language was changed from "all men are born free and equal" to "all human beings are born free and equal".',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'In India, the National Human Rights Commission (NHRC) was established under which statute in 1993?',
    options: ['The Protection of Human Rights Act, 1993', 'The National Civil Liberties Act, 1993', 'The Fundamental Rights Enforcement Act, 1993', 'The Prevention of Torture Act, 1993'],
    correctAnswerIndex: 0,
    explanation: 'The NHRC was constituted on October 12, 1993, under the Protection of Human Rights Act, 1993 (amended in 2006 and 2019) to promote and protect human rights in India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Under the Protection of Human Rights (Amendment) Act, 2019, who is eligible to be appointed as the Chairperson of the National Human Rights Commission (NHRC)?',
    options: ['A person who has been a Chief Justice of India OR a Judge of the Supreme Court', 'Only a former Chief Justice of India', 'Any retired High Court Chief Justice', 'A senior advocate of the Supreme Court'],
    correctAnswerIndex: 0,
    explanation: 'The 2019 amendment widened the eligibility to allow either a former Chief Justice of India or any retired Judge of the Supreme Court to be appointed as NHRC Chairperson.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The Chairperson and members of the NHRC are appointed by the President on the recommendation of a high-powered committee headed by:',
    options: ['Prime Minister of India', 'Chief Justice of India', 'Union Home Minister', 'Speaker of Lok Sabha'],
    correctAnswerIndex: 0,
    explanation: 'The statutory selection committee is chaired by the Prime Minister and includes the Speaker of Lok Sabha, Deputy Chairman of Rajya Sabha, Leaders of Opposition in both Houses, and the Union Home Minister.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'What is the statutory tenure of the Chairperson and members of the NHRC as amended in 2019?',
    options: ['3 years or until attaining the age of 70 years, whichever is earlier', '5 years or 70 years of age', '5 years or 65 years of age', '6 years or 68 years of age'],
    correctAnswerIndex: 0,
    explanation: 'The 2019 amendment reduced the term of office of the Chairperson and members from 5 years to 3 years (or up to 70 years of age) and made them eligible for reappointment.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The headquarters of the United Nations Human Rights Council (UNHRC) is located in which city?',
    options: ['Geneva, Switzerland', 'New York, USA', 'Vienna, Austria', 'Paris, France'],
    correctAnswerIndex: 0,
    explanation: 'The UNHRC, an intergovernmental body within the UN system made up of 47 states responsible for human rights worldwide, is headquartered at the Palais des Nations in Geneva.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The international human rights non-governmental organization "Amnesty International", which won the Nobel Peace Prize in 1977, was founded in 1961 by:',
    options: ['Peter Benenson in London', 'Henri Dunant in Geneva', 'Sean MacBride in Dublin', 'Eleanor Roosevelt in Washington'],
    correctAnswerIndex: 0,
    explanation: 'British lawyer Peter Benenson founded Amnesty International in July 1961 following his newspaper article "The Forgotten Prisoners" advocating for prisoners of conscience.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The International Committee of the Red Cross (ICRC), a three-time Nobel Peace Prize laureate, was founded in 1863 by:',
    options: ['Henry Dunant', 'Fridtjof Nansen', 'Woodrow Wilson', 'Albert Schweitzer'],
    correctAnswerIndex: 0,
    explanation: 'Swiss humanitarian Henry Dunant initiated the Red Cross after witnessing the horrific aftermath of the Battle of Solferino in 1859, leading to the First Geneva Convention.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Under Section 36(2) of the Protection of Human Rights Act 1993, what is the limitation period beyond which the NHRC cannot inquire into a human rights violation?',
    options: ['One year from the date on which the incident is alleged to have occurred', 'Two years', 'Six months', 'Three years'],
    correctAnswerIndex: 0,
    explanation: 'Section 36(2) states that the Commission shall not inquire into any matter after the expiry of one year from the date on which the act constituting violation of human rights is alleged to have been committed.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The Scheduled Castes and the Scheduled Tribes (Prevention of Atrocities) Act was enacted in which year?',
    options: ['1989', '1986', '1993', '1976'],
    correctAnswerIndex: 0,
    explanation: 'The SC/ST (Prevention of Atrocities) Act was enacted on September 9, 1989 (coming into force in January 1990) to prevent crimes against members of SCs and STs and establish Special Courts.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The Protection of Women from Domestic Violence Act (PWDVA) in India was enacted in:',
    options: ['2005', '2000', '2010', '1998'],
    correctAnswerIndex: 0,
    explanation: 'PWDVA was passed in 2005 and came into effect on October 26, 2006, providing civil protection orders, residence orders, and monetary relief for abused women.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The Child and Adolescent Labour (Prohibition and Regulation) Act, 1986, as amended in 2016, completely prohibits the employment of children below what age in all occupations and processes?',
    options: ['14 years (and prohibits adolescents aged 14–18 in hazardous occupations)', '12 years', '16 years', '18 years'],
    correctAnswerIndex: 0,
    explanation: 'The 2016 amendment aligned with the Right to Education Act, imposing a blanket ban on employment of children below 14 in all commercial establishments, with limited exemptions for non-hazardous family enterprises.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The National Commission for Protection of Child Rights (NCPCR) is a statutory body set up in 2007 under which Act of Parliament?',
    options: ['Commissions for Protection of Child Rights (CPCR) Act, 2005', 'Juvenile Justice Act, 2015', 'POCSO Act, 2012', 'Child Labour Act, 1986'],
    correctAnswerIndex: 0,
    explanation: 'The NCPCR was established in March 2007 under the CPCR Act 2005 to ensure that all laws and policies conform to the UN Convention on the Rights of the Child.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Under the Rights of Persons with Disabilities (RPwD) Act, 2016, how many categories of disabilities are legally recognized in India (increased from 7 in the 1995 Act)?',
    options: ['21 categories of disabilities', '14 categories', '18 categories', '25 categories'],
    correctAnswerIndex: 0,
    explanation: 'The RPwD Act 2016 enacted the UNCRPD principles, expanding recognized benchmark disabilities from 7 to 21 (including acid attack victims, autism, intellectual disability, and Parkinson’s).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'In which landmark case in 2014 did the Supreme Court of India recognize transgender individuals as a "Third Gender" and affirm their fundamental rights under Articles 14, 15, and 21?',
    options: ['National Legal Services Authority (NALSA) v. Union of India', 'Navtej Singh Johar v. Union of India', 'Suresh Kumar Koushal v. Naz Foundation', 'Joseph Shine v. Union of India'],
    correctAnswerIndex: 0,
    explanation: 'In the historic NALSA judgment (April 2014), the Supreme Court affirmed transgender persons\' right to self-identify their gender as male, female, or third gender.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'In Navtej Singh Johar v. Union of India (2018), the Supreme Court decriminalized consensual same-sex adult relationships by reading down which Section of the Indian Penal Code?',
    options: ['Section 377', 'Section 375', 'Section 497', 'Section 304B'],
    correctAnswerIndex: 0,
    explanation: 'A unanimous 5-judge Constitution bench ruled that Section 377 of the IPC, to the extent it criminalized consensual homosexual sexual acts between adults in private, was unconstitutional.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The National Commission for Scheduled Tribes (NCST) was created as an independent constitutional body under Article 338A by which Amendment Act?',
    options: ['89th Constitutional Amendment Act, 2003', '65th Amendment Act, 1990', '102nd Amendment Act, 2018', '73rd Amendment Act, 1992'],
    correctAnswerIndex: 0,
    explanation: 'The 89th Amendment Act of 2003 bifurcated the erstwhile National Commission for SCs and STs into the National Commission for Scheduled Castes (Art 338) and the National Commission for Scheduled Tribes (Art 338A).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Who was appointed the first Chairman of the National Commission for Scheduled Tribes (NCST) in 2004?',
    options: ['Kunwar Singh Tekam', 'Urmila Singh', 'Rameshwar Oraon', 'Nand Kumar Sai'],
    correctAnswerIndex: 0,
    explanation: 'Kunwar Singh Tekam served as the inaugural Chairperson of the newly established National Commission for Scheduled Tribes in March 2004.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The National Commission for Backward Classes (NCBC) was accorded constitutional status under Article 338B by which Amendment Act in 2018?',
    options: ['102nd Constitutional Amendment Act, 2018', '103rd Amendment Act, 2019', '101st Amendment Act, 2016', '99th Amendment Act, 2014'],
    correctAnswerIndex: 0,
    explanation: 'The 102nd Amendment Act of 2018 inserted Article 338B and Article 342A into the Constitution, elevating the NCBC from a statutory body to a constitutional body.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The landmark Vishaka v. State of Rajasthan (1997) Supreme Court ruling laid down mandatory guidelines regarding:',
    options: ['Prevention of Sexual Harassment of women at the workplace', 'Equal wages for domestic workers', 'Maternity leave entitlements', 'Dowry prohibition enforcement'],
    correctAnswerIndex: 0,
    explanation: 'The Vishaka guidelines defined sexual harassment and mandated Internal Complaints Committees (ICC), forming the foundation for the Sexual Harassment of Women at Workplace (POSH) Act 2013.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The concept of "Public Interest Litigation" (PIL) was pioneered in India in the late 1970s and 1980s under the judicial leadership of which Supreme Court judges?',
    options: ['Justice P. N. Bhagwati and Justice V. R. Krishna Iyer', 'Justice H. R. Khanna and Justice M. H. Beg', 'Justice Y. V. Chandrachud and Justice A. N. Ray', 'Justice J. S. Verma and Justice Kuldip Singh'],
    correctAnswerIndex: 0,
    explanation: 'Justices P.N. Bhagwati and V.R. Krishna Iyer relaxed the traditional doctrine of locus standi, allowing any public-spirited citizen or NGO to petition the courts under Article 32 or 226 for the downtrodden.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'The legal principle of "Epistolary Jurisdiction" developed by the Indian judiciary in human rights protection means:',
    options: ['The court treating a simple letter or postcard from an aggrieved or incarcerated citizen as a formal writ petition', 'Conducting trials by written correspondence', 'Exchanging affidavits via email', 'Issuing judicial letters to foreign embassies'],
    correctAnswerIndex: 0,
    explanation: 'Under epistolary jurisdiction (epitomized in Sunil Batra v. Delhi Administration), the Supreme Court accepts informal handwritten letters or telegrams as writ petitions to redress custodial atrocities.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Under the Protection of Children from Sexual Offences (POCSO) Act, 2012, an individual is legally defined as a "child" if below what age?',
    options: ['18 years', '14 years', '16 years', '12 years'],
    correctAnswerIndex: 0,
    explanation: 'Section 2(1)(d) of the POCSO Act 2012 explicitly defines a child as any person below the age of 18 years, providing gender-neutral protection against sexual abuse and exploitation.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'human-rights',
    questionText: 'Who was awarded the Nobel Peace Prize in 2014 alongside Malala Yousafzai for spearheading the "Bachpan Bachao Andolan" to rescue children from bonded labor?',
    options: ['Kailash Satyarthi', 'Swami Agnivesh', 'Medha Patkar', 'Anna Hazare'],
    correctAnswerIndex: 0,
    explanation: 'Kailash Satyarthi founded Bachpan Bachao Andolan in 1980 and organized the Global March Against Child Labour, liberating over 100,000 children from slavery.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },

  // --- ENVIRONMENT, BIODIVERSITY & CLIMATE CHANGE (25 Questions) ---
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Wildlife (Protection) Act of India, which provides statutory protection to wild animals, birds, and plants, was enacted in which year?',
    options: ['1972', '1980', '1986', '1974'],
    correctAnswerIndex: 0,
    explanation: 'Enacted in 1972 under Prime Minister Indira Gandhi, the Wildlife (Protection) Act established protected areas (National Parks, Sanctuaries) and prohibited hunting of scheduled species.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Environment (Protection) Act was enacted by the Indian Parliament in 1986 in the immediate aftermath of which tragic industrial catastrophe?',
    options: ['Bhopal Gas Tragedy (December 1984)', 'Chasnala Mining Disaster', 'Visakhapatnam Gas Leak', 'Jaipur Oil Depot Fire'],
    correctAnswerIndex: 0,
    explanation: 'Enacted under Article 253 to implement the decisions of the 1972 Stockholm Conference, the umbrella Environment (Protection) Act 1986 was triggered by the methyl isocyanate leak in Bhopal.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Forest (Conservation) Act, which strictly prohibits the diversion of forest land for non-forest purposes without prior central approval, was passed in:',
    options: ['1980', '1972', '1988', '1952'],
    correctAnswerIndex: 0,
    explanation: 'The Forest (Conservation) Act of 1980 curbed indiscriminate deforestation by requiring central government authorization before de-reserving or clearing forest land.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The National Green Tribunal (NGT) was established in October 2010 under which Article / statute for speedy environmental justice?',
    options: ['The National Green Tribunal Act, 2010 (drawn from Article 21 - Right to a Healthy Environment)', 'The Wildlife Act', 'The Forest Act', 'The Air Act'],
    correctAnswerIndex: 0,
    explanation: 'Established under the NGT Act 2010, the NGT is a specialized judicial body chaired by a retired Supreme Court Judge with principal bench in New Delhi to dispose of environmental cases within 6 months.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: '"Project Tiger", India’s landmark conservation initiative to save the Bengal Tiger, was officially launched on April 1, 1973, from which National Park?',
    options: ['Jim Corbett National Park (Uttarakhand)', 'Kanha National Park', 'Ranthambore National Park', 'Sundarbans National Park'],
    correctAnswerIndex: 0,
    explanation: 'Project Tiger was launched in April 1973 at Corbett National Park by Prime Minister Indira Gandhi with nine initial tiger reserves covering 9,115 sq km (including Palamu in Jharkhand).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: '"Project Elephant" was launched by the Ministry of Environment and Forests in which year to provide financial and technical support for wild Asian elephants and their migration corridors?',
    options: ['February 1992', '1973', '2002', '1988'],
    correctAnswerIndex: 0,
    explanation: 'Project Elephant was launched in 1992 to protect elephants, secure ecological corridors, address human-elephant conflict, and care for captive elephants.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'India’s first designated Elephant Reserve notified in 2001 under Project Elephant is:',
    options: ['Singhbhum Elephant Reserve (Jharkhand)', 'Mayurbhanj Elephant Reserve', 'Wayanad Elephant Reserve', 'Kaziranga Elephant Reserve'],
    correctAnswerIndex: 0,
    explanation: 'The Singhbhum Elephant Reserve, covering 13,440 sq km across East and West Singhbhum and Saraikela-Kharsawan in Jharkhand, was notified as the country’s first elephant reserve in 2001.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The concept of "Biodiversity Hotspots" was first developed in 1988 by which British environmentalist?',
    options: ['Norman Myers', 'E. O. Wilson', 'Arthur Tansley', 'Charles Elton'],
    correctAnswerIndex: 0,
    explanation: 'Norman Myers identified biodiversity hotspots as biogeographic regions boasting at least 1,500 endemic vascular plant species that have lost over 70% of their primary native vegetation.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'How many global Biodiversity Hotspots are represented in the territory of India?',
    options: ['4 Hotspots (Himalaya, Western Ghats, Indo-Burma, and Sundaland)', '2 Hotspots', '6 Hotspots', '3 Hotspots'],
    correctAnswerIndex: 0,
    explanation: 'Four of the world’s 36 biodiversity hotspots cover Indian territory: the Himalayas, the Western Ghats (and Sri Lanka), Indo-Burma (Northeast India), and Sundaland (Nicobar Islands).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Ramsar Convention on Wetlands of International Importance was signed in 1971 in Ramsar, a city located in which country?',
    options: ['Iran', 'Iraq', 'Jordan', 'Egypt'],
    correctAnswerIndex: 0,
    explanation: 'The Convention on Wetlands was adopted on February 2, 1971, in the Iranian city of Ramsar on the shores of the Caspian Sea, celebrated globally as World Wetlands Day.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Montreal Protocol on Substances that Deplete the Ozone Layer was signed in 1987 to phase out the production of:',
    options: ['Chlorofluorocarbons (CFCs) and Halons', 'Carbon dioxide and methane', 'Sulfur dioxide and nitrogen oxides', 'Lead and mercury effluents'],
    correctAnswerIndex: 0,
    explanation: 'The Montreal Protocol successfully phased out the manufacture of ozone-depleting halogenated hydrocarbons (CFCs, halons, CTC), universally recognized as the most successful international environmental treaty.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Kigali Amendment (2016) to the Montreal Protocol aims to progressively phase down which potent greenhouse gases used as refrigerants?',
    options: ['Hydrofluorocarbons (HFCs)', 'Sulfur hexafluoride', 'Methane', 'Nitrous oxide'],
    correctAnswerIndex: 0,
    explanation: 'The Kigali Amendment agreed to phase down HFCs (which replaced CFCs but act as greenhouse gases thousands of times more potent than CO2) by more than 80% over 30 years.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Kyoto Protocol adopted in 1997 under the UNFCCC established legally binding greenhouse gas emission reduction targets based on the principle of:',
    options: ['Common But Differentiated Responsibilities and Respective Capabilities (CBDR-RC)', 'Equal per capita emissions', 'Polluter Pays Principle alone', 'Market-based carbon taxing'],
    correctAnswerIndex: 0,
    explanation: 'CBDR-RC acknowledges that developed countries (Annex I) are historically responsible for the bulk of industrial carbon emissions and must bear the primary burden of mitigation.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The landmark Paris Agreement adopted at COP21 in December 2015 aims to hold the increase in global average temperature to:',
    options: ['Well below 2°C above pre-industrial levels and pursuing efforts to limit it to 1.5°C', 'Below 3°C', 'Below 1°C', 'Zero temperature rise'],
    correctAnswerIndex: 0,
    explanation: 'Article 2 of the Paris Agreement commits all signatory parties to hold global warming well below 2°C and pursue efforts to cap the increase at 1.5°C through Nationally Determined Contributions (NDCs).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'In India, the National Biodiversity Authority (NBA) was established in 2003 with headquarters at:',
    options: ['Chennai (Tamil Nadu)', 'New Delhi', 'Kolkata', 'Dehradun'],
    correctAnswerIndex: 0,
    explanation: 'The National Biodiversity Authority was established in 2003 at Chennai to implement India’s Biological Diversity Act 2002, regulating access to bio-resources and fair benefit sharing.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The "Red Data Book", which documents rare and endangered species of plants and animals facing extinction risks, is published by:',
    options: ['International Union for Conservation of Nature (IUCN)', 'World Wide Fund for Nature (WWF)', 'United Nations Environment Programme (UNEP)', 'Convention on Biological Diversity (CBD)'],
    correctAnswerIndex: 0,
    explanation: 'The IUCN Red List of Threatened Species founded in 1964 assesses extinction risks across categories ranging from Least Concern (LC) to Critically Endangered (CR) and Extinct (EX).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The historic "Chipko Movement" against commercial tree felling was spearheaded in 1973 in Reni village (Chamoli district, Uttarakhand) by:',
    options: ['Sunderlal Bahuguna and Chandi Prasad Bhatt (along with Gaura Devi)', 'Baba Amte and Medha Patkar', 'Salimar Ali and Madhav Gadgil', 'Anna Hazare and Rajendra Singh'],
    correctAnswerIndex: 0,
    explanation: 'Villagers led by Gaura Devi, Chandi Prasad Bhatt, and Sunderlal Bahuguna hugged trees in the Garhwal Himalayas, prompting a 15-year ban on commercial felling in the region.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The Appiko Movement, an environmental grassroots campaign modeled directly on the Chipko Movement, originated in 1983 in which state?',
    options: ['Karnataka (Western Ghats - Uttara Kannada)', 'Kerala', 'Tamil Nadu', 'Maharashtra'],
    correctAnswerIndex: 0,
    explanation: 'Led by Pandurang Hegde in Salkani village, Sirsi, Karnataka, villagers embraced trees in the Western Ghats under the Kannada slogan "Ubsu, Belasu, Balasu" (Save, Grow, and Rational Use).',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'Rajendra Singh, the Magsaysay and Stockholm Water Prize laureate renowned for reviving indigenous Johad rainwater check-dams in Rajasthan, is popularly hailed as:',
    options: ['"Waterman of India"', '"Forest Man of India"', '"Birdman of India"', '"Ice Man of India"'],
    correctAnswerIndex: 0,
    explanation: 'Rajendra Singh spearheaded community watershed management through the Tarun Bharat Sangh NGO, reviving seven rivers across arid Rajasthan.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'Jadav Payeng, who single-handedly planted and cultivated an entire 550-hectare forest over 40 years on a sandbar of the Brahmaputra River in Assam, is known as:',
    options: ['"Forest Man of India"', '"Green Warrior"', '"Tree Saint"', '"Mountain Man"'],
    correctAnswerIndex: 0,
    explanation: 'Jadav "Molai" Payeng created the Molai forest in Majuli island, awarded the Padma Shri in 2015 as the "Forest Man of India".',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The "Biological Oxygen Demand" (BOD) of a water body serves as an index of:',
    options: ['Organic pollution in water (amount of dissolved oxygen needed by aerobic microorganisms to decompose organic material)', 'Industrial heavy metal toxicity', 'Acidity of rain precipitation', 'Salinity concentration'],
    correctAnswerIndex: 0,
    explanation: 'Higher BOD indicates that more dissolved oxygen is being consumed by bacterial decomposition of organic wastes, signifying severe organic contamination.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'What is "Biomagnification" (Bioamplification) in ecotoxicology?',
    options: [
      'The increasing concentration of a persistent toxic chemical (such as DDT or methylmercury) in the tissues of organisms at successively higher levels in a food chain',
      'The rapid proliferation of microscopic algae',
      'The natural regeneration of topsoil',
      'The expansion of desert boundaries',
    ],
    correctAnswerIndex: 0,
    explanation: 'Lipophilic, non-biodegradable toxins resist metabolic breakdown and become exponentially magnified in top trophic-level predators (such as vultures and raptors).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The catastrophic decline of India’s white-rumped and long-billed vulture population (by over 99% in the 1990s) was caused by residues of which veterinary NSAID drug in cattle carcasses?',
    options: ['Diclofenac', 'Paracetamol', 'Ibuprofen', 'Penicillin'],
    correctAnswerIndex: 0,
    explanation: 'Vultures feeding on livestock treated with the veterinary anti-inflammatory drug Diclofenac suffered acute visceral gout and kidney failure, resulting in a ban on veterinary diclofenac in 2006.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'The "Cheetah Reintroduction Project" in India saw the first batch of wild African cheetahs released in September 2022 into which National Park?',
    options: ['Kuno National Park (Madhya Pradesh)', 'Madhav National Park', 'Bandhavgarh National Park', 'Ranthambore National Park'],
    correctAnswerIndex: 0,
    explanation: 'Cheetahs, declared extinct in India in 1952, were translocated from Namibia and South Africa and released into Kuno National Park in Sheopur, Madhya Pradesh.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'environment-biodiversity',
    questionText: 'Which was the first Biosphere Reserve established in India in 1986 under UNESCO’s Man and the Biosphere (MAB) Programme?',
    options: ['Nilgiri Biosphere Reserve (spanning Tamil Nadu, Kerala, and Karnataka)', 'Nanda Devi Biosphere Reserve', 'Gulf of Mannar', 'Sundarbans'],
    correctAnswerIndex: 0,
    explanation: 'The Nilgiri Biosphere Reserve covering 5,520 sq km in the Western Ghats was India’s first designated biosphere reserve in 1986, harboring Lion-tailed macaques and Nilgiri tahrs.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },

  // --- DISASTER MANAGEMENT (20 Questions) ---
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The Disaster Management Act, which created an institutional mechanism for disaster response and mitigation in India, was enacted in which year?',
    options: ['2005 (Act No. 53 of 2005)', '2000', '2008', '2010'],
    correctAnswerIndex: 0,
    explanation: 'Passed in the wake of the 2004 Indian Ocean Tsunami, the Disaster Management Act received presidential assent on December 23, 2005.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'Under Section 3 of the Disaster Management Act, 2005, who serves as the ex-officio Chairperson of the National Disaster Management Authority (NDMA)?',
    options: ['Prime Minister of India', 'Union Minister of Home Affairs', 'Minister of Science and Technology', 'Cabinet Secretary'],
    correctAnswerIndex: 0,
    explanation: 'The NDMA is the apex policy body for disaster management in India, headed ex-officio by the Prime Minister of India, with a nominated Vice-Chairperson holding cabinet-minister rank.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'At the State level, who heads the State Disaster Management Authority (SDMA) under Section 14 of the Disaster Management Act?',
    options: ['Chief Minister of the State', 'Governor of the State', 'State Home Minister', 'Chief Secretary'],
    correctAnswerIndex: 0,
    explanation: 'The SDMA is headed ex-officio by the Chief Minister of the respective State as Chairperson.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'At the district level, who functions as the Chairperson of the District Disaster Management Authority (DDMA) under Section 25?',
    options: ['District Magistrate / Collector / Deputy Commissioner (with elected local head as Co-Chairperson)', 'Superintendent of Police', 'Zilla Parishad President alone', 'Chief Medical Officer'],
    correctAnswerIndex: 0,
    explanation: 'The District Collector / DM / Deputy Commissioner is the ex-officio Chairperson of the DDMA, coordinating all emergency relief and disaster preparedness operations.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The National Disaster Response Force (NDRF) was constituted under Section 44 of the DM Act 2005. Which central armed police forces contribute personnel on deputation to NDRF?',
    options: ['BSF, CRPF, CISF, ITBP, SSB, and Assam Rifles', 'Indian Army exclusively', 'State Armed Police battalions', 'Home Guards alone'],
    correctAnswerIndex: 0,
    explanation: 'The NDRF is a specialized multi-disciplinary disaster rescue force composed of 16 battalions staffed on deputation from central armed paramilitary forces.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The "Sendai Framework for Disaster Risk Reduction" (2015–2030) was adopted at the Third UN World Conference on Disaster Risk Reduction in which country?',
    options: ['Japan', 'Switzerland', 'South Korea', 'Germany'],
    correctAnswerIndex: 0,
    explanation: 'Adopted in Sendai, Miyagi Prefecture, Japan, in March 2015, the framework outlines four priorities and seven global targets to substantially reduce disaster mortality and economic losses by 2030.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The Coalition for Disaster Resilient Infrastructure (CDRI) was launched in September 2019 at the UN Climate Action Summit by which world leader?',
    options: ['Prime Minister Narendra Modi of India', 'President Emmanuel Macron of France', 'UN Secretary-General Antonio Guterres', 'Prime Minister Boris Johnson of the UK'],
    correctAnswerIndex: 0,
    explanation: 'PM Modi launched CDRI, headquartered in New Delhi, as an international partnership of national governments, UN agencies, and multilateral banks to promote climate-resilient infrastructure.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'According to the Bureau of Indian Standards (BIS) seismic zoning map of India, how many Seismic Hazard Zones are recognized in the country?',
    options: ['Four Zones (Zone II, Zone III, Zone IV, and Zone V)', 'Five Zones (Zones I through V)', 'Three Zones', 'Six Zones'],
    correctAnswerIndex: 0,
    explanation: 'BIS IS 1893:2002 classified India into four seismic zones: Zone II (Low), Zone III (Moderate), Zone IV (Severe), and Zone V (Very Severe / Catastrophic). Zone I was merged into Zone II.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'Which northern and northeastern regions of India fall under the highest seismic risk category: Seismic Zone V?',
    options: ['Entire Northeast India, parts of Jammu & Kashmir, Ladakh, Himachal Pradesh, Uttarakhand, Rann of Kutch, and North Bihar', 'Deccan Plateau', 'Rajasthan Thar desert', 'Odisha coast'],
    correctAnswerIndex: 0,
    explanation: 'Zone V corresponds to macro-seismic intensity of IX or greater on the MSK scale, covering the active plate collision boundary of the Himalayas and the fault zones of Kutch.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'Which instrument is universally used to record the motion of the ground during an earthquake?',
    options: ['Seismograph (Seismometer)', 'Barometer', 'Anemometer', 'Hygrometer'],
    correctAnswerIndex: 0,
    explanation: 'A seismometer measures ground motion vibrations generated by seismic P, S, and surface waves, producing a graph known as a seismogram.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'What is the point on the Earth’s surface directly vertically above the subterranean focus (hypocenter) where an earthquake originates?',
    options: ['Epicenter', 'Focal point', 'Fault plane', 'Seismic shadow zone'],
    correctAnswerIndex: 0,
    explanation: 'The hypocenter (focus) is the subsurface rupture point within the earth where seismic strain is released; the point on the surface directly above it is the epicenter.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The Richter Magnitude Scale measures the energy released by an earthquake on a logarithmic scale where each whole number increase represents what increase in wave amplitude?',
    options: ['10-fold increase in wave amplitude (and ~31.6 times increase in energy)', '2-fold increase', '100-fold increase', '5-fold increase'],
    correctAnswerIndex: 0,
    explanation: 'Developed by Charles Richter in 1935, each whole unit step represents a 10-fold increase in measured seismographic amplitude and approximately 31.6 times more energy released.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The Indian Tsunami Early Warning Centre (ITEWC), established following the 2004 Indian Ocean Tsunami, is operated by INCOIS located at:',
    options: ['Hyderabad (Telangana)', 'Chennai', 'Visakhapatnam', 'Kochi'],
    correctAnswerIndex: 0,
    explanation: 'The Indian National Centre for Ocean Information Services (INCOIS) under the Ministry of Earth Sciences operates the state-of-the-art 24x7 ITEWC in Hyderabad.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'In India, the apex national agency responsible for monitoring, cyclone forecasting, and issuing weather storm warnings is:',
    options: ['India Meteorological Department (IMD), New Delhi', 'National Centre for Medium Range Weather Forecasting (NCMRWF)', 'INCOIS', 'Survey of India'],
    correctAnswerIndex: 0,
    explanation: 'Founded in 1875 under the Ministry of Earth Sciences, the IMD is designated as a Regional Specialised Meteorological Centre (RSMC) by WMO for tracking tropical cyclones in the North Indian Ocean.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'What is a "Glacial Lake Outburst Flood" (GLOF), such as the South Lhonak lake disaster in Sikkim in October 2023?',
    options: [
      'A catastrophic release of water when a moraine or ice dam containing a proglacial lake fails abruptly',
      'The sudden melting of sea ice in the Arctic',
      'Flash floods triggered by industrial dam sluices',
      'A subterranean volcanic eruption under a geyser',
    ],
    correctAnswerIndex: 0,
    explanation: 'GLOFs occur when unstable moraine dams retaining retreat-formed glacial lakes breach due to avalanches, earthquakes, or cloudbursts, releasing high-velocity debris floods.',
    difficulty: 'Medium',
    questionType: 'CURRENT_AFFAIRS',
    sourceType: 'INTERNAL',
    sourceDate: '2023-10-05',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'Which mining disaster in the Dhanbad coal belt of Jharkhand on December 27, 1975, killed 375 miners when water from an abandoned mine inundated the pit?',
    options: ['Chasnala Mining Disaster', 'Dhori Colliery Disaster', 'Rajpura Disaster', 'Lalmatia Disaster'],
    correctAnswerIndex: 0,
    explanation: 'The Chasnala Colliery disaster occurred when an explosion breached millions of gallons of water from an adjacent flooded pit into the Chasnala mine, suffocating and drowning 375 miners.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'In Jharkhand, underground coal seam fires that have been burning uncontrolled for over a century, causing ground subsidence and toxic emissions, are located in:',
    options: ['Jharia Coalfield', 'Karanpura field', 'Giridih field', 'Rajmahal field'],
    correctAnswerIndex: 0,
    explanation: 'First detected in 1916 at Khas Jharia, subterranean coal fires in the Jharia basin burn across multiple fire areas, prompting major rehabilitation programs by BCCL.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'The National Institute of Disaster Management (NIDM), the premier national training institute for capacity building in disaster mitigation, is located in:',
    options: ['New Delhi', 'Dehradun', 'Nagpur', 'Pune'],
    correctAnswerIndex: 0,
    explanation: 'Under Section 42 of the DM Act 2005, NIDM operates in New Delhi to conduct research, training courses, and policy formulation for disaster management in India.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'Which chemical agent is commonly used in fire extinguishers to extinguish electrical fires and flammable liquid fires without leaving conductive residue?',
    options: ['Carbon Dioxide (CO2)', 'Water', 'Sodium chloride foam', 'Bleaching powder'],
    correctAnswerIndex: 0,
    explanation: 'Carbon dioxide smothers fires by displacing ambient oxygen and provides non-conductive, clean suppression suitable for Class B (liquids) and Class C (electrical) fires.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'disaster-management',
    questionText: 'What is the standard disaster emergency helpline number operationalized across India for police, fire, medical, and disaster response?',
    options: ['112', '100', '108', '101'],
    correctAnswerIndex: 0,
    explanation: '112 is the unified pan-India Emergency Response Support System (ERSS), integrating all emergency utility numbers (Police 100, Fire 101, Ambulance 102).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },

  // --- SPORTS, URBANIZATION & MISCELLANEOUS GK (20 Questions) ---
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Who was the first individual Olympic Gold Medalist from independent India?',
    options: ['Abhinav Bindra (10m Air Rifle at Beijing 2008)', 'Neeraj Chopra', 'K. D. Jadhav', 'Leander Paes'],
    correctAnswerIndex: 0,
    explanation: 'Abhinav Bindra won India’s historic first individual Olympic gold medal in the Men’s 10m Air Rifle event at the 2008 Beijing Olympic Games.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Who was the first individual athlete from independent India to win an Olympic medal (Bronze in Men’s freestyle bantamweight wrestling at Helsinki 1952)?',
    options: ['K. D. Jadhav (Khashaba Dadasaheb Jadhav)', 'Milkha Singh', 'Norman Pritchard', 'Dhyan Chand'],
    correctAnswerIndex: 0,
    explanation: 'Wrestler K.D. Jadhav made history at the 1952 Helsinki Olympics by securing the bronze medal, India\'s first individual podium finish after independence.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'What is the highest sporting honour of the Republic of India, renamed in August 2021?',
    options: ['Major Dhyan Chand Khel Ratna Award', 'Arjuna Award', 'Dronacharya Award', 'Rashtriya Khel Protsahan Puruskar'],
    correctAnswerIndex: 0,
    explanation: 'Formerly known as the Rajiv Gandhi Khel Ratna Award, India’s premier sports award instituted in 1991–92 was officially rechristened the Major Dhyan Chand Khel Ratna Award in August 2021.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Who was the first recipient of the Rajiv Gandhi Khel Ratna (now Major Dhyan Chand Khel Ratna) Award in 1991–1992?',
    options: ['Viswanathan Anand (Chess)', 'Sachin Tendulkar', 'Geet Sethi', 'Karnam Malleswari'],
    correctAnswerIndex: 0,
    explanation: 'Grandmaster Viswanathan Anand was conferred the inaugural Khel Ratna award in 1991–92 following his international triumphs as India’s first chess Grandmaster.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'National Sports Day in India is celebrated every year on August 29 to commemorate the birth anniversary of which legendary sports icon?',
    options: ['Major Dhyan Chand (The Wizard of Hockey)', 'Milkha Singh', 'K. D. Jadhav', 'Kapil Dev'],
    correctAnswerIndex: 0,
    explanation: 'August 29 marks the birth anniversary of Major Dhyan Chand, who steered India to three Olympic hockey gold medals (1928, 1932, 1936).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Who was the first Indian woman to win an Olympic medal (Bronze in 69kg weightlifting at Sydney 2000)?',
    options: ['Karnam Malleswari', 'Mary Kom', 'Saina Nehwal', 'P. V. Sindhu'],
    correctAnswerIndex: 0,
    explanation: 'Weightlifter Karnam Malleswari of Andhra Pradesh became the first Indian woman to climb an Olympic podium on September 19, 2000, lifting 240 kg at Sydney.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Who is the only Indian woman athlete to win medals at two consecutive Olympic Games (Silver at Rio 2016 and Bronze at Tokyo 2020)?',
    options: ['P. V. Sindhu (Badminton)', 'Saina Nehwal', 'Sakshi Malik', 'Lovlina Borgohain'],
    correctAnswerIndex: 0,
    explanation: 'Shuttler P.V. Sindhu clinched silver at the 2016 Rio Games and bronze at the 2020 Tokyo Games, becoming the first Indian female double individual Olympic medalist.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'The Atal Mission for Rejuvenation and Urban Transformation (AMRUT) launched in June 2015 aims to provide basic urban services primarily in:',
    options: ['Water supply, sewerage network, and stormwater drainage in 500 select cities', 'Construction of airports in metropolitan areas', 'Building shopping malls', 'Free urban bus passes'],
    correctAnswerIndex: 0,
    explanation: 'AMRUT focuses on universal household coverage of piped water tap connections and sewerage facilities across 500 major Indian cities.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'The Smart Cities Mission was launched by the Government of India in June 2015 to promote core infrastructure and decent quality of life across how many selected cities?',
    options: ['100 Smart Cities', '50 Smart Cities', '200 Smart Cities', '75 Smart Cities'],
    correctAnswerIndex: 0,
    explanation: 'The Smart Cities Mission selected 100 cities through a competitive challenge process, utilizing Integrated Command and Control Centres (ICCC) for smart urban governance.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Which city in Jharkhand was selected under the first round of the Smart Cities Mission and developed India\'s first greenfield Smart City at Dhurwa?',
    options: ['Ranchi Smart City', 'Jamshedpur', 'Dhanbad', 'Bokaro'],
    correctAnswerIndex: 0,
    explanation: 'Ranchi Smart City is being developed over 656 acres of greenfield land in Dhurwa, planned with smart utilities, education hubs, and transit-oriented development.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'In Census of India terminology, what is a "Census Town"?',
    options: [
      'A settlement with minimum population of 5,000, at least 75% of male working population in non-agricultural pursuits, and a density of at least 400 persons per sq km',
      'Any town having a municipal corporation',
      'A village with an industrial factory',
      'A settlement with a railway station',
    ],
    correctAnswerIndex: 0,
    explanation: 'Census Towns are not statutory administrative municipalities but meet the threefold demographic criteria of population (>= 5,000), male non-farm workforce (>= 75%), and density (>= 400/km2).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'According to Census 2011, what percentage of India’s total population resides in urban areas?',
    options: ['31.16%', '27.80%', '35.40%', '22.50%'],
    correctAnswerIndex: 0,
    explanation: 'As per the 2011 Census, India’s urban population stood at 377.1 million, constituting 31.16% of the total population (68.84% rural).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'According to Census 2011, what is the urbanization rate (percentage of urban population) of the State of Jharkhand?',
    options: ['24.05%', '31.16%', '18.20%', '29.50%'],
    correctAnswerIndex: 0,
    explanation: 'In Census 2011, 24.05% of Jharkhand’s population (approx. 79.33 lakh) lived in urban areas, with Dhanbad being the most urbanized district (58.13%).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Which district in Jharkhand has the lowest percentage of urban population (most rural) as per Census 2011?',
    options: ['Godda (4.91%)', 'Garhwa', 'Chatra', 'Latehar'],
    correctAnswerIndex: 0,
    explanation: 'Godda district has the lowest urban population proportion in Jharkhand at only 4.91%, making it 95.09% rural.',
    difficulty: 'Hard',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'The "Pradhan Mantri Street Vendor’s AtmaNirbhar Nidhi" (PM SVANidhi) scheme launched in June 2020 provides:',
    options: ['Collateral-free working capital micro-loans up to Rs 10,000 (escalating to Rs 50,000) for urban street vendors', 'Permanent shops in municipal malls', 'Free food rations to vendors', 'Subsidized fuel for cargo autos'],
    correctAnswerIndex: 0,
    explanation: 'PM SVANidhi empowers street vendors to resume livelihoods post-COVID-19 lockdowns with affordable working capital loans incentivized with 7% interest subsidies for timely digital repayment.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'Which international day is observed globally every year on June 21, adopted by the UN General Assembly on India’s proposal in 2014?',
    options: ['International Day of Yoga', 'World Environment Day', 'International Day of Peace', 'World Water Day'],
    correctAnswerIndex: 0,
    explanation: 'UNGA Resolution 69/131 proclaimed June 21 as the International Day of Yoga, recognizing the ancient holistic health practice originating in India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'World Environment Day has been celebrated annually on June 5 since 1973 under the auspices of which UN agency?',
    options: ['United Nations Environment Programme (UNEP)', 'World Meteorological Organization (WMO)', 'UNESCO', 'UNDP'],
    correctAnswerIndex: 0,
    explanation: 'Established by the UN General Assembly at the Stockholm Conference in 1972, World Environment Day is led by UNEP on June 5.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'International Mother Language Day is observed globally on February 21 to commemorate:',
    options: [
      'The students killed in Dhaka in 1952 protesting for the recognition of Bengali as an official language',
      'The adoption of the UN Charter',
      'The death anniversary of Rabindranath Tagore',
      'The founding of UNESCO',
    ],
    correctAnswerIndex: 0,
    explanation: 'UNESCO proclaimed February 21 as International Mother Language Day in 1999 to honor the 1952 Language Movement martyrs in Dhaka.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'The headquarters of the United Nations Educational, Scientific and Cultural Organization (UNESCO) is located in:',
    options: ['Paris, France', 'Geneva, Switzerland', 'Rome, Italy', 'London, UK'],
    correctAnswerIndex: 0,
    explanation: 'Founded in 1945, UNESCO is headquartered at Place de Fontenoy in Paris, France.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-miscellaneous',
    topicSlug: 'sports-urbanization-misc',
    questionText: 'The Food and Agriculture Organization (FAO) of the United Nations has its international headquarters situated in:',
    options: ['Rome, Italy', 'Geneva, Switzerland', 'Vienna, Austria', 'Nairobi, Kenya'],
    correctAnswerIndex: 0,
    explanation: 'Established on October 16, 1945 (observed as World Food Day), the FAO is headquartered in Rome, Italy, leading global efforts to defeat hunger and ensure food security.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
];
