import { JPSCQuestionRaw } from './types';

export const scienceQuestions: JPSCQuestionRaw[] = [
  // --- GENERAL SCIENCE (35 Questions) ---
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the optical phenomenon responsible for the twinkling of stars observed from the Earth’s surface at night?',
    options: ['Atmospheric refraction through turbulent layers of varying optical density', 'Total internal reflection', 'Dispersion of white starlight', 'Rayleigh scattering by atmospheric gases'],
    correctAnswerIndex: 0,
    explanation: 'As light from distant point-source stars travels through atmospheric air layers of continually shifting temperature and refractive index, the apparent path bends irregularly, causing the intensity to fluctuate (scintillation).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which electromagnetic radiation has the shortest wavelength and the highest frequency and energy in the electromagnetic spectrum?',
    options: ['Gamma rays', 'X-rays', 'Ultraviolet rays', 'Radio waves'],
    correctAnswerIndex: 0,
    explanation: 'Gamma rays possess the shortest wavelength (< 10^-11 meters), highest frequencies (> 10^19 Hz), and greatest penetrating power among all regions of the electromagnetic spectrum.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Why is red light used as a danger signal and traffic brake light?',
    options: ['Red light has the longest wavelength in visible light and undergoes the least scattering by fog and air molecules', 'Red light travels faster than all other colors in vacuum', 'Red light is completely absorbed by the human cornea', 'Red light causes optical refraction in glass lenses'],
    correctAnswerIndex: 0,
    explanation: 'According to Rayleigh’s Law of Scattering, scattered intensity is inversely proportional to the fourth power of wavelength (I proportional to 1/lambda^4). Red has the longest wavelength in the visible spectrum and scatters least, remaining visible from great distances through smoke and fog.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Optical fibers transmit high-speed telecommunication signals based on which fundamental optical principle?',
    options: ['Total Internal Reflection', 'Optical Interference', 'Fraunhofer Diffraction', 'Polarization by double refraction'],
    correctAnswerIndex: 0,
    explanation: 'Optical fibers consist of a high-refractive-index core enclosed in a lower-refractive-index cladding; light entering above the critical angle undergoes repeated Total Internal Reflection (TIR) with minimal signal loss.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the SI unit of electric potential difference (electromotive force)?',
    options: ['Volt', 'Ampere', 'Ohm', 'Watt'],
    correctAnswerIndex: 0,
    explanation: 'The Volt (V), named after Alessandro Volta, is the SI unit of electric potential difference and electromotive force, defined as one joule of energy per coulomb of electric charge (1 V = 1 J/C).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which physical law explains the upward buoyant force exerted on a body wholly or partially submerged in a fluid?',
    options: ['Archimedes’ Principle', 'Pascal’s Law', 'Bernoulli’s Principle', 'Hooke’s Law'],
    correctAnswerIndex: 0,
    explanation: 'Archimedes\' Principle states that any body completely or partially immersed in a fluid experiences an upward buoyant force equal to the weight of the fluid displaced by the body.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Hydraulic brakes in automobiles and hydraulic lifts operate directly on the basis of:',
    options: ['Pascal’s Law', 'Archimedes’ Principle', 'Newton’s Third Law', 'Bernoulli’s Theorem'],
    correctAnswerIndex: 0,
    explanation: 'Pascal\'s Law states that pressure applied to an enclosed static fluid is transmitted equally and undiminished in all directions across the fluid and container walls, allowing force multiplication in hydraulics.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Why does water boil at a lower temperature than 100°C at high altitudes in the mountains?',
    options: ['Atmospheric pressure is lower at high altitudes', 'Atmospheric pressure is higher', 'Water density decreases with height', 'Sunlight is more intense at high altitudes'],
    correctAnswerIndex: 0,
    explanation: 'A liquid boils when its saturated vapor pressure equals surrounding atmospheric pressure. At elevated altitudes, atmospheric pressure drops, meaning water vapor pressure matches ambient pressure at a lower temperature.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the chemical formula and common name of "Baking Soda"?',
    options: ['Sodium Hydrogen Carbonate (NaHCO3)', 'Sodium Carbonate decahydrate (Na2CO3.10H2O)', 'Calcium Hydroxide (Ca(OH)2)', 'Sodium Hydroxide (NaOH)'],
    correctAnswerIndex: 0,
    explanation: 'Baking Soda is Sodium Bicarbonate (NaHCO3), whereas Washing Soda is Sodium Carbonate (Na2CO3.10H2O) and Caustic Soda is Sodium Hydroxide (NaOH).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which gas is predominantly released when limestone (calcium carbonate) is subjected to thermal decomposition in a kiln?',
    options: ['Carbon dioxide (CO2)', 'Carbon monoxide (CO)', 'Oxygen (O2)', 'Sulfur dioxide (SO2)'],
    correctAnswerIndex: 0,
    explanation: 'Thermal calcination of calcium carbonate decomposes it into quicklime (calcium oxide) and carbon dioxide gas: CaCO3 -> CaO + CO2.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which acid is primarily present in sour milk and curd (yogurt)?',
    options: ['Lactic Acid', 'Citric Acid', 'Acetic Acid', 'Tartaric Acid'],
    correctAnswerIndex: 0,
    explanation: 'Lactobacillus bacteria ferment lactose sugar in milk into lactic acid, which curdles milk proteins (casein) and gives yogurt its characteristic tart taste.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the pH value of pure distilled water at 25°C (room temperature)?',
    options: ['7.0 (Neutral)', '0.0', '14.0', '5.5'],
    correctAnswerIndex: 0,
    explanation: 'At 25°C, the self-ionization constant of pure water yields equal hydrogen and hydroxide ion concentrations of 10^-7 mol/L, giving an exactly neutral pH of 7.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which metal remains in liquid state at standard room temperature and pressure (25°C)?',
    options: ['Mercury (Hg)', 'Bromine (Br)', 'Gallium (Ga)', 'Cesium (Cs)'],
    correctAnswerIndex: 0,
    explanation: 'Mercury (atomic number 80) is the only transition metallic element that is liquid under standard room temperature and pressure (Bromine is a liquid non-metal).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is "Plaster of Paris" chemically?',
    options: ['Calcium Sulfate Hemihydrate (CaSO4.1/2 H2O)', 'Calcium Sulfate Dihydrate (CaSO4.2H2O)', 'Calcium Carbonate (CaCO3)', 'Magnesium Sulfate heptahydrate'],
    correctAnswerIndex: 0,
    explanation: 'Heating gypsum (CaSO4.2H2O) to 373 K (100°C) drives off three-fourths of its crystallization water to produce Plaster of Paris (CaSO4.1/2 H2O).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which cellular organelle is universally referred to as the "Powerhouse of the Cell"?',
    options: ['Mitochondria', 'Ribosome', 'Golgi Apparatus', 'Lysosome'],
    correctAnswerIndex: 0,
    explanation: 'Mitochondria generate over 90% of the cell’s chemical energy through oxidative phosphorylation in the form of adenosine triphosphate (ATP).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which organelles contain hydrolytic digestive enzymes and are termed the "Suicide Bags" of the cell?',
    options: ['Lysosomes', 'Peroxisomes', 'Vacuoles', 'Centrosomes'],
    correctAnswerIndex: 0,
    explanation: 'Lysosomes contain acidic hydrolases; when a cell is damaged or dies, lysosomes rupture and digest the cell\'s own components (autolysis).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which hormone synthesized by the beta cells of the Islets of Langerhans in the pancreas regulates blood glucose levels?',
    options: ['Insulin', 'Glucagon', 'Thyroxine', 'Adrenaline'],
    correctAnswerIndex: 0,
    explanation: 'Insulin facilitates cellular uptake of glucose from the bloodstream and stimulates glycogen synthesis in the liver; its deficiency or resistance causes diabetes mellitus.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Night blindness (Nyctalopia) and Xerophthalmia are caused by a dietary deficiency of which vitamin?',
    options: ['Vitamin A (Retinol)', 'Vitamin B1 (Thiamine)', 'Vitamin C (Ascorbic acid)', 'Vitamin D (Calciferol)'],
    correctAnswerIndex: 0,
    explanation: 'Vitamin A is essential for synthesizing rhodopsin (visual purple in retinal rods); its deficiency impairs vision in dim light and causes cornea drying.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Scurvy, characterized by bleeding gums and poor wound healing, is caused by the deficiency of:',
    options: ['Vitamin C (Ascorbic Acid)', 'Vitamin D', 'Vitamin B12', 'Vitamin K'],
    correctAnswerIndex: 0,
    explanation: 'Vitamin C is an essential co-factor for prolyl and lysyl hydroxylase enzymes in collagen cross-linking synthesis; its lack leads to tissue fragility and scurvy.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which vitamin synthesized in human skin upon exposure to solar UVB radiation is essential for intestinal calcium absorption?',
    options: ['Vitamin D (Cholecalciferol)', 'Vitamin E', 'Vitamin A', 'Vitamin B6'],
    correctAnswerIndex: 0,
    explanation: 'Photolysis of 7-dehydrocholesterol in the epidermis by sunlight yields previtamin D3, which is converted in liver and kidneys to active calcitriol.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which blood group is universally known as the "Universal Donor" in the ABO/Rh blood group system?',
    options: ['O Negative (O -ve)', 'AB Positive (AB +ve)', 'O Positive (O +ve)', 'A Negative (A -ve)'],
    correctAnswerIndex: 0,
    explanation: 'O-negative red blood cells lack A, B, and Rh (D) surface antigens, meaning they will not trigger acute hemolytic reactions in recipients with antibodies.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which blood group is known as the "Universal Recipient"?',
    options: ['AB Positive (AB +ve)', 'O Negative (O -ve)', 'A Positive (A +ve)', 'B Negative (B -ve)'],
    correctAnswerIndex: 0,
    explanation: 'AB-positive individuals possess both A and B antigens as well as the Rh antigen on their erythrocytes and have neither anti-A, anti-B, nor anti-Rh antibodies in serum.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Malaria is an infectious protozoan disease caused by Plasmodium parasites transmitted to humans by the bite of:',
    options: ['Infected female Anopheles mosquito', 'Aedes aegypti mosquito', 'Culex mosquito', 'Tsetse fly'],
    correctAnswerIndex: 0,
    explanation: 'Plasmodium sporozoites are inoculated into the human bloodstream during blood meals taken by infected female Anopheles mosquitoes.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Dengue fever and Chikungunya are viral infections transmitted primarily by which vector mosquito species?',
    options: ['Aedes aegypti', 'Anopheles stephensi', 'Culex pipiens', 'Mansonia'],
    correctAnswerIndex: 0,
    explanation: 'Aedes aegypti (the yellow fever mosquito, characterized by white lyre markings on its thorax) bites predominantly during daytime and breeds in clean stagnant urban water.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'The human heart consists of how many distinct anatomical chambers?',
    options: ['Four chambers (two atria and two ventricles)', 'Three chambers', 'Two chambers', 'Five chambers'],
    correctAnswerIndex: 0,
    explanation: 'The mammalian heart features complete double circulation with four muscular chambers: right atrium, right ventricle, left atrium, and left ventricle.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the normal resting blood pressure of a healthy human adult measured in millimeters of mercury (mm Hg)?',
    options: ['120 / 80 mm Hg', '140 / 90 mm Hg', '100 / 60 mm Hg', '160 / 100 mm Hg'],
    correctAnswerIndex: 0,
    explanation: 'Standard human resting blood pressure is defined as 120 mm Hg systolic (peak ventricular contraction) over 80 mm Hg diastolic (ventricular filling).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'The structural and functional filtering unit of the human kidney is termed:',
    options: ['Nephron', 'Neuron', 'Alveolus', 'Hepatocyte'],
    correctAnswerIndex: 0,
    explanation: 'Each human kidney contains approximately 1 to 1.3 million microscopic nephrons composed of a renal corpuscle (glomerulus and Bowman\'s capsule) and renal tubule system.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which master endocrine gland located at the base of the brain secretes Growth Hormone, TSH, ACTH, and Prolactin?',
    options: ['Pituitary Gland (Hypophysis)', 'Thyroid Gland', 'Adrenal Gland', 'Pancreas'],
    correctAnswerIndex: 0,
    explanation: 'The pituitary gland, nestled in the sella turcica of the sphenoid bone and regulated by the hypothalamus, acts as the master gland controlling other endocrine tissues.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which radioactive isotope is widely utilized in medical oncology for radiation therapy of malignant cancer tumors?',
    options: ['Cobalt-60', 'Iodine-131', 'Carbon-14', 'Uranium-235'],
    correctAnswerIndex: 0,
    explanation: 'Cobalt-60 is a synthetic radioisotope of cobalt that emits high-energy gamma rays (1.17 and 1.33 MeV), widely used in teletherapy machines to treat deep-seated cancer tumors.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which radioisotope is specifically employed for the diagnosis and therapeutic ablation of hyperthyroidism and thyroid cancer?',
    options: ['Iodine-131', 'Phosphorus-32', 'Sodium-24', 'Cobalt-60'],
    correctAnswerIndex: 0,
    explanation: 'Thyroid follicular cells actively accumulate circulating iodine; radioiodine (I-131) emits both beta particles and gamma rays to selectively ablate overactive thyroid tissue.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Radiocarbon dating, an archaeological dating technique used to determine the age of organic carbonaceous artifacts up to 50,000 years, measures the decay of:',
    options: ['Carbon-14 (half-life c. 5,730 years)', 'Carbon-12', 'Carbon-13', 'Uranium-238'],
    correctAnswerIndex: 0,
    explanation: 'Willard Libby developed radiocarbon dating based on the constant ratio of cosmic-ray produced radioactive Carbon-14 to stable Carbon-12 in living organisms, which decays with a half-life of 5,730 years after death.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the phenomenon where certain materials exhibit zero electrical resistance and expulsion of magnetic flux (Meissner Effect) below a critical temperature?',
    options: ['Superconductivity', 'Ferromagnetism', 'Semiconductivity', 'Piezoelectricity'],
    correctAnswerIndex: 0,
    explanation: 'Discovered by Heike Kamerlingh Onnes in 1911 in mercury, superconductivity involves zero electrical resistivity and perfect diamagnetism (Meissner effect) below a critical temperature Tc.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Which element is primarily used as the moderator in heavy water nuclear power reactors (PHWR) in India to slow down fast neutrons?',
    options: ['Deuterium oxide (Heavy Water - D2O)', 'Liquid sodium', 'Cadmium rods', 'Boron carbide'],
    correctAnswerIndex: 0,
    explanation: 'Pressurized Heavy Water Reactors (PHWR), the mainstay of India’s nuclear power generation (e.g. Rawatbhata, Kakrapar), use Deuterium oxide (D2O) as both neutron moderator and primary coolant.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'Control rods in nuclear reactors, used to absorb excess neutrons and regulate or halt nuclear fission chain reactions, are made of:',
    options: ['Cadmium or Boron', 'Uranium-238', 'Lead', 'Beryllium'],
    correctAnswerIndex: 0,
    explanation: 'Cadmium and boron have extraordinarily high neutron absorption cross-sections, allowing them to capture free neutrons without undergoing fission.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'general-science',
    questionText: 'What is the speed of light in a vacuum, which serves as a fundamental physical constant (c)?',
    options: ['Approximately 3 x 10^8 meters per second (299,792,458 m/s)', '3 x 10^6 m/s', '3 x 10^10 m/s', '330 m/s'],
    correctAnswerIndex: 0,
    explanation: 'The speed of light in vacuum is exactly 299,792,458 meters per second (commonly approximated as 3 x 10^8 m/s).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },

  // --- AGRICULTURE & SCIENCE TECHNOLOGY (30 Questions) ---
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which symbiotic bacterium forms root nodules in leguminous crops and fixes atmospheric nitrogen into soil ammonia?',
    options: ['Rhizobium', 'Azotobacter', 'Clostridium', 'Nitrosomonas'],
    correctAnswerIndex: 0,
    explanation: 'Rhizobium bacteria establish an endosymbiotic relationship with root hairs of legumes (pulses, beans), expressing nitrogenase enzymes to convert atmospheric N2 into bioavailable ammonium.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'What is the ideal N-P-K (Nitrogen, Phosphorus, Potassium) fertilizer application ratio recommended for balanced cereal crop cultivation in India?',
    options: ['4 : 2 : 1', '2 : 1 : 1', '1 : 2 : 1', '4 : 4 : 2'],
    correctAnswerIndex: 0,
    explanation: 'The agronomic optimum macro-nutrient ratio for general cereal crop production (wheat and rice) in India is recommended as 4:2:1 (N:P:K).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Neem-coated urea was made 100% mandatory for all domestic agricultural subsidized urea in India in 2015 to achieve which benefit?',
    options: ['Slow down nitrogen release, improve crop nitrogen absorption, and prevent diversion to chemical factories', 'Increase soil acidity', 'Repel avian pests from crop fields', 'Increase grain moisture'],
    correctAnswerIndex: 0,
    explanation: 'Neem oil acts as a natural nitrification inhibitor, retarding the conversion of nitrogen into volatile nitrates and ensuring steady uptake while preventing illicit industrial diversion.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The "System of Rice Intensification" (SRI) method of paddy cultivation is characterized by:',
    options: [
      'Transplanting single young seedlings at wider spacing with intermittent alternate wetting and drying instead of continuous flooding',
      'Continuous flooding with chemical broadcast seeding',
      'Dense broadcasting of unsprouted seeds',
      'Growing rice under greenhouse canopies',
    ],
    correctAnswerIndex: 0,
    explanation: 'SRI (originating in Madagascar) drastically reduces water requirements by 30-50% and seed inputs by 80% while enhancing root aeration and grain yield through alternate wetting and drying.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which micro-irrigation method delivers water and dissolved nutrients directly to the plant root zone drop-by-drop, achieving up to 90% water use efficiency?',
    options: ['Drip Irrigation (Trickle Irrigation)', 'Sprinkler Irrigation', 'Flood Furrow Irrigation', 'Basin Irrigation'],
    correctAnswerIndex: 0,
    explanation: 'Drip irrigation utilizes drippers/emitters to supply water directly at root level, virtually eliminating evaporation and deep percolation losses under Pradhan Mantri Krishi Sinchayee Yojana (PMKSY - "Per Drop More Crop").',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which Indian state became the world’s first fully certified 100% organic farming state in 2016?',
    options: ['Sikkim', 'Kerala', 'Himachal Pradesh', 'Uttarakhand'],
    correctAnswerIndex: 0,
    explanation: 'In January 2016, Sikkim was declared the world\'s first 100% organic state, having transitioned all agricultural land to organic practices and winning the UN Future Policy Gold Award in 2018.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Bt Cotton, the only genetically modified (GM) commercial crop approved for commercial cultivation in India (2002), contains genes from which soil bacterium?',
    options: ['Bacillus thuringiensis', 'Agrobacterium tumefaciens', 'Pseudomonas putida', 'Escherichia coli'],
    correctAnswerIndex: 0,
    explanation: 'Bt cotton incorporates Cry1Ac and Cry2Ab endotoxin genes derived from the soil bacterium Bacillus thuringiensis to confer biological resistance against the cotton bollworm (Helicoverpa armigera).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'In India, which apex statutory committee under the Ministry of Environment, Forest and Climate Change approves the environmental release of Genetically Modified Organisms (GMOs)?',
    options: ['Genetic Engineering Appraisal Committee (GEAC)', 'Indian Council of Agricultural Research (ICAR)', 'Department of Biotechnology (DBT)', 'Food Safety and Standards Authority of India (FSSAI)'],
    correctAnswerIndex: 0,
    explanation: 'GEAC functions under the Rules for the Manufacture, Use/Import/Export and Storage of Hazardous Microorganisms/Genetically Engineered Organisms (1989) under the Environment Protection Act 1986.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The "Soil Health Card" scheme was launched by Prime Minister Narendra Modi in February 2015 from Suratgarh (Rajasthan) with which primary objective?',
    options: [
      'Issue farm-level soil nutrient status cards assessing 12 chemical parameters to recommend customized fertilizer dosages',
      'Provide crop insurance against hailstorms',
      'Issue land ownership deeds to marginal farmers',
      'Distribute free hybrid seeds',
    ],
    correctAnswerIndex: 0,
    explanation: 'Soil Health Cards test 12 parameters (N, P, K, S, Zn, Fe, Cu, Mn, Bo, pH, EC, OC) to advise farmers on judicious chemical and organic fertilizer inputs under the motto "Swasth Dhara, Khet Hara".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which technique is employed to correct strongly acidic soils (pH < 5.5) commonly encountered in Jharkhand and Eastern India?',
    options: ['Application of agricultural lime (calcium carbonate / dolomite)', 'Application of gypsum (calcium sulfate)', 'Excessive flooding with river water', 'Spraying dilute sulfuric acid'],
    correctAnswerIndex: 0,
    explanation: 'Acidic soils have high aluminum and hydrogen ion toxicity; applying agricultural limestone (CaCO3) neutralizes acidity, elevates soil pH, and unlocks phosphorus for root uptake.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which mineral is applied to reclaim alkaline and sodic soils (high exchangeable sodium percentage)?',
    options: ['Gypsum (Calcium Sulfate)', 'Lime', 'Rock phosphate', 'Potash'],
    correctAnswerIndex: 0,
    explanation: 'Gypsum (CaSO4.2H2O) replaces sodium ions adsorbed on clay minerals with calcium ions; the displaced sodium forms soluble sodium sulfate and is leached away by irrigation.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Who is revered as the "Father of the Green Revolution" globally, receiving the Nobel Peace Prize in 1970 for developing semi-dwarf wheat varieties?',
    options: ['Dr. Norman Borlaug', 'Dr. M. S. Swaminathan', 'Dr. Verghese Kurien', 'William Gaud'],
    correctAnswerIndex: 0,
    explanation: 'American agronomist Dr. Norman Borlaug developed high-yielding semi-dwarf disease-resistant wheat cultivars at CIMMYT in Mexico that averted mass famine in South Asia.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Who is recognized as the "Father of the Green Revolution in India" and was posthumously conferred the Bharat Ratna in 2024?',
    options: ['Dr. M. S. Swaminathan', 'C. Subramaniam', 'Dr. Norman Borlaug', 'B. P. Pal'],
    correctAnswerIndex: 0,
    explanation: 'Eminent geneticist Dr. M. S. Swaminathan cross-bred semi-dwarf Mexican wheat with Indian lines (Kalyan Sona, Sonalika) to usher in food self-sufficiency, honored with Bharat Ratna in 2024.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Who coined the famous term "Green Revolution" in 1968 to describe the dramatic increase in agricultural food production?',
    options: ['William Gaud (Director of USAID)', 'Norman Borlaug', 'M. S. Swaminathan', 'Indira Gandhi'],
    correctAnswerIndex: 0,
    explanation: 'William Gaud, Administrator of the U.S. Agency for International Development (USAID), coined the phrase "Green Revolution" in a speech in Washington in March 1968.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: '"Golden Rice" is a genetically engineered biofortified variety of rice developed to biosynthesize which precursor nutrient?',
    options: ['Beta-carotene (provitamin A)', 'Iron and Zinc', 'Vitamin C', 'Lysine protein'],
    correctAnswerIndex: 0,
    explanation: 'Golden Rice is genetically engineered with daffodil/maize genes to synthesize beta-carotene in the edible rice endosperm, aimed at eliminating childhood blindness caused by Vitamin A deficiency.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which blue-green alga (cyanobacterium) is widely utilized as a nitrogen-fixing biofertilizer in waterlogged paddy fields?',
    options: ['Anabaena azollae (in symbiotic association with Azolla)', 'Spirogyra', 'Chlamydomonas', 'Ulothrix'],
    correctAnswerIndex: 0,
    explanation: 'The aquatic fern Azolla hosts the nitrogen-fixing cyanobacterium Anabaena azollae, adding up to 30–40 kg of organic nitrogen per hectare to flooded rice soils.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'What is "Hydroponics" in agricultural science?',
    options: ['The technique of growing plants without soil in nutrient-rich water solutions', 'The cultivation of marine aquatic plants', 'Terrace cultivation on steep hillsides', 'Mulching using dried crop straw'],
    correctAnswerIndex: 0,
    explanation: 'Hydroponics is a form of soilless agriculture where plant root systems are bathed in oxygenated mineral nutrient aqueous solutions in controlled environment settings.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'What is "Aeroponics"?',
    options: ['Growing plants in an air or mist environment without soil or aggregate medium', 'Growing crops in space capsules', 'Spraying pesticides from drones', 'Cultivating hanging orchards'],
    correctAnswerIndex: 0,
    explanation: 'Aeroponics suspends plant roots in enclosed chambers where they are intermittently misted with nutrient aerosol mist, requiring up to 95% less water than traditional soil farming.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The CRISPR-Cas9 technology, which won the 2020 Nobel Prize in Chemistry, is revolutionary in biological sciences for:',
    options: ['Targeted precision genome editing (molecular gene scissors)', 'Sequencing ancient fossil bones', 'Synthesizing artificial antibodies', 'Cloning extinct mammals'],
    correctAnswerIndex: 0,
    explanation: 'Discovered by Jennifer Doudna and Emmanuelle Charpentier, CRISPR-Cas9 acts as a programmable RNA-guided molecular scissor capable of cutting and editing exact DNA sequences in plants, animals, and humans.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'In India, the National Gene Bank preserving crop germplasm seeds at -18°C is maintained at:',
    options: ['National Bureau of Plant Genetic Resources (NBPGR), New Delhi', 'IARI Pusa, New Delhi', 'Forest Research Institute, Dehradun', 'Central Rice Research Institute, Cuttack'],
    correctAnswerIndex: 0,
    explanation: 'The National Gene Bank at ICAR-NBPGR in New Delhi is the second largest seed genebank in the world, conserving over 4.5 lakh unique plant germplasm accessions.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The International Crops Research Institute for the Semi-Arid Tropics (ICRISAT), a premier global agricultural research center, has its headquarters at:',
    options: ['Patancheru, Hyderabad (Telangana)', 'Bengaluru', 'New Delhi', 'Bhopal'],
    correctAnswerIndex: 0,
    explanation: 'ICRISAT, founded in 1972, is headquartered at Patancheru near Hyderabad, focusing on improving dryland crops like sorghum, pearl millet, chickpea, pigeonpea, and groundnut.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The Central Tuber Crops Research Institute (CTCRI) is located at:',
    options: ['Thiruvananthapuram (Kerala)', 'Coimbatore', 'Shimla', 'Nagpur'],
    correctAnswerIndex: 0,
    explanation: 'ICAR-CTCRI is located at Sreekariyam, Thiruvananthapuram, Kerala, conducting research on tropical root and tuber crops like cassava, sweet potato, and yams.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which agricultural research institute located at Cuttack, Odisha, developed seminal flood-tolerant rice varieties (such as Swarna-Sub1)?',
    options: ['National Rice Research Institute (NRRI)', 'Indian Agricultural Research Institute', 'Central Soil Salinity Research Institute', 'Directorate of Rice Development'],
    correctAnswerIndex: 0,
    explanation: 'ICAR-National Rice Research Institute (NRRI) in Cuttack, founded in 1946, has bred premier high-yielding, pest-resistant, and submergence-tolerant rice strains for Asian ecologies.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Birsa Agricultural University (BAU), established in 1981 to advance agronomic science and forestry in the plateau region, is located at:',
    options: ['Kanke, Ranchi (Jharkhand)', 'Dumka', 'Hazaribagh', 'Jamshedpur'],
    correctAnswerIndex: 0,
    explanation: 'Birsa Agricultural University was inaugurated by Prime Minister Indira Gandhi on June 26, 1981, at Kanke, Ranchi, specializing in dryland farming and tribal hill agriculture.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The Indian Institute of Natural Resins and Gums (formerly Indian Lac Research Institute), pioneer in lac production and processing, is located in Jharkhand at:',
    options: ['Namkum, Ranchi', 'Chas, Bokaro', 'Chaibasa', 'Giridih'],
    correctAnswerIndex: 0,
    explanation: 'Established in 1924 at Namkum in Ranchi, it is the world’s premier institute devoted to lac insects and resin technology (renamed National Institute of Secondary Agriculture in 2022).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which insect produces commercial natural "Lac" resin cultivated extensively across Jharkhand on host trees like Ber, Palas, and Kusum?',
    options: ['Kerria lacca', 'Bombyx mori', 'Apis dorsata', 'Antheraea mylitta'],
    correctAnswerIndex: 0,
    explanation: 'The tiny scale insect Kerria lacca secretes natural resinous lac as a protective encrustation over host tree twigs, making Jharkhand the supplier of over 50% of India’s lac.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'Which wild silkworm species native to Jharkhand and Central India feeds on Asan and Arjun trees to produce coarse copper-colored "Tussar Silk"?',
    options: ['Antheraea mylitta', 'Bombyx mori', 'Samia ricini', 'Antheraea assamensis'],
    correctAnswerIndex: 0,
    explanation: 'Antheraea mylitta is the wild silkmoth that yields tropical Tussar silk, of which Jharkhand is the leading producer in India (centered around Santhal Parganas and Kolhan).',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'What is the "Kisan Drone" scheme promoted under the Sub-Mission on Agricultural Mechanization (SMAM)?',
    options: [
      'Subsidized deployment of unmanned aerial vehicles (UAVs) for crop assessment, digitizing land records, and precision spraying of pesticides and liquid fertilizers',
      'Delivery of tractor parts to farmers',
      'Surveillance of wild animals near forests',
      'Artificial cloud seeding for rainfall',
    ],
    correctAnswerIndex: 0,
    explanation: 'Kisan Drones perform precision agriculture by spraying micronutrients and nano-urea uniformly while reducing human chemical exposure and water consumption.',
    difficulty: 'Easy',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'India’s first commercial Liquid Nano-Urea plant developed by IFFCO was inaugurated in 2022 at:',
    options: ['Kalol (Gujarat)', 'Phulpur (UP)', 'Sindri (Jharkhand)', 'Barauni (Bihar)'],
    correctAnswerIndex: 0,
    explanation: 'IFFCO developed the proprietary liquid nano-urea formulation and commissioned the world’s first commercial manufacturing plant at Kalol in Gandhinagar, Gujarat.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'agriculture-science',
    questionText: 'The historic fertilizer factory established in 1951 in Dhanbad district of Jharkhand, recently revived as HURL in 2022, is located at:',
    options: ['Sindri', 'Dhanbad town', 'Chirkunda', 'Katras'],
    correctAnswerIndex: 0,
    explanation: 'The Sindri fertilizer plant was India’s first state-owned industrial fertilizer complex, modernized and dedicated to the nation as Hindustan Urvarak & Rasayan Limited (HURL) in 2022.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },

  // --- INFORMATION & COMMUNICATION TECHNOLOGY (25 Questions) ---
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'How many bits constitute a standard "Byte" in computer architecture?',
    options: ['8 bits', '4 bits', '16 bits', '32 bits'],
    correctAnswerIndex: 0,
    explanation: 'In digital computing, a byte is a unit of digital information that most commonly consists of eight bits (a 4-bit unit is termed a nibble).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is the full form of the standard networking protocol "TCP/IP"?',
    options: ['Transmission Control Protocol / Internet Protocol', 'Telecommunication Control Program / Interface Protocol', 'Transport Channel Protocol / Information Protocol', 'Terminal Connection Protocol / Internet Provider'],
    correctAnswerIndex: 0,
    explanation: 'TCP/IP (Transmission Control Protocol / Internet Protocol) is the foundational communications suite of the Internet, designed by Vint Cerf and Bob Kahn.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is the length (address space) of an Internet Protocol version 6 (IPv6) address compared to an IPv4 address?',
    options: ['128 bits (IPv6) versus 32 bits (IPv4)', '64 bits versus 32 bits', '256 bits versus 64 bits', '128 bits versus 64 bits'],
    correctAnswerIndex: 0,
    explanation: 'IPv4 uses 32-bit addresses (yielding ~4.3 billion unique addresses), whereas IPv6 expands the address space to 128 bits, providing 2^128 (approx 3.4 x 10^38) addresses.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Which non-volatile firmware stored on a ROM chip on the computer motherboard initializes and tests hardware during system bootup?',
    options: ['BIOS (Basic Input/Output System)', 'RAM', 'Cache Memory', 'Virtual Memory'],
    correctAnswerIndex: 0,
    explanation: 'The BIOS (or modern UEFI) executes the Power-On Self-Test (POST) upon powering up and boots the operating system from storage into RAM.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Who is recognized as the inventor of the World Wide Web (WWW) in 1989 at CERN?',
    options: ['Tim Berners-Lee', 'Vint Cerf', 'Alan Turing', 'Bill Gates'],
    correctAnswerIndex: 0,
    explanation: 'Sir Tim Berners-Lee invented the World Wide Web, HTML (Hypertext Markup Language), HTTP, and the first web client/server at CERN in Geneva in 1989.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is "Phishing" in cybersecurity terminology?',
    options: [
      'A social engineering cyber attack using fraudulent emails or counterfeit websites to trick victims into revealing passwords or credit card numbers',
      'Overwhelming a server with dummy network packets',
      'Infecting a computer via an unauthorized flash drive',
      'Scanning open ports on a corporate router',
    ],
    correctAnswerIndex: 0,
    explanation: 'Phishing mimics legitimate trusted entities (such as banks or government agencies) to deceive users into disclosing sensitive personal credentials.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What type of malicious software encrypts a victim’s computer files and demands financial payment for the decryption key?',
    options: ['Ransomware', 'Spyware', 'Adware', 'Trojan Horse'],
    correctAnswerIndex: 0,
    explanation: 'Ransomware (such as WannaCry, LockBit) encrypts files with asymmetric cryptography and demands cryptocurrency ransom for decryption access.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Which Section of the Information Technology (IT) Act, 2000, was struck down by the Supreme Court of India in the Shreya Singhal case (2015) for violating free speech?',
    options: ['Section 66A', 'Section 66F', 'Section 69A', 'Section 79'],
    correctAnswerIndex: 0,
    explanation: 'In Shreya Singhal v. Union of India (2015), the Supreme Court struck down Section 66A for being unconstitutionally vague and chilling the freedom of speech under Article 19(1)(a).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Under Section 69A of the IT Act, 2000, the Central Government has statutory powers to:',
    options: ['Issue directions to block public access to any computer information in the interest of national sovereignty, defense, or public order', 'Seize all computer hardware', 'Suspend all mobile SIM cards in a state', 'Impose internet taxes on search engines'],
    correctAnswerIndex: 0,
    explanation: 'Section 69A empowers designated central authorities to issue orders blocking web URLs and apps in the interest of India’s defense, sovereignty, and public order.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'The Indian Computer Emergency Response Team (CERT-In), the national nodal agency for responding to cybersecurity incidents, operates under which ministry?',
    options: ['Ministry of Electronics and Information Technology (MeitY)', 'Ministry of Home Affairs', 'Ministry of Defence', 'Prime Minister’s Office'],
    correctAnswerIndex: 0,
    explanation: 'CERT-In was established in 2004 under Section 70B of the Information Technology Act under MeitY to coordinate cybersecurity defenses and incident responses.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is India’s indigenous supercomputer series developed by C-DAC (Centre for Development of Advanced Computing) called?',
    options: ['PARAM', 'AIRAWAT', 'PRATYUSH', 'MIHIR'],
    correctAnswerIndex: 0,
    explanation: 'C-DAC developed the landmark PARAM series (starting with PARAM 8000 in 1991 under Vijay Bhatkar, up to modern PARAM Shivay, PARAM Rudra, and PARAM Ganga under the National Supercomputing Mission).',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Which Indian AI supercomputer installed at C-DAC Pune was ranked among the top 100 global supercomputers in the Top500 list in 2023?',
    options: ['AIRAWAT-PSAI', 'PARAM Siddhi-AI', 'Pratyush', 'Mihir'],
    correctAnswerIndex: 0,
    explanation: 'AIRAWAT (AI Research, Analytics and Knowledge Dissemination Platform) at C-DAC Pune operates at 13 petaflops and achieved global recognition in the Top500 rankings.',
    difficulty: 'Medium',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is the underlying technological architecture of cryptocurrencies like Bitcoin and smart contracts like Ethereum?',
    options: ['Distributed Ledger Technology (Blockchain)', 'Relational SQL Databases', 'Centralized Mainframe Hosting', 'Quantum Computing'],
    correctAnswerIndex: 0,
    explanation: 'Blockchain is a decentralized, cryptographically linked distributed ledger where transactions are validated by consensus protocols without intermediaries.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Which semiconductor material is most universally used in the fabrication of integrated circuits (microchips) and solar cells?',
    options: ['Silicon (Si)', 'Germanium (Ge)', 'Copper (Cu)', 'Gallium Arsenide (GaAs)'],
    correctAnswerIndex: 0,
    explanation: 'Silicon\'s natural abundance, stable crystalline structure, and ability to form an insulating silicon dioxide (SiO2) layer make it the bedrock of microelectronics.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'The Digital Personal Data Protection (DPDP) Act was passed by the Parliament of India in which year?',
    options: ['2023', '2021', '2019', '2016'],
    correctAnswerIndex: 0,
    explanation: 'The DPDP Act 2023 established a legal framework for processing digital personal data, safeguarding individual consent and establishing the Data Protection Board of India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Which Indian space mission successfully landed the Vikram lander on the South Pole region of the Moon on August 23, 2023?',
    options: ['Chandrayaan-3', 'Chandrayaan-2', 'Mangalyaan', 'Aditya-L1'],
    correctAnswerIndex: 0,
    explanation: 'ISRO’s Chandrayaan-3 achieved a historic soft landing on the lunar south pole with lander Vikram and rover Pragyan, commemorating August 23 as National Space Day.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is the name of the landing site of Chandrayaan-3’s Vikram lander near the Moon’s south pole officially designated by Prime Minister Narendra Modi?',
    options: ['Shiv Shakti Point', 'Tiranga Point', 'Jawahar Point', 'Atal Point'],
    correctAnswerIndex: 0,
    explanation: 'The touchdown location of Chandrayaan-3 was named "Shiv Shakti Point", while Chandrayaan-2\'s impact site was named "Tiranga Point".',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'Which space observatory was launched by ISRO in September 2023 to continuously monitor the Sun from the Sun-Earth Lagrange Point 1 (L1)?',
    options: ['Aditya-L1', 'XPoSat', 'AstroSat', 'NISAR'],
    correctAnswerIndex: 0,
    explanation: 'Aditya-L1 was launched by PSLV-C57 to orbit the L1 Lagrange point (1.5 million km from Earth) to study solar corona dynamics, coronal mass ejections, and space weather.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2024,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'The Unified Payments Interface (UPI) developed by the National Payments Corporation of India (NPCI) was launched in which year?',
    options: ['2016', '2014', '2018', '2015'],
    correctAnswerIndex: 0,
    explanation: 'NPCI launched UPI as an instant real-time payment system on April 11, 2016, revolutionizing digital retail payments in India.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2021,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'In computer networking, what does the abbreviation "DNS" stand for?',
    options: ['Domain Name System', 'Digital Network Service', 'Data Navigation Server', 'Direct Network Switch'],
    correctAnswerIndex: 0,
    explanation: 'The Domain Name System (DNS) translates human-friendly alphanumeric domain names (like example.com) into numerical IP addresses (like 192.0.2.1).',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is the primary operational distinction between "Cloud Computing" and traditional on-premises data centers?',
    options: [
      'On-demand delivery of compute, storage, and databases over the internet with pay-as-you-go pricing',
      'Data stored solely on portable solid-state disks',
      'Transmission of encrypted files through satellite dishes',
      'Exclusive usage of supercomputers for scientific simulations',
    ],
    correctAnswerIndex: 0,
    explanation: 'Cloud computing (IaaS, PaaS, SaaS) allows elastic, on-demand scaling of computing resources over the internet without owning physical server hardware.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is "Quantum Supremacy" (Quantum Advantage)?',
    options: [
      'The demonstration that a programmable quantum computer can solve a problem that no classical supercomputer could solve in any feasible time',
      'A quantum computer running on solar power',
      'The replacement of silicon chips with carbon chips',
      'An impenetrable optical fiber cable network',
    ],
    correctAnswerIndex: 0,
    explanation: 'Quantum advantage occurs when a quantum processor utilizing superposition and entanglement performs a calculation intractable for the fastest classical supercomputers.',
    difficulty: 'Medium',
    questionType: 'PYQ_INSPIRED',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'The "BharatNet" project undertaken by the Department of Telecommunications aims to:',
    options: [
      'Connect all 2.5 lakh Gram Panchayats in India with high-speed optical fiber broadband connectivity',
      'Provide free satellite TV to all schools',
      'Lay undersea cables to Southeast Asia',
      'Install 5G towers on national highways',
    ],
    correctAnswerIndex: 0,
    explanation: 'BharatNet (formerly National Optical Fibre Network - NOFN) provides middle-mile optical fiber connectivity to all village Gram Panchayats to bridge the rural-urban digital divide.',
    difficulty: 'Easy',
    questionType: 'PYQ',
    sourceType: 'OFFICIAL_PYQ',
    year: 2016,
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What is the primary difference between a "Virus" and a "Worm" in computer malware classification?',
    options: [
      'A worm is a self-replicating standalone program that spreads across computer networks without needing a host program, whereas a virus must attach itself to an executable file',
      'A virus targets only hardware while a worm targets software',
      'A worm only affects mobile devices',
      'A virus cannot be removed by antivirus software',
    ],
    correctAnswerIndex: 0,
    explanation: 'Computer worms exploit operating system network vulnerabilities to propagate independently from machine to machine without requiring human activation or host file modification.',
    difficulty: 'Medium',
    questionType: 'PRACTICE',
    sourceType: 'REFERENCE_BOOK',
    qaStatus: 'VERIFIED',
  },
  {
    subjectSlug: 'jpsc-science',
    topicSlug: 'information-technology',
    questionText: 'What does "Open Source Software" (OSS) signify regarding software licensing?',
    options: [
      'Software whose source code is released under a license where the copyright holder grants users the rights to study, modify, and distribute the code freely',
      'Software available free of charge but with closed proprietary source code (freeware)',
      'Software designed exclusively for government servers',
      'Trial software with an expiration date',
    ],
    correctAnswerIndex: 0,
    explanation: 'Open Source Software (such as Linux, Android, Python) grants public access to the source code, encouraging collaborative enhancement and peer transparency.',
    difficulty: 'Easy',
    questionType: 'PRACTICE',
    sourceType: 'INTERNAL',
    qaStatus: 'VERIFIED',
  },
];
